### ISSUE TITLE
yapf install error

### ISSUE THREAD

**Issue by wuxumjy** [google/yapf#103]
hi
when I run "pip install yapf" in my computer, some error happen like this:
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    import yapf
  File "/root/yapf-master/yapf/__init__.py", line 35, in <module>
    from yapf.yapflib import yapf_api
  File "/root/yapf-master/yapf/yapflib/yapf_api.py", line 41, in <module>
    from yapf.yapflib import blank_line_calculator
  File "/root/yapf-master/yapf/yapflib/blank_line_calculator.py", line 35
    'simple_stmt', 'small_stmt', 'expr_stmt', 'print_stmt', 'del_stmt',
                 ^
SyntaxError: invalid syntax

**Comment by eliben** [comment]
What version of Python are you using?

Does the error happen when you install yapf in another manner, like downloading the source and installing with `python setup.py install` ?

**Comment by hayd** [comment]
@wuxumjy can you upgrade to the lastest version and see if you still see the same error?

    pip install yapf -U

**Comment by macau23** [comment]
I can see this on RHEL6:

    pip install yapf -U

**Comment by macau23** [comment]
Not a bug; sorry didn't see this:

`YAPF supports Python 2.7...`
