### ISSUE TITLE
PyPi package has no Home-page

### ISSUE THREAD

**Issue by nikosavola** [google/yapf#1049]
I was looking to get to this GitHub page or some other site for the project by doing
```bash
pip show yapf
```
and clicking a link, but currently it returns
```
Name: yapf
Version: 0.32.0
Summary: A formatter for Python code.
Home-page: UNKNOWN
Author: Google Inc.
Author-email:
License: Apache License, Version 2.0
Location: c:\users\niko\appdata\local\programs\python\python310\lib\site-packages
Requires:
Required-by:
```
where the _Home-page:_ field is not set. I suggest changing it to https://github.com/google/yapf. I guess this needs to be done somewhere in [setup.py](https://github.com/google/yapf/blob/main/setup.py)?

**Comment by raj-kapil** [comment]
Hey @nikosavola, I opened a PR for this [#1051 ](https://github.com/google/yapf/pull/1051) to fix the above mentioned issue.

**Comment by thiagowfx** [comment]
Fixed by https://github.com/google/yapf/pull/1051
