### ISSUE TITLE
Plans for release 0.33.0?

### ISSUE THREAD

**Issue by hartwork** [google/yapf#1057]
Hi!

The latest release off `main` 0.32.0 was release about 13 months ago. GitHub counts 44 commits on `main` since 0.32.0 with this overall diff: https://github.com/google/yapf/compare/v0.32.0...main . Are there plans for a release 0.33.0 off `main`?

Best, Sebastian

**Comment by Spitfire1900** [comment]
@bwendling what is involved in staging a new version for release? Does someone have the PyPi keys available to publish a new release.

**Comment by hartwork** [comment]
Based on this picture…

![yapf_maint](https://user-images.githubusercontent.com/1577132/232783741-b94cf861-6dbe-45e8-83e8-c7907fb3575f.png)

…at https://pypi.org/project/yapf/ I believe that these three people have write access to yapf on PyPI:

- Bill Wendling — @bwendling
- Dustin Ingram — @di
- Eli Bendersky — @eliben

**Comment by bwendling** [comment]
It is done. :-)
