### ISSUE TITLE
Enforce pre-commit clean code via CI?

### ISSUE THREAD

**Issue by hartwork** [google/yapf#1081]
Hi!

I'm considering to provide a pull request that enforces pre-commit clean CI because `main` is not pre-commit clean today and CI would prevent that from happening again. For that pull request to be healthy:
- pre-commit files would have ideally gone down to a single copy already (issue #1077) at that point
- Pull requests #1078, #1079, #1080 would ideally have been merged already
- It would need to be decided if (or when) mass-applying yapf to itself is considered tolerable with the current set of open pull requests around.

What do you think?

**Comment by Spitfire1900** [comment]
That is fine, I would also like to see pre-commit handle virtual environment installs of the workspace. Pre-commit today works in terminals when a venv is activated but this does not work when committing via the Source Control pane of VSCode.

**Comment by hartwork** [comment]
@Spitfire1900 I'm not entirely sure how that relates to CI — could you help me see the connection?

Regarding virtual environments, pre-commit can be used completely without virtualenvs, e.g. I have package `dev-vcs/pre-commit` installed system-wide on my Gentoo box. Many other distros [have it packaged](https://repology.org/project/python:pre-commit/badges) too.

Regarding making local commits, Git commit hooks as e.g. activated by `pre-commit install --install-hooks` should be running whenever someone makes new Git commits through Git as a subprocess unless passing `--no-verify`. So dependending on how IDEs put new commits into Git, it may just need activation of the related pre-commit hook.

PS: I have [six pull request waiting for review](https://github.com/google/yapf/pulls/hartwork) in here today, so I will postpone creating more until that number is near zero. If you can help with review and/or merging, that would rock.

What do you think?

**Comment by Spitfire1900** [comment]
Sorry. I'll clarify, and it can be a different issue (arguably this is a problem with VSCode).


While VSCode supports virtual environments, it does not perform any git actions initiated through its GUI in an activated virtual environment, even if one already exists.

**Comment by hartwork** [comment]
@Spitfire1900 I think it is indeed a separate issue then, thanks for the clarification :+1:

**Comment by thiagowfx** [comment]
You probably meant https://github.com/google/yapf/pull/1093

**Comment by hartwork** [comment]
@thiagowfx indeed, yes, thanks!

**Comment by Spitfire1900** [comment]
Would be part of the idea of this pre-commit --run-all as part of ci.yml?

I would not be opposed to that idea, but I don't know if the output would be very helpful in the event of job failure.

I am a little bit more interested in using GitHub Actions to auto format PR's without requiring people to have pre-commit installed locally or have to deal with pre-commit blocking making commits locally and/or coming back to a branch because formatting was off after you've already context-switched.

https://youtu.be/RAelLqnnOp0

**Comment by hartwork** [comment]
> Would be part of the idea of this pre-commit --run-all as part of ci.yml?

@Spitfire1900 you have a good point in that I should remove the now-duplicate parts from `ci.yml`. That will make the CI faster due to more parallesm and have `ci.yml` be about one major thing: Running the test suite, great. Give me a minute.


> I would not be opposed to that idea, but I don't know if the output would be very helpful in the event of job failure.

The action runs `pre-commit run -a --show-diff-on-failure` — you will see helpful diffs whenever formatting is off, there will be no guessing games :smiley: 


> I am a little bit more interested in using GitHub Actions to auto format PR's without requiring people to have pre-commit installed locally or have to deal with pre-commit blocking making commits locally and/or coming back to a branch because formatting was off after you've already context-switched.
> 
> https://youtu.be/RAelLqnnOp0

The CI only enforces that the overall diff is clean; developers can achieve that with or without pre-commit installed as a local pre-commit Git hook or not.
