### ISSUE TITLE
cant format file contains syntax match 

### ISSUE THREAD

**Issue by zxcvbnm3057** [google/yapf#1085]
While try to format a file contains new match syntax. Error occurs.

Error information:

lib2to3.pgen2.parse.ParseError: bad input: type=1, value='line',

How to reproduce:

Try format code like this:
```
a=3
b=0
match a:
    case 0:
        b = 1
    case _:
        b=2

print(b) 
```

version info:
Python 3.10.2 with yapf 0.33.0

**Comment by Spitfire1900** [comment]
Open PR for this https://github.com/google/yapf/pull/1067

**Comment by Spitfire1900** [comment]
@zxcvbnm3057 please try out a build of PR https://github.com/google/yapf/pull/1067 and contribute there.
