### ISSUE TITLE
Using pylintrc files

### ISSUE THREAD

**Issue by jhughesbiot** [google/yapf#1094]
Looking for an example on using a custom pylintrc file with this project.  Can't seem to find any references other than adding a file to the project and no examples appear to be present for this.  Anybody able to point me to the right spot for this?

**Comment by Spitfire1900** [comment]
Yapf doesn't use pylintrc files

From https://github.com/google/yapf/tree/main#formatting-style
> YAPF will search for the formatting style in the following manner:

Specified on the command line
In the [style] section of a .style.yapf file in either the current directory or one of its parent directories.
In the [yapf] section of a setup.cfg file in either the current directory or one of its parent directories.
In the [tool.yapf] section of a pyproject.toml file in either the current directory or one of its parent directories.
In the [style] section of a ~/.config/yapf/style file in your home directory.

**Comment by jhughesbiot** [comment]
So why does a pylintrc file exist anywhere in this project if it there is no use for it?

**Comment by Spitfire1900** [comment]
The [pylintrc] file here exists for developers of yapf, and not for end users of yapf.
