### ISSUE TITLE
0.40.0 version was created under wrong tag 0.44.0

### ISSUE THREAD

**Issue by qarmin** [google/yapf#1106]
In pypi I see version 0.40.0, but here there is only version 0.44.0

**Comment by bwendling** [comment]
Doh! I hopefully corrected this. Thanks for letting me know.

**Comment by mgorny** [comment]
Now the tag is `v.40.0`, i.e. one `0` is missing.

**Comment by bwendling** [comment]
*grumble* Done.

**Comment by mgorny** [comment]
Thanks!
