### ISSUE TITLE
Delete accidental Git tag v.40.0?

### ISSUE THREAD

**Issue by hartwork** [google/yapf#1117]
Hi @bwendling could you delete accidental Git tag `v.40.0` where the major version "0" is missing?

![tags_Screenshot_20230621_165530](https://github.com/google/yapf/assets/1577132/910d87d8-3ce9-4dac-ad33-efe095e0a14e)

Thanks!

**Comment by bwendling** [comment]
Hmm...Thought I had done that all ready. Done.
