### ISSUE TITLE
error is raised at `for _name, _value in list(globals().items()):` in yapf_third_party/_ylib2to3/pgen2/token.py

### ISSUE THREAD

**Issue by eunwoosh** [google/yapf#1118]
Hi, I got an error when importing yapf whose version is 0.40.1
When the yapf is imported, yapf_third_party/_ylib2to3/pgen2/token.py is executed
and then error is raised as below.
![image](https://github.com/google/yapf/assets/92974184/858e1c63-8021-41bd-85c2-02fe7c022c96)
I think it occurs to other people also https://github.com/scipy/scipy/issues/11479
Something weird is it appears not in all cases.
It can be solved easily if `for _name, _value in list(globals().items()):` is changed to `for _name, _value in list(globals().copy().items()):`.
Could you fix this bug?

**Comment by bwendling** [comment]
Please add a code snippet that replicates this error.

**Comment by eunwoosh** [comment]
I'm not using yapf directly and this error is raised only if some conditions are meet (I don't know which condition it is).
And, It's quite hard to setup exactly same environment as mine, so please allow for providing code similar to my condition.
Here is the code.
```
import importlib
import multiprocessing as mp


def test():
    print("import start")
    importlib.import_module("yapf.yapflib.yapf_api")
    print("import end")

def main():
    spawn_mp = mp.get_context("spawn")

    p = spawn_mp.Process(target=test)
    p.start()
    p.join()

if __name__ == "__main__":
    main()

```

**Comment by Spitfire1900** [comment]
Unable to reproduce

```python
kyle@mainstay:~/Repos$ pipx run --no-cache yapf <<EOF 
import importlib
import multiprocessing as mp


def test():
    print("import start")
    importlib.import_module("yapf.yapflib.yapf_api")
    print("import end")

def main():
    spawn_mp = mp.get_context("spawn")

    p = spawn_mp.Process(target=test)
    p.start()
    p.join()

if __name__ == "__main__":
    main()
EOF
⚠️  yapf is already on your PATH and installed at /home/kyle/.local/bin/yapf. Downloading and running anyway.
import importlib
import multiprocessing as mp


def test():
    print("import start")
    importlib.import_module("yapf.yapflib.yapf_api")
    print("import end")


def main():
    spawn_mp = mp.get_context("spawn")

    p = spawn_mp.Process(target=test)
    p.start()
    p.join()


if __name__ == "__main__":
    main()
kyle@mainstay:~/Repos$ 

```
