### ISSUE TITLE
yapf support in VSCode deprecated

### ISSUE THREAD

**Issue by KorbinianP** [google/yapf#1124]
Hey,

when using yapf in Visual Studio Code I get this message in my config.json
`"python.formatting.provider": "yapf",`
> This setting will soon be deprecated. Please use the Autopep8 extension or the Black Formatter extension. Learn more here: https://aka.ms/AAlgvkb.

The mentioned website tells me that yapf support is soon deprecated and a separate extension would be required. I can't find such an extension, do you plan to provide it?

Cheers

PS: Maybe this is redundant to #861

**Comment by EeyoreLee** [comment]
made a simple preview version can be searched by `yapf` keyword. Can anyone tell me how do you use it or what functions do you need ?

**Comment by EeyoreLee** [comment]
[Here](https://github.com/EeyoreLee/vscode-extension-yapf) is a release for vscode yapf extension can be searched via `yapf` keyword in vscode extension and microsoft marketplace. Support formatting in file or modification mode on save.

**Comment by SafiJ** [comment]
does it support google style formatting?

**Comment by EeyoreLee** [comment]
@SafiJ - Yup, it's just a vscode extension which will call yapf you install, so it support almost thing this google/yapf support. The usage is same in following
```
YAPF will search for the formatting style in the following manner:

Specified on the command line
In the [style] section of a .style.yapf file in either the current directory or one of its parent directories.
In the [yapf] section of a setup.cfg file in either the current directory or one of its parent directories.
In the [tool.yapf] section of a pyproject.toml file in either the current directory or one of its parent directories.
In the [style] section of a ~/.config/yapf/style file in your home directory.
If none of those files are found, the default style PEP8 is used.
```
And it can also support `--style` or others args in vscode settings.

**Comment by Spitfire1900** [comment]
@EeyoreLee . I love that you've made this. Many thanks :+1:

**Comment by bwendling** [comment]
@EeyoreLee would you mind updating the README.md to include a link to the VSCode extension, please? :-)

**Comment by bwendling** [comment]
Ah! Never mind, @Spitfire1900 is taking care of it. (https://github.com/google/yapf/pull/1130)

**Comment by Spitfire1900** [comment]
What are thoughts on a new docs page, "EDITOR SUPPORT.md" for recommended integration instructions for VSCode, IntelliJ/PyCharm, NeoVIM, IPython, etc.?

**Comment by Spitfire1900** [comment]
#1130 can be used as a reference for projects that want to use YAPF & VSCode. But was really intended to help bootstrap development on YAPF itself.

**Comment by EeyoreLee** [comment]
If you plan to add this markdown, I'd be willing to help add the vscode part.

**Comment by Spitfire1900** [comment]
Draft pull request https://github.com/google/yapf/pull/1135 opened to document YAPF integration with popular IDEs.

**Comment by KorbinianP** [comment]
I would close the issue as there is now a VSCode extension. Not by google but by @EeyoreLee
