### ISSUE TITLE
Yapf is not found as a formatter in vscode

### ISSUE THREAD

**Issue by andrybicio** [google/yapf#1125]
I installed yapf in my virtual environment (Windows 11 + WSL2 with Ubuntu 20.04.6 LTS) using
```{bash}
pip install yapf
```
and it runs smoothly.

According to docs I read online, I needed to add in the `settings.json` file for the workspace the line:
```[json]
{
  "python.formatting.provider": "yapf"
}
```
Note that whenever I try to modify the value of such a key, "yapf" is actually suggested as one of the options.

![image](https://github.com/google/yapf/assets/56033694/e5a7e397-6e2b-4542-80b8-b35e4e8c712f)

However, when running the command to format the document, it prompts that the default value for the formatter is `black`, but the latter cannot be found since I have uninstalled it.
![image](https://github.com/google/yapf/assets/56033694/b6f097b8-5bd3-4b4e-9303-24c6574e6cba)

 I am suggested, then, to choose another one for my Workspace, and I would like it to be `yapf`, but it is not shown in the options I have.

![image](https://github.com/google/yapf/assets/56033694/f2ee4aaa-fa24-4bdb-81a9-14e4d491233e)

Note that running in the shell, with the virtual environment activated that is the same one of the Python interpreter selected, yapf formats the file like a charm.

Any hints on how to make VSCode find yapf?

**Comment by unlsycn** [comment]
The option "python.formatting.provider" is provided by Python extension as it calls yapf for formatting hence you should select "Python" as your formatter.
BTW, yapf support by Python extension is going to be deprecated, Seeing #1124 .

**Comment by andrybicio** [comment]
That means are they planning to release a vscode extension for it? It seems to work and select the correct formatter, though. Thank you!

**Comment by Spitfire1900** [comment]
https://marketplace.visualstudio.com/items?itemName=eeyore.yapf

**Comment by Spitfire1900** [comment]
@bwendling this may be closed as resolved by  https://marketplace.visualstudio.com/items?itemName=eeyore.yapf and #1135
