### ISSUE TITLE
Please release v0.40.2 because off-main Git tag v0.40.1 is hidden from users of pre-commit autoupdate

### ISSUE THREAD

**Issue by hartwork** [google/yapf#1146]
Hi!

yapf Git tag `v0.40.1` is not an ancestor of `main` in Git history and that is why `pre-commit autoupdate` keeps downgrading yapf from v0.40.1 to v0.40.0 according to https://github.com/pre-commit/pre-commit/issues/3010#issuecomment-1729887654 e.g. see https://github.com/git-big-picture/git-big-picture/pull/357 for the end user effect. This affects up to 10 projects of mine:

```console
# grep /yapf */.pre-commit-config.yaml | wc -l
10
```

Any chance you could make a new release with a Git tag off `main` this time?

Thanks in advance!

CC @bwendling

**Comment by Spitfire1900** [comment]
This looks resolved.
![image](https://github.com/google/yapf/assets/6462596/0eff3fd6-0178-43d0-a283-9bd4c2ec75c4)

**Comment by hartwork** [comment]
@Spitfire1900 perfect, thanks to you and and @bwendling :pray:
