### ISSUE TITLE
Auto-discover and format `.pyi` files.

### ISSUE THREAD

**Issue by elenakrittik** [google/yapf#1151]
`.pyi` files (used primarily in type stubs) are also valid Python files, therefore it would be great if yapf would discover and format them automatically (like it currently does with `.py` files).

**Comment by Toppole6** [comment]
``

**Comment by hartwork** [comment]
From a quick look, maybe this is the only place that needs patching…

https://github.com/google/yapf/blob/3d4986ee86be97f7b26bb737743ffbda2cc18c27/yapf/yapflib/file_resources.py#L253-L258

…and maybe an additional test.

**Comment by bwendling** [comment]
Okay, but I think it should be done via a flag of some sort. Maybe a knob where you can specify the file extensions you'd like formatted?

**Comment by bwendling** [comment]
If the only time there'd be a `.pyi` file is for type stubs, then I suppose not.

**Comment by hartwork** [comment]
@bwendling cool! :+1:

**Comment by elenakrittik** [comment]
Thank you!
