### ISSUE TITLE
Version 0.33.0 is incorrectly marked as supporting Python2.7

### ISSUE THREAD

**Issue by Spitfire1900** [google/yapf#1154]
Not sure what the fix is here, but I realized today that version 0.33.0 does not support python2.7 but was inadvertently uploaded to PyPi as such. The last version that supported python2.7 was 0.32.0 and a fresh installation attempt of yapf when using python2.7 should not resolve to any newer version.

```
kyle@mainstay:~/Repos/yapf$ pip2.7 install yapf
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting yapf
  Using cached yapf-0.33.0-py2.py3-none-any.whl (200 kB)
ERROR: Could not find a version that satisfies the requirement tomli>=2.0.1 (from yapf) (from versions: none)
ERROR: No matching distribution found for tomli>=2.0.1 (from yapf)
```

**Comment by Spitfire1900** [comment]
Maybe yank 0.33.0 and replace with a `0.33.0-post1`? `0.40.0` should be consider for yanking also if we go that far.

**Comment by Spitfire1900** [comment]
@bwendling , thoughts here?

**Comment by bwendling** [comment]
I'm not sure what's the best course of action. If we want to replace it, then we should go with `0.33.1` or something, since we'll have to adjust the supported versions information in the source. I'm half-tempted to just remove it period and tell everyone that `0.32.0` is the last Python 2.7 version... I'm not sure how badly that's going to affect people.

**Comment by Spitfire1900** [comment]
Replacing it with 0.33.1 as a py3 only release will still cause 0.33.0 to be incorrectly resolved as the "final" py2 release.

My understanding is that "yanked" is just metadata, so that yapf>=0.32.0 will resolve to 0.32.0 on py2.

I would suspect that pinned 0.33.0 in peoples' requirements.txt and lock files would still install 0.33.0 even if it is yanked.

Need someone whose actually worked with yanking and/or testing on Test PyPi as part of this.

**Comment by Spitfire1900** [comment]
https://peps.python.org/pep-0592/

**Comment by Spitfire1900** [comment]
To clarify, my suggestion does not involve deleting the release from PYPI but to mark the release as yanked.

**Comment by Spitfire1900** [comment]
https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/amp/

**Comment by bwendling** [comment]
SGTM. I went ahead and marked them as "yanked".

**Comment by Spitfire1900** [comment]
@bwendling I've confirmed that 0.32.0 is now the latest version that resolves.

```
kyle@mainstay:~/Repos/yapf$ python2.7 -m pip install yapf
Collecting yapf
  Using cached yapf-0.32.0-py2.py3-none-any.whl (190 kB)
Installing collected packages: yapf
Successfully installed yapf-0.32.0
kyle@mainstay:~/Repos/yapf$ 
```

**Comment by bwendling** [comment]
Thank you for the fixes!
