### ISSUE TITLE
[Question]: Why removing the verify module, how can this be substituted ?

### ISSUE THREAD

**Issue by tianlianghai** [google/yapf#1155]
A imcompatible problem which utilize the verify parameter lead me to this.

**Comment by bwendling** [comment]
The 'verify' module was used only for internal testing (I believe the flag was hidden). And it wasn't very robust. For instance, there were several constructs that it simply couldn't handle.

**Comment by hartwork** [comment]
For the record, the related commit is 6bc6de17f4da1e8fd04aad36b02b1252076387ef and and it was first included in release 0.40.2 of 2023-09-22.

Should this question issue remain open or can it be closed as answered?

**Comment by bwendling** [comment]
I'll close it. We would need a much better "verification" strategy if we want to bring it back in some form.
