### ISSUE TITLE
May I ask how to automatically add a space after "#" when using yapf? I haven't found such configuration. Thank you.

### ISSUE THREAD

**Issue by jiayouzl** [google/yapf#1174]
**May I ask how to automatically add a space after "#" when using yapf? I haven't found such configuration. Thank you.**

<img width="1624" alt="image" src="https://github.com/google/yapf/assets/7685337/91d2db5c-492b-4402-a47a-d8f2c5b84774">

**Comment by bwendling** [comment]
YAPF doesn't mess with the token stream in this way. So all comments are kept "as is" without us trying to reformat them. This is to keep us from messing up some specialized comment formats, like "`#. <translation>`" for translation efforts.

**Comment by kamahen** [comment]
Some editors / IDEs have this. (On Emacs, I have something bound to the tab key that auto-formats same-line comments: `indent-for-tab-command`)
