### ISSUE TITLE
New release YAPF v0.40.3 needed

### ISSUE THREAD

**Issue by hartwork** [google/yapf#1248]
Hi! 👋 

All my YAPF pre-commit CIs keeps failing "randomly" because of bug #1164 / #1204, e.g. …

- October 18th at https://github.com/hartwork/wnpp.debian.net/actions/runs/11408926229/attempts/1
- October 14th at https://github.com/hartwork/xiangqi-setup/actions/runs/11327762194/attempts/1
- October 12th at https://github.com/hartwork/grub2-theme-preview/actions/runs/11306759475/attempts/1
- October 11th at https://github.com/hartwork/jawanndenn/actions/runs/11294766309/attempts/1
- October 11th at https://github.com/hartwork/git-delete-merged-branches/actions/runs/11283103256/attempts/1
- October 3rd at https://github.com/hartwork/binary-gentoo/actions/runs/11160259332/job/31020362745
- September 30th at https://github.com/hartwork/xiangqi-setup/actions/runs/11106301031/attempts/1
- September 2nd at https://github.com/hartwork/git-delete-merged-branches/actions/runs/10672007565/attempts/1
- …

My own pull request #1243 with a fix was merged _but_ the fix won't get to any users or setups without a release. 

I'm the first to help with a release if any help is needed — my e-mail contact is in my profile and I can do voice calls in English or German as needed, too. 

Please make a new release please please so I can finally stop cleaning up manually after failed CI runs caused by YAPF. Thank you! 🙏 

Best, Sebastian

**Comment by hartwork** [comment]
@bwendling do you have a few minutes?

**Comment by avalanche-pwn** [comment]
I second this.

Due to cybersecurity at my company we can't pull directly from git and are forced to use the version from PyPI.

I can also help if there's any need.

**Comment by hartwork** [comment]
@bwendling do you have a minute?

**Comment by hartwork** [comment]
@bwendling do you have a minute?

**Comment by bwendling** [comment]
Hey. Sorry about not responding. I've had less and less time to deal with YAPF these days. I'll create a new release.

**Comment by hartwork** [comment]
@bwendling that would be great 👍

**Comment by bwendling** [comment]
v0.43.0 released now. :)

**Comment by hartwork** [comment]
@bwendling thank you very much! 🙏
