### ISSUE TITLE
Yapf creates space "Immediately before the open parenthesis that starts the argument list of a function call"

### ISSUE THREAD

**Issue by alexjurkiewicz** [google/yapf#137]
pep8 says:

    h2. Whitespace in Expressions and Statements
    h3. Pet Peeves
    Avoid extraneous whitespace in the following situations:
    [...]
    Immediately before the open parenthesis that starts the argument list of a function call:
        Yes: spam(1)
        No:  spam (1)

Yapf 0.1.8 seems to do the no case, you can see with `echo 'del(foo)' | yapf`

**Comment by gwelymernans** [comment]
The `del` operator takes an expression list (`exprlist`) and isn't considered a function call. In fact, `pep8` doesn't tag `del (foo)` as a violation.

**Comment by alexjurkiewicz** [comment]
I see what you mean. In that case could yapf normalise more variations of
operator usage? Bracketising the first example below would (I think) help
make code more consistent:

    assert foo, "fail"
    assert(foo, "fail")
    assert (foo, "fail")

**Comment by gwelymernans** [comment]
That way lies dragons! :-)

Seriously, though, YAPF doesn't add parentheses or backslash-newlines to code. In the case of `assert`, it would cause more problems than it's worth. Basically, there would be people who want them and then people who don't. So if we add them, we would need to turn them off by default. Then if the option is on, should we add them only if the line goes over the column limit? or always? Etc.

**Comment by alexjurkiewicz** [comment]
Fair enough, thanks for the explanation :)
