### ISSUE TITLE
backslash continuations confuse yapf

### ISSUE THREAD

**Issue by alexjurkiewicz** [google/yapf#138]
I think the following definitions should simplify to the same code:

    def tile_is_traversable(self, x, y):
        return (a) and any([b for c in d if e])

    def tile_is_traversable(self, x, y):
        return (a) \
            and any([b
                for c
                in d
                if e])

However, they don't, and the second one gets very ugly (and over 80chars):

    def tile_is_traversable(self, x, y):
        return (a) and any([b for c in d if e])

    def tile_is_traversable(self, x, y):
        return (a) \
            and any([b
                                      for c
                                      in d
                                      if e])

**Comment by gwelymernans** [comment]
Yeah. This is a dup of #94.
