### ISSUE TITLE
PEP8 style recommends two spaces before comment, yapf does one.

### ISSUE THREAD

**Issue by ssbr** [google/yapf#14]
From an email from Terry Reedy:

> [...] style.py has
>
>>  # The number of spaces required before a trailing comment.
>>  SPACES_BEFORE_COMMENT=1,
>
 >PEP8 actually says "Inline comments should be separated by at least two spaces from the statement.", which is what you have in the google style.

**Comment by gwelymernans** [comment]
Fixed in 205d641.
