### ISSUE TITLE
Slicing numpy arrays

### ISSUE THREAD

**Issue by ggventurini** [google/yapf#141]
Hi!

First of all, thanks for making great piece of code available.

I think I found a bug: `yapf` (0.1.8), run without any option except `-d`, tries to fix this:

```python
A[0, :] = 0
A[:, 0] = 1
```
with this:
```diff
-A[0, :] = 0
+A[0,:] = 0
A[:, 0] = 1
```

I believe either both lines should be fixed or none of them should. For all it's worth, I find the original code more readable.

Cheers,

**Comment by gwelymernans** [comment]
I find it more readable too. :-) I'm not able to reproduce this, though.

```
$ yapf /tmp/bad.py
A[0, :] = 0
A[:, 0] = 1
```

(This is with 0.1.8.) Is it still occurring for you?

**Comment by ggventurini** [comment]
Hi!

Thanks for your reply. 

This issue is very strange, I can reproduce it easily and I have v 1.8.0 installed.

I had made more complex examples from the original piece of code I was working on, but turns out I can reproduce this issue with the same code as you have in your `/tmp/bad.py` file above.

Check this out:

```
➜  work git:(master) ✗ yapf --version
yapf 0.1.8
➜  ahkab git:(master) ✗ yapf -d yapf_test2.py        
--- yapf_test2.py        (original)
+++ yapf_test2.py       (reformatted)
@@ -1,2 +1,2 @@
-A[0, :] = 0
+A[0,:] = 0
 A[:, 0] = 1
➜  work git:(master) ✗ yapf yapf_test2.py 
A[0,:] = 0
A[:, 0] = 1
➜  work git:(master) ✗ cat yapf_test2.py 
A[0, :] = 0
A[:, 0] = 1
```

My Python version is 2.7.9 x86_64 as installed by anaconda on OS X. I can't try it out on Py3 because anaconda has 3.3.5 as highest version, for the time being.

**Comment by hayd** [comment]
You can do a py34 env with conda http://conda.pydata.org/docs/intro.html#creating-python-3-4-or-python-2-6-environments.

Did you install yapf with pip? I will try an reproduce on OSX later (I also use conda).

**Comment by gwelymernans** [comment]
Hmm...My python is 2.7.5 and 3.4.3. When I look at the code, we actually specify that a space is required between a `,` and `:`. Is there some type of strange encoding system you have or something? (Kind of grasping at straws now...)

**Comment by ggventurini** [comment]
I think my encoding is rather standard:

```
➜  work git:(master) ✗ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

Thanks for taking time to investigate this. If you need more info, just ask away.

**Comment by gwelymernans** [comment]
I just noticed that the separation of `,` and `:` was recent. I uploaded v0.1.9 with that fix. Could you give it a shot?

**Comment by ggventurini** [comment]
That fixed it!

```
➜  work git:(master) ✗ yapf yapf_test2.py 
A[0, :] = 0
A[:, 0] = 1
➜  work git:(master) ✗ yapf -d yapf_test2.py
➜  work git:(master) ✗ yapf --version
yapf 0.1.9
```

The file is exactly the same as before and now the space is preserved.

Thank you!

**Comment by gwelymernans** [comment]
Great! :-)
