### ISSUE TITLE
error in string splice

### ISSUE THREAD

**Issue by jason-kane** [google/yapf#143]
My pardon if this is a dupe, I did look at the open issues but didn't see anything that seemed relevant.

with a current pull of yapf (eafa1f) this:
```python
beta = "123"

test = {
    'alpha': beta[-1]
}

print beta[-1]
```

becomes:
```python
beta = "123"

test = {'alpha': beta[ - 1]}

print beta[-1]
```

If there is a comment (like this) yapf doesn't change anything:
```python
beta = "123"

test = {
    # comment
    'alpha': beta[-1]
}

print beta[-1]
```

My expectation would be that a string index like [-1] would never have whitespace added.

**Comment by gwelymernans** [comment]
Ew...yes, it shouldn't be adding spaces like that. Let me see what I can do.
