### ISSUE TITLE
Restricting lines doesn't always work

### ISSUE THREAD

**Issue by vrana** [google/yapf#147]
With some source codes, all lines are reformatted, not just the specified ones:

> echo -e "a=1\nb=2\n" | pyformat --yapf --lines=2-2

Expected:

```py
a=1
b = 2
```

Actual:

```py
a = 1
b = 2
```

Some source codes work as expected:

> echo -e "a( 1)\nb( 2)" | pyformat --yapf --lines=2-2

Expected = actual:

```py
a( 1)
b(2)
```

**Comment by gwelymernans** [comment]
Fixed now.
