### ISSUE TITLE
Plugin sections Wiki and project (yapf/plugins/) are out of sync

### ISSUE THREAD

**Issue by Ecno92** [google/yapf#151]
Currently there are two places where you can find more info about using yapf in your editor as a plugin:

* The wiki: https://github.com/google/yapf/wiki/Editor-Plugins
* The plugin folder in the project: https://github.com/google/yapf/tree/master/plugins

It seems like the plugin wiki page is older and out of date since the Emacs plugin link does not work anymore.
My proposal is to get rid of the Wiki page and to include the link to the sublime plugin in `yapf/plugins/README.rst`

I will open a PR for the Sublime Text plugin link, but one of the project maintainers needs to remove the wiki page since I can't find how to include this in a PR.

**Comment by gwelymernans** [comment]
Good idea. Done! :-)
