### ISSUE TITLE
Lines with only white spaces.

### ISSUE THREAD

**Issue by kierun** [google/yapf#153]
Here is a simple piece of code. If I run `yapf -i --style=pep8` on it, nothing happens. However, there is a line in the doc string that contains only white spaces.  PyLint complains about it with a trailing-whitespace. `pep8` complains with "W293 blank line contains whitespace".

I would have expected yapf to remove all the white spaces on that line.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys


def main():
    """A silly example.
    
    ^ Oh look a white space!
    """
    return 0


if __name__ == "__main__":
    sys.exit(main())

# EOF```

**Comment by hayd** [comment]
Yapf doesn't modify multi-line strings at all. Theoretically this could change the behaviour of your program... it's unclear whether this should be something yapf does.

I like to use [docformattter](https://github.com/myint/docformatter) for this.

**Comment by kierun** [comment]
[Docformatter](https://github.com/myint/docformatter) does the job for me!  Thank you.

**Comment by joshburkart** [comment]
Should we consider allowing calling `docformatter` from `yapf`? I'd love to have `docformatter` run automatically, and it's a little annoying to configure two formatters in an IDE. Formatting docstrings seems like a reasonable thing for  `yapf` to be able to do...

**Comment by joshburkart** [comment]
Err this is in #279
