### ISSUE TITLE
--lines doesn't only touch the specified lines

### ISSUE THREAD

**Issue by sbc100** [google/yapf#154]
It seems that --lines doesn't limit the modifications to the specified lines.

Specifically it seems to do indentation on the entire file.

For example, take this file with 8 space indents.
```
def foo():                                                                       
        a=1                                                                      
                                                                                 
def bar():                                                                       
        b=1  
```

If I try to yapf on just line 2 it seems to operator mostly on line 2 but also corrects indentation on line 5:
```
$ yapf  test.py --lines 2-2
[(2, 2)]
def foo():
    a = 1

def bar():
    b=1
```

Is this indented behavior?

BTW, I'm trying to add yapf support for 'git cl format' and the default way this works is that it should only touch the lines that are in the diff:
https://codereview.chromium.org/1156743008/

**Comment by hayd** [comment]
See also #66.

FWIW [pep8radius](https://github.com/hayd/pep8radius) does this (yapf/autopep8 the lines from the diff), although extracting the lines changes could surely be more elegant.

Having written quite a bit of the code to do this indentation stuff for autopep8, it's *really* very tricky to get the indentation within indentation thing right... Although I suppose this is easier as yapf has access to the ast... but still it's gonna be fiddly.

**Comment by sbc100** [comment]
Oh yeah.. is is basically a dup of #66, right?

**Comment by hayd** [comment]
This issue could be changed to something like "indentation is modified globally", as I think this is purely about indentation. IMO this should probably be the one open, as this is more specific than the original issue- for which the example code was actually fixed.

(Aside: Mixed indentation is an abomination and should be killed with fire immediately.)
