### ISSUE TITLE
yapf freezes on windows

### ISSUE THREAD

**Issue by shelper** [google/yapf#159]
I just installed YAPF on windows Python 3.4.2, via pip and try to run it on a file `foo.py` by simply put:
`yapf foo.py`, the file is as simple as one line code ` x = y+z ` and i found it freezes my computer, and never finish, 
but when i import yapf and uses the function FileFormat() it worked. I believe there is some bug, maybe windows specific, in the code？

**Comment by shelper** [comment]
i found the fix here 
https://github.com/Laharah/yapf/commit/3e7937268a7142f669cbd4d8e9789d2621bb4452

dont know why the author didnt file a pull request but hopefully this can be fixed in the next release

**Comment by gwelymernans** [comment]
Sorry for the delay in getting to this. I applied a patch similar to @Laharah's patch. Please try it out!
