### ISSUE TITLE
yapf will line break right before the closing bracket of a tuple

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#16]
This is somewhat of an aesthetic preference, so obviously feel free to close this as notabugwontfix, but the following code:

    def aaaaaaaaaaa(*args):
        pass

    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = aaaaaaaaaaa(
        ("...", "."), "..",
        ".............................................."
    )

is reformatted as

    def aaaaaaaaaaa(*args):
        pass

    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = aaaaaaaaaaa(("...", "."
        ), "..", "..............................................")

Having the tuple argument split over the line like that with the closing bracket on the next line looks really bad. Note that putting the closing bracket on the same line as the opening bracket would not even come close to the 80 character column limit.

**Comment by DRMacIver** [comment]
Confirmed in master.

**Comment by gwelymernans** [comment]
Yeah, this is not desirable. There should be a greater affinity for not splitting before the closing paren if we didn't split after the opening paren.
