### ISSUE TITLE
Lengthy 'if not' conditional causes E901 SyntaxError

### ISSUE THREAD

**Issue by affablebloke** [google/yapf#167]
After running YAPF on a large codebase, I discovered that lengthy 'if not' conditionals were causing E901 SyntaxErrors. However, this could be mitigated by modifying the code after the **or** to be wrapped with parentheses.

Example:

```python
def test():
    if not "Foooooooooooooooooooooooooooooo" or "Foooooooooooooooooooooooooooooo" == "Foooooooooooooooooooooooooooooo":
        pass

```
Reformatted using YAPF:
```python
def test():
    if not
    "Foooooooooooooooooooooooooooooo" or "Foooooooooooooooooooooooooooooo" == "Foooooooooooooooooooooooooooooo":
        pass
```

Modifying *unwrapped_line._SplitPenalty()* seems to fix the issue and the tests still pass.

From [_SplitPenalty line 392](https://github.com/google/yapf/blob/b8645eab86deff45dee4163d3a0db3da50470a03/yapf/yapflib/unwrapped_line.py#L392https://github.com/google/yapf/blob/b8645eab86deff45dee4163d3a0db3da50470a03/yapf/yapflib/unwrapped_line.py#L392-393):
```python
if prev_token.value == 'not':
    return split_penalty.STRONGLY_CONNECTED
```
To:
```python
if prev_token.value == 'not':
    return split_penalty.UNBREAKABLE
```

**Comment by gwelymernans** [comment]
Nice catch! Thanks for the suggested fix. :-)

**Comment by affablebloke** [comment]
:+1:
