### ISSUE TITLE
Splitting on [ is ugly

### ISSUE THREAD

**Issue by alexjurkiewicz** [google/yapf#169]
Input:

    status = cf.describe_stacks(StackName=stackname)[u'Stacks'][0][u'StackStatus']

Output:

    status = cf.describe_stacks(StackName=stackname)[u'Stacks'][0][
        u'StackStatus'
    ]

This is a pretty ugly change. Is there something smarter that could be done here? I don't think backslash continuation is much better:

    status = cf.describe_stacks(StackName=stackname)[u'Stacks'][0]\
        [u'StackStatus']

Maybe the ] could not be on a dedicated line?

**Comment by gwelymernans** [comment]
Putting the `]` on the same line as the content of the index is probably the best we can do here...

**Comment by alexjurkiewicz** [comment]
:+1:
