### ISSUE TITLE
yapf --style=pep8 puts wrong number of spaces before inline comment

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#17]
https://www.python.org/dev/peps/pep-0008/#inline-comments states "Inline comments should be separated by at least two spaces from the statement"

Yapf in pep8 style mode appears to put inline comments one space after the end. e.g. the following is both a result and fixed point of yapf --style=pep8:

    def bar(x): # inline comment
        pass

**Comment by eliben** [comment]
This was fixed yesterday in https://github.com/google/yapf/commit/205d641cf4e40ef3da482c5e24e5f35915871dea

Could you please re-check with an up-to-date YAPF that your issues are still relevant, and close those that are not?

**Comment by DRMacIver** [comment]
Will do. I'm pretty sure all the later ones are, but I'll recheck. Sorry about that!
