### ISSUE TITLE
unexpected spaces around keyword / parameter equals

### ISSUE THREAD

**Issue by sfermigier** [google/yapf#174]
Here are a few lines extracted from a real life project, and run through yapf with standard settings:

~~~python
sources = {
    'json': request.get_json(silent = True) or {},
    'json2': request.get_json(silent=True),
}
json = request.get_json(silent=True) or {}
~~~

As you can see, in one case (but not the others), extra spaces are added around the '=' sign (line 2).

`pep8` rightfully reports:

~~~
toto.py:2:36: E251 unexpected spaces around keyword / parameter equals
toto.py:2:38: E251 unexpected spaces around keyword / parameter equals
~~~

**Comment by gwelymernans** [comment]
Poop! I hope this fixes it for good now.
