### ISSUE TITLE
trailing comments cause wrong split

### ISSUE THREAD

**Issue by kain88-de** [google/yapf#177]
Trailing comments can cause yapf to split some lines so that the file is not valid python-code anymore.

[if-statement formating](https://github.com/MDAnalysis/mdanalysis/pull/393/files#diff-f6bcd0989a32586cc1db4d653eb66562L3808)
``` diff
- elif not f[a1] and f[a2]:  # If a1 isn't in a fragment, add it to a2's
+            elif not
+            f[a1] and f[a2]:  # If a1 isn't in a fragment, add it to a2's
```

In other cases it just causes annoying line splits

[function variable formatting](https://github.com/MDAnalysis/mdanalysis/pull/393/files#diff-f6bcd0989a32586cc1db4d653eb66562L3802)
```diff
-        f = dict.fromkeys(self.atoms, None)  # each atom starts with its own list
+        f = dict.fromkeys(self.atoms,
+                          None)  # each atom starts with its own list
```

I used the standard settings for this.

**Comment by gwelymernans** [comment]
I think this has been fixed along the way.
