### ISSUE TITLE
When run in 'range' mode, yapf reformats lines outside of the given range

### ISSUE THREAD

**Issue by nickhutchinson** [google/yapf#180]
Yapf appears to not entirely respect the range of lines passed to it via the `-l`/`--lines` option. While it seems to avoid doing major reformatting of lines outside of this range, it still applies some whitespace reformatting.

This is undesirable when you regularly work on files with mixed-width indentation. For example, when invoked with `yapf -l 10-18` yapf reformats the following ghastly code:

```python
def horrible():
  oh_god()
  why_would_you()
  [
     'do',

      'that',
  ]

def still_horrible():
    oh_god()
    why_would_you()
    [
        'do',

        'that',
    ]
```

... to this:

```python
def horrible():
    oh_god()
    why_would_you()
    [       'do',
        'that',
    ]

def still_horrible():
    oh_god()
    why_would_you()
    ['do', 'that', ]
```

I think yapf should have left `horrible()` alone.

Tested with yapf 0.2.5, Python 2.7.10.

**Comment by gwelymernans** [comment]
Yeah, this is ++ungood. I'll see what I can do.
