### ISSUE TITLE
Function call parameters being over indented in pep8 style when in conditional with and/or

### ISSUE THREAD

**Issue by JuhaniImberg** [google/yapf#181]
echo '
    if x or z.y(a, c,
                aaaaaaaaaaaaaaaaaaaaa=aaaaaaaaaaaaaaaaaa,
                bbbbbbbbbbbbbbbbbbbbb=bbbbbbbbbbbbbbbbbb):
        pass
    ' | yapf --style pep8        
    if x or z.y(a,
                    c,
                    aaaaaaaaaaaaaaaaaaaaa=aaaaaaaaaaaaaaaaaa,
                    bbbbbbbbbbbbbbbbbbbbb=bbbbbbbbbbbbbbbbbb):
        pass

Basically the reason for pr #170 is still happening

    yapf --version
    yapf 0.2.6

**Comment by ambv** [comment]
This provides a minor regression for when dedenting closing brackets is used. The following is unnecessary since the closing bracket distinguishes indentation in an PEP8-conformant manner:
```
             if not self.reckless and (
-                self.monitor.counters['db.running'] != 1 or
-                self.monitor.counters['db.in_multimysqldconf'] != 1
+                    self.monitor.counters['db.running'] != 1 or
+                    self.monitor.counters['db.in_multimysqldconf'] != 1
             ):
                 should_die = True
```

Are closing brackets ever dedented without DEDENT_CLOSING_BRACKETS after be974d80?

**Comment by gwelymernans** [comment]
I think you're right. I fixed this here:

To https://github.com/google/yapf.git
   0946c0f..43bdc7b  master -> master

**Comment by ambv** [comment]
Wow, you're fast, man. Kudos and thanks!
