### ISSUE TITLE
yapf not support PEP-0492

### ISSUE THREAD

**Issue by ipfans** [google/yapf#182]
PEP-0492 add ```async``` and ```await``` to keyword.

```python
➜  ~  yapf --style pep8 ~/Desktop/3.5_asyncio_async.py
import asyncio
import time

async

def slow_operation(n):
    await asyncio.sleep(1)
    # print("Slow operation {} complete".format(n))

    async

def main():
    start = time.time()
    await asyncio.wait([slow_operation(i) for i in range(10000)])
    end = time.time()
    print('Complete in {} second(s)'.format(end - start))


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
➜  ~  yapf --style google ~/Desktop/3.5_asyncio_async.py
import asyncio
import time

async

def slow_operation(n):
    await asyncio.sleep(1)
    # print("Slow operation {} complete".format(n))

    async

def main():
    start = time.time()
    await asyncio.wait([slow_operation(i) for i in range(10000)])
    end = time.time()
    print('Complete in {} second(s)'.format(end - start))


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by gwelymernans** [comment]
I'm not familiar with the keywords. What's the desired formatting for them?

**Comment by myint** [comment]
An example [here](https://www.python.org/dev/peps/pep-0492/#working-example). It is available in Python 3.5.

**Comment by gwelymernans** [comment]
Ah! Got it. The parser that we use is lib2to3's parser, so if it doesn't support the new syntax than we can't. (We would LOVE to change the parser, but it's not easy working with "ast"...) Do you know if there's any plan to update lib2to3 to support the new syntax?

**Comment by myint** [comment]
I think it might be parsing it okay. Though, I'm not sure since I haven't started using Python 3.5 regularly yet.

`foo.py`:
```python
async def foo():
    pass
```

```
$ ./3.5/bin/python -m lib2to3 foo.py
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No files need to be modified.
```

If I run the same thing with Python 3.4, I get a parse error.

**Comment by gwelymernans** [comment]
I downloaded 3.5.0a1, and it doesn't have `async` in the grammar just yet. It might be very new indeed.

**Comment by eliben** [comment]
a1 would be a fairly early version, it won't necessarily have this implemented. In general, we should be able to support it in the Python version it's released in (probably 3.5 final). Since Python 3.5 has not been released yet and `async` is new in 3.5, this is certainly not a super high-priority request feature :)

**Comment by ipfans** [comment]
As [PEP-0478](https://www.python.org/dev/peps/pep-0478/) 3.5.0 final will release at September 13, 2015. ```async def foo(): await``` can use 3.5.0b4 and newer version :) This feature is not high-priority, and still thanks for your works.

**Comment by ntcong** [comment]
3.5 was released, is there any plan to support async and await in yapf now ?

**Comment by gwelymernans** [comment]
Sorry for not responding earlier. Yes, we want to support 3.5. It will probably happen sometime after Thanksgiving weekend, though.

**Comment by catch22** [comment]
Any updates on this?

**Comment by gwelymernans** [comment]
Not as of yet. It's been a busy month...

**Comment by sdunster** [comment]
This appears to be in lib2to3 from what I can tell: https://hg.python.org/cpython/rev/eeeb666a53657ccbaf850f2debb2e916f730d101

What do I need to do to get this working in yapf?

**Comment by sdunster** [comment]
So I ran this with Python 3.5 and found that it recognises the syntax (when run with 3.4 it threw syntax exceptions), but it doesn't understand how to format `async def` or `await` and so it kinda screwed that up as expected. I'll try and find some time to figure out what needs to change but if you could point me in the right direction that would be much appreciated.

**Comment by gwelymernans** [comment]
I think this works now. Please check and let me know.

**Comment by ipfans** [comment]
Thx for your works.

But I have a small question:

```
➜  ~ /Users/user/.pyenv/versions/3.5.1/bin/yapf --style=pep8 -d Desktop/test.py
--- Desktop/test.py	(original)
+++ Desktop/test.py	(reformatted)
@@ -1,11 +1,9 @@
 import asyncio
 import time
-

 async def slow_operation():
     await asyncio.sleep(1)
     # print("Slow operation {} complete".format(n))
-

 async def main():
     start = time.time()
```

As ```pep-8```, top-level function and class definitions should surround with two blank lines.

**Comment by gwelymernans** [comment]
Ah yes. Good catch. Let me do a thing and get that fixed.
