### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by donnex** [google/yapf#183]
Is there any Chanelog for this project or is it still a bit to early for one?

I'm just a user of Yapf and it would be interesting to get a summary of what's new or changed when new versions show up.

**Comment by gwelymernans** [comment]
I haven't thought to add a change log. I can start one though. I think we're at a point now where it's mostly working as needed. :-)

**Comment by donnex** [comment]
That would be much appreciated! As a user it's much easier to check the chanelog instead of reading a bunch of commits :P

**Comment by gwelymernans** [comment]
I added one. :-)

**Comment by pquentin** [comment]
@gwelymernans: It looks like @donnex wanted something better than a "a bunch of commits" as he said. See http://keepachangelog.com/: "Don’t let your friends dump git logs into CHANGELOGs™".

It's certainly more work, though. Oh, and thanks for yapf!

**Comment by donnex** [comment]
Yeah that would be ideal, but a changelog with all commits is a step in the right direction :) Better than reading through all commits on the repo and try to guess what's changed or new.

Thanks for yapf ineed!

**Comment by gwelymernans** [comment]
Ah! I was going off of the GCC model. :-) I'll revamp them and make them more useful.

And I'm glad you guys are finding YAPF useful! :-)

**Comment by gwelymernans** [comment]
I think we have something that covers your request here. Please check out `CHANGELOG` and let me know what you think.

**Comment by donnex** [comment]
Looks really nice, short summary of what actually changed without having to check out every commit :)

Thanks a lot!
