### ISSUE TITLE
Fails to break line with a long function name

### ISSUE THREAD

**Issue by mtlynch** [google/yapf#189]
I noticed that YAPF breaks lines weirdly when the function name causes the line to overflow:
```
$ more longname.py 
def foo():
  foobarb_variable_with_kind_of_a_long_name = function_with_a_pretty_long_name()
```

**Current**:
```
$ yapf longname.py
def foo():
    foobarb_variable_with_kind_of_a_long_name = function_with_a_pretty_long_name(
    )
```
Note that the long line is 81 characters long.

**Desired**:
```
$ yapf longname.py
def foo():
    foobarb_variable_with_kind_of_a_long_name = (
        function_with_a_pretty_long_name())
```

**Comment by gwelymernans** [comment]
Unfortunately, YAPF refuses to add parentheses to code it's formatting. Basically, "Here Be Dragons". Also, the formatting algorithm doesn't lend itself to adding parentheses on a conditional basis.
