### ISSUE TITLE
Feature: Look for config in setup.cfg

### ISSUE THREAD

**Issue by sfermigier** [google/yapf#192]
If would be nice if yapf could look up the config in the setup.cfg file at the root of the project being worked on (just as pep8, pylama and other similar tools do)..

**Comment by gwelymernans** [comment]
I'm not sure I understand what the change should be. Do you have an example of what the `setup.cfg` file would look like?

**Comment by sfermigier** [comment]
Like this:
```
[yapf]
based_on_style = pep8
spaces_before_comment = 4
split_before_logical_operator = true
```

**Comment by gwelymernans** [comment]
We actually have that in the `.style.yapf` file.

**Comment by sfermigier** [comment]
I know, my example is copy/pasted from your doc.

My point is: I don't like to have my projects root directories cluttered with a lot of config files for all the tools we're using, and an emerging common best practice, for Python specific tools, is to have all the various configs as sections in the setup.cfg file.

For instance, in one of my projects, I have sections for:

- Babel (i18n)
- Pytest
- Pep8
- Flake8
- Pylama
- isort
- Sphinx

See: <https://github.com/abilian/abilian-core/blob/master/setup.cfg>

**Comment by hayd** [comment]
It was in the original implementation #100, it changed in #108, see [these comment](https://github.com/google/yapf/pull/100#issuecomment-93610662). It may be my fault.

Note: yapf itself already has a setup.cfg for wheels!

**Comment by skorokithakis** [comment]
+1, this seems like a good idea.
