### ISSUE TITLE
Continuation line does not distinguish itself from next line for 'for' statements

### ISSUE THREAD

**Issue by azmd** [google/yapf#197]
While commit b5bb402 closed the pep8 warnings for if statements for me (thanks!), it seems that it still happens when reformatting for statements, e.g.

```python
    for connection in itertools.chain(branch.contact, branch.address, morestuff):
        dosomething(connection)
```
turns into

```python
    for connection in itertools.chain(
        branch.contact, branch.address, morestuff):
        dosomething(connection)
```
This triggers the pep8 warning `E125 continuation line with same indent as next logical line`

I'd expect 
```python
    for connection in itertools.chain(
        branch.contact, branch.address, morestuff):
            dosomething(connection)
```

**Comment by gwelymernans** [comment]
Hmm...The code I wrote to fix that was horrible, and didn't cover everything. Try it again with this patch. :-)

**Comment by azmd** [comment]
Works like a charm, thanks!

**Comment by gwelymernans** [comment]
:+1:
