### ISSUE TITLE
Allow global config.

### ISSUE THREAD

**Issue by skorokithakis** [google/yapf#200]
A global configuration file (e.g. `~/.config/yapf/style`) would be handy. The motivation is that I pretty much always use a line width of 100 and always want to dedent closing brackets. I don't want to be specifying these on the command line every time I run YAPF, I want a global configuration that will be the lowest priority, immediately before the built-in config.

So the order would go:
* Command-line style.
* `.style.yapf`
* `~/.config/yapf/style`
* Default options.

**Comment by gwelymernans** [comment]
I think the solution to #192 will work here. We now support using the `setup.cfg` file with a `[yapf]` section. It would basically be your third option here.

**Comment by skorokithakis** [comment]
Is that not a per-project file?

**Comment by gwelymernans** [comment]
I'm not sure what you mean by that. Basically, it acts similarly to `.style.yapf`. Here's how we check:

* Command line
* `.style.yapf`
* `setup.cfg` with a `[yapf]` section
* Default options

The check for `.style.yapf` and `setup.cfg` go from the current directory to the parent directories until it either finds one of those files or runs out of parent directories.

**Comment by skorokithakis** [comment]
I mean that I would like this config to be global, not per-project. If a `setup.cfg` or `.style.yapf` is not found in this directory or any of the parent directories, `yapf` should check the global config file to see if there are any options defined there. It basically inserts a step in your list above:

* Command line
* `.style.yapf`
* `setup.cfg` with a `[yapf]` section
* `~/.config/yapf/style.cfg`
* Default options

Does that make more sense?

**Comment by skorokithakis** [comment]
Thank you!

**Comment by gwelymernans** [comment]
No problem. :-)

**Comment by hayd** [comment]
why ~/.config/yapf/style and not say ~/.config/yapf.style  ?

Also IIRC ~/.config is system dependent so i think we ought to use:

    os.path.join(os.getenv('XDG_CONFIG_HOME') or os.path.expanduser('~/.config'), 'yapf', 'style')

**Comment by skorokithakis** [comment]
I'm leaning towards `yapf.style` or `yapf.cfg` as well, but I didn't know whether more files would need to be added later. If it's likely that yapf will always only need one file, then I agree with you, a `~/.config/yapf.cfg` would be best.

**Comment by gwelymernans** [comment]
I took a look at my current `~/.config` directory and `git` is a directory in there with the `ignore` file in it. I just went with that format for consistency. If there's not a convention, then I think we can get away with just `~/.config/yapf.cfg`.

Thoughts?

**Comment by skorokithakis** [comment]
+1

**Comment by gwelymernans** [comment]
I just looked up the docs for `XDG_CONFIG_HOME` and it says this:

> A user specific version of the configuration file may be created in `$XDG_CONFIG_HOME/subdir/filename`, taking into account the default value for `$XDG_CONFIG_HOME` if `$XDG_CONFIG_HOME` is not set.
