### ISSUE TITLE
trailing comma changes output for lists

### ISSUE THREAD

**Issue by alexjurkiewicz** [google/yapf#201]
This:

    LOG_DB_MAPPINGS = [
        ['v', 'version'],
        ['lv', 'lv'],
        ['name', 'player'],
        ['uid', 'uid'],
        ['race', 'race'],
    ]

Is a no-op for yapf. But if you remove the trailing comma, you get this:

    LOG_DB_MAPPINGS = [
        ['v', 'version'], ['lv', 'lv'], ['name', 'player'], ['uid',
                                                             'uid'], ['race',
                                                                      'race']
    ]

**Comment by gwelymernans** [comment]
That's semi-expected...When you add a trailing comma, it places each element on a different line. Otherwise, it tries to bin pack them.

Your example is being horribly formatted though. I'll see what I can do.

**Comment by alexjurkiewicz** [comment]
Do you mean it's an intentional feature giving a way to signal to yapf how
you want a list to be formatted? Isn't that a little baroque?

**Comment by gwelymernans** [comment]
Yes. But it's not completely baroque. It's done in other formatters, like `clang-format`.

**Comment by alexjurkiewicz** [comment]
Ah, fair enough!
