### ISSUE TITLE
Formating imports

### ISSUE THREAD

**Issue by noisy** [google/yapf#203]
Is there a way to format imports from:

    from a_very_long_or_indented_module_name_yada_yad import (long_argument_1,
                                                            long_argument_2,
                                                            long_argument_3)

to

    from a_very_long_or_indented_module_name_yada_yad import (
        long_argument_1,
        long_argument_2,
        long_argument_3
    )

?

**Comment by pquentin** [comment]
See [DEDENT_CLOSING_BRACKETS](https://github.com/google/yapf#knobs).

**Comment by noisy** [comment]
@pquentin I already using this, but this gives me only:

    from a_very_long_or_indented_module_name_yada_yad import (
        long_argument_1, long_argument_2, long_argument_3
    )

**Comment by pquentin** [comment]
Oh, you're right, they do not include imports. Sorry!

**Comment by gwelymernans** [comment]
Kind of. You would need to add a `,` at the end of the import list, and one of the elements of that list needs to go over 80 columns. So something like:

```
$ python -m yapf --style facebook /tmp/bad.py
from a_very_long_or_indented_module_name_yada_yad import (
    long_argument_1, long_argument_2, long_argument_3
)
from a_very_long_or_indented_module_name_yada_yada_yada_yada import (
    long_argument_1,
    long_argument_2,
    long_argument_3,
)
```

(Note, `--style=facebook` turns on the `DEDENT_CLOSING_BRACKETS` option.)
