### ISSUE TITLE
Space between modeline/shebang and module docstring

### ISSUE THREAD

**Issue by renstrom** [google/yapf#208]
Imagine this file:

``` python
#!/usr/bin/env python
# -*- coding: utf-8 name> -*-

"""Some module docstring."""


def foobar():
    pass
```

Running yapf on it produces this diff:

``` diff
--- yapf.py (original)
+++ yapf.py (reformatted)
@@ -1,6 +1,5 @@
 #!/usr/bin/env python
 # -*- coding: utf-8 name> -*-
-
 """Some module docstring."""

```

I would actually have expected yapf **not** to remove the blank line between the shebang/encoding and the module docstring (i.e. do nothing).

**Comment by Stealthii** [comment]
This should be a configurable option. Something along the lines of `BLANK_LINE_BEFORE_MODULE_DOCSTRING` (boolean). It's a limiting factor unfortunately that prevents adoption within my team.

**Comment by jedie** [comment]
PyPi package has currently no `BLANK_LINE_BEFORE_MODULE_DOCSTRING` :(

Hope next release coming soon ;)
