### ISSUE TITLE
Group imports by stdlib/third-party/application

### ISSUE THREAD

**Issue by renstrom** [google/yapf#209]
According to [PEP8](https://www.python.org/dev/peps/pep-0008/#imports) imports should be ordered as follows:

>Imports should be grouped in the following order:
>
>- standard library imports
>- related third party imports
>- local application/library specific imports
>
>You should put a blank line between each group of imports.

Not sure how feasible this is but https://github.com/timothycrosley/isort seems to make it work, I guess by maintaining a list of all stdlib modules.

**Comment by renstrom** [comment]
Out of scope?

**Comment by gwelymernans** [comment]
Oh...sorry, I should have explained. Yeah, it's a bit out of scope of the tool. I would accept patches that do it, but at the time I don't have any plans to support this.

**Comment by carlthome** [comment]
Hmm, too bad. I expected this to be included, at least when using `based_on_style = pep8` considering the imports grouping is mandated by that style.
