### ISSUE TITLE
yapf (facebook style) loves to make a two-step reformat of over-long line

### ISSUE THREAD

**Issue by daniel-pittman** [google/yapf#210]
YAPF loves to make two steps if run twice in fixing this:

    # last character is column 87 with our indent
    self.assertEqual(result.reason_not_added, "current preflight is still running")

becomes

    self.assertEqual(result.reason_not_added,
                     "current preflight is still running")

next run it becomes

    self.assertEqual(
        result.reason_not_added, "current preflight is still running"
    )

Now, I like the last option best, and it's what we want, but the fact we take consistently two steps to get there is a surprise.  I'm not sure why it prefers the intermediate form once, but it happens often enough to feel "routine".

**Comment by gwelymernans** [comment]
Just a sanity check, are you using the same command line arguments for both runs? I'm traveling right now but I'll check this when I land.

**Comment by daniel-pittman** [comment]
Yes, exactly the same arguments each time.  It's likely using a line range specification that covers those, because it's part of our lint infrastructure and targets what the current change targets, but beyond that it's literally identical.  (See also part of the lint infrastructure.)

**Comment by gwelymernans** [comment]
There seems to be done weirdness where if the code is on separate lines, then it formats it the FB way. Otherwise it formats it like the first result. I'll see what I can find out...

**Comment by gwelymernans** [comment]
@ambv Would you be able to help track this down?

**Comment by khornberg** [comment]
I get the same behavior on several code bases using identical commands.

**Comment by ppolewicz** [comment]
We have a similar problem with our CI. In our workflow we use a pre-commit script that is later verified by the CI - and the CI fails frequently since yapf 0.6.1 or so. Example:
```sql
$ python --version
Python 3.4.3
$ yapf --version
yapf 0.8.0
$ cat setup.cfg
[yapf]
based_on_style=facebook
COLUMN_LIMIT=100
SPACE_BETWEEN_ENDING_COMMA_AND_CLOSING_BRACKET=False
SPLIT_PENALTY_AFTER_OPENING_BRACKET=0

[nosetests]
verbosity=2

$ cat yapf.py
class Foo:
    class Bar:
        @classmethod
        def baz(cls, clues_list, effect, constraints, constraint_manager):
            if clues_lists:
               return cls.single_constraint_not(clues_lists, effect, constraints[0], constraint_manager)
$ yapf yapf.py > yapf2.py
$ cat yapf2.py 
class Foo:
    class Bar:
        @classmethod
        def baz(cls, clues_list, effect, constraints, constraint_manager):
            if clues_lists:
                return cls.single_constraint_not(clues_lists, effect, constraints[0],
                                                 constraint_manager)
$ yapf yapf2.py > yapf3.py
$ cat yapf3.py 
class Foo:
    class Bar:
        @classmethod
        def baz(cls, clues_list, effect, constraints, constraint_manager):
            if clues_lists:
                return cls.single_constraint_not(
                    clues_lists, effect, constraints[0], constraint_manager
                )
$ sha1sum yapf*
62681294b58319d1c76fa37a7c298d2027312818  yapf2.py
e2457002b367d09ae28c0c3a7e13bdbc9d83ee9f  yapf3.py
49e1b9ddb583ccbb70c262f9e90445f03c449a94  yapf.py
$ 
```
Can we somehow force yapf to re-evaluate a line until it stops changing it? My current idea is to wrap it in a shell script which will run yapf in a loop until it is really done...

**Comment by ppolewicz** [comment]
Further investigation shows that this problem is as old as the facebook style itself (940898780a1bec2003b20dc090f87992d5c95f88)

**Comment by ambv** [comment]
This problem is inherent to YAPF's rules that depend on the "current relative line location". After a single reformatting that relative location might change, in which case it will have different penalties assigned. I haven't got time to really work on this before, you're probably have to wait until PyCon for me to get to this during sprints.

**Comment by ppolewicz** [comment]
I will look into it further myself

**Comment by ppolewicz** [comment]
If I understand correctly, if the first pass produces a newline inside a (parenthesis) scope, a break just after `opening_paren` and just before `closing_paren` should be forced. Then the line should be reformatted again. This can happen many times in a situation like this:
```python
[[[[['very long string', 'very long string']]]]]
```
becomes
```python
[[[[['very long string',
  'very long string']]]]]
```
and then outer scope is forced to be pushed into separate lines
```python
[
  [[[['very long string', 'very long string']]]]
]
```
(...) eventually it will become this:
```python
[
  [
    [
      [
        [
          'very long string',
          'very long string'
        ]
      ]
    ]
  ]
]
```

Current code tries to enforce a line break in `_MustBreakBefore`, which is too early - at this point it is unknown whether there will be line breaks in the scope or not.

**Comment by gwelymernans** [comment]
I think you're right. What needs to happen is that when a newline is placed between two brackets, then we need to enforce a newline split after the opening bracket and before the closing bracket. The `.lineno` attribute isn't a good way to determine this, because it only tells us the line number of the original, un-formatted token. I'm not sure how best to achieve this...

**Comment by ppolewicz** [comment]
This is not enough. If a newline is placed between brackets and we enforce the split as you said, we might want to remove the original newline. Or not.

I think we need to reevaluate in a loop until finished.

As for the best way to achieve this in current architecture of the code, I am not sure either. I think the reformatter will need to set must_break and loop internally. Any hint on how to do it well would be appreciated.

**Comment by gwelymernans** [comment]
I think this should fix the issue.

The original code was using the "lineno" attribute, which isn't the correct way to determine if the argument list is going to be split. That can be done only by looking at the tokens themselves and seeing if they go beyond the column limit.

Please give it a try and let me know how it works (or if it doesn't).

**Comment by gwelymernans** [comment]
Also, reevaluating the formatting in a loop really doesn't work because of how the algorithm works. The way we control what the formatting result is is by assigning penalties.

**Comment by ppolewicz** [comment]
I confirm that it now works correctly for both my code and the example supplied by @daniel-pittman.

Please release to pypi.
