### ISSUE TITLE
Check formatting

### ISSUE THREAD

**Issue by nikolay** [google/yapf#211]
Is there a way to check if the source code already complies with YAPF formatting?

**Comment by gwelymernans** [comment]
You can use the `--verify` option to verify that it still compiles after it's been formatted. However, it may fail in some situations where the code actually does compile.

**Comment by ppolewicz** [comment]
@nikolay I'm not sure if this is what you mean, but you can check the exit code of yapf --diff like this:
```sh
#!/bin/bash -eu
if yapf --diff file.py >/dev/null; then
   echo "valid"
else
   echo "invalid"
fi

**Comment by nikolay** [comment]
@ppolewicz Thank you! Let me try that!
