### ISSUE TITLE
join up double-punctuation in multi-line function calls.

### ISSUE THREAD

**Issue by daniel-pittman** [google/yapf#215]
Occasionally it's necessary, or at least desirable, to pass a list comprehension to a function -- sometimes unavoidably when, for example, the target code requires a list rather than an iterable.  YAPF likes to format it as follows:

                    self.client.createJobs(
                        [
                            create_hg_jobs(hg) for hg in hostgroups
                        ]
                    ),

I should prefer it to format like this:

                    self.client.createJobs([
                        create_hg_jobs[hg] for hg in hostgroups
                    ]),

Which that places two punctuation on the same like - '(' and '[' - it saves two lines of vertical space, and one extra indentation depth, to format like this.

**Comment by gwelymernans** [comment]
This seems to be what happens right now:

```
python -m yapf --style pep8 < /tmp/x.py
def _():
    if True:
        if True:
            if True:
                self.client.createJobs([
                    create_hg_jobs(hg) for hg in hostgroups
                ]),
```
