### ISSUE TITLE
All arguments on same line after breaking at paren

### ISSUE THREAD

**Issue by ncknuna** [google/yapf#216]
If I have:

```python
a = a_really_long_function_name_with_some_arguments(argument1, argument2=argument3)
```

yapf wants to format it as either:

```python
value = a_really_long_function_name_with_some_arguments(
    argument1, 
    argument2=argument3)
```

or

```python
value = a_really_long_function_name_with_some_arguments(argument1, 
                                                        argument2=argument3)
```

However, I would like it to be formatted:
```python
value = a_really_long_function_name_with_some_arguments(
    argument1, argument2=argument3)
```

Which is less lines than the first option, and doesn't have all the leading whitespace in the second line of the second option (the space before argument2=argument3). More generally, I would like to be able to have the following heuristic:
1. If a function call can fit all on one line, fit it on that line
2. If it can't fit on one line, but can fit on two after breaking at the paren, format it that way (my example above)
3. If it can't fit on two after breaking at the paren, put each argument on its own line.

Is there a way to tune yapf to do this? If not, I would be more than happy to submit a patch if pointed in the right direction. I thought maybe I could do this with some combination of SPLIT_PENALTY_AFTER_OPENING_BRACKET and SPLIT_PENALTY_FOR_ADDED_LINE_SPLIT, but if that is possible, the tuning is very finicky. Perhaps we could add a tuning parameter to penalize leading whitespace?

**Comment by ncknuna** [comment]
I would also like some way of having the closing paren on the same line as the last arg in the first two cases, and on its own line (as in DEDENT_CLOSING_BRACKETS) in the third case. From reading the documentation, I would guess that DEDENT_CLOSING_BRACKETS would cause the closing paren to be on a new line in case 2, which wouldn't be great. If I should open a separate issue about this after this issue is resolved, just let me know and I can do that.

**Comment by gwelymernans** [comment]
I'm very sorry for getting to this so late. Things have been hectic and YAPF took a back seat for a while.

The main reason for YAPF's formatting here is that when you use a named argument it will place each argument on a separate line. It's not ideal for all situations, but it did solve some issues several people had where they didn't want named arguments to "flow". The idea is that flowing them is harder to read.

There is a knob you can tweak to stop if from doing this `SPLIT_BEFORE_NAMED_ASSIGNS`. If you would like a combination of splitting and not splitting based on some heuristic, you can look at the code around [this code](https://github.com/google/yapf/blob/master/yapf/yapflib/format_decision_state.py#L152). One option would be to determine if there are more than one named argument, in which case you would want to place them all on separate lines, but if there is only one you could "flow" the arguments. I'm okay with any sensible heuristic, but it might be best to create a knob for it. :-)

**Comment by ncknuna** [comment]
I'm finally getting around to addressing this and think I have a pretty decent solution and tests to demonstrate it. My main question now is where I should put the tests. I just want to be able to say "given these style arguments, when I put in this input, I expect this output", but it seems like there are tests like that scattered across the test modules.

**Comment by gwelymernans** [comment]
The majority of formatting tests are in `reformatting_test.py`.  The best thing to do would be to put it in there under its own class. That way you can set whatever parameters you want. :-)

**Comment by ncknuna** [comment]
Great, thanks. I'll try to get a PR out next weekend, but no promises :)

**Comment by gwelymernans** [comment]
So you should be able to control this with the `SPLIT_BEFORE_NAMED_ASSIGNS` knob:

```
python -m yapf --style '{based_on_style: pep8; SPLIT_BEFORE_NAMED_ASSIGNS: False}' < /tmp/x.py
if True:
    value = a_really_long_function_name_with_some_arguments(
        argument1, argument2=argument3)
```
