### ISSUE TITLE
yapf --style=pep8 produces "E126 continuation line over-indented for hanging indent"

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#22]
The following code:

    class NAryTreeStrategy():

        def produce_template(self, context, pv):
            if True:
                children = tuple((self.branch_key_strategy.draw_template(
                    context, pv.branch_key_parameter),
                    self.produce_template(context, pv))
                    for _ in range(10))
                return children

Is reformatted as:

    class NAryTreeStrategy():
        def produce_template(self, context, pv):
            if True:
                children = tuple((self.branch_key_strategy.draw_template(
                    context, pv.branch_key_parameter),
                                  self.produce_template(context, pv))
                                 for _ in range(10))
                return children

Which causes the pep8 checker to report "E126 continuation line over-indented for hanging indent"

**Comment by DRMacIver** [comment]
Confirmed in master.

**Comment by hayd** [comment]
autopep8 returns this (which looks much worse):

```
class NAryTreeStrategy():

    def produce_template(self, context, pv):
        if True:
            children = tuple((self.branch_key_strategy.draw_template(
                context, pv.branch_key_parameter),
                self.produce_template(context, pv))
                for _ in range(10))
            return children
```

Presumably we want something like (which I think also passes pep8):

```
class NAryTreeStrategy():

    def produce_template(self, context, pv):
        if True:
            children = tuple(
                (self.branch_key_strategy.draw_template(
                    context,
                    pv.branch_key_parameter),
                 self.produce_template(context, pv))
                for _ in range(10))
            return children
```
but still ew, tbh I'm not sure there's a syntax where this does not suck...

```
class NAryTreeStrategy():
    def produce_template(self, context, pv):
        if True:
            draw = self.branch_key_strategy.draw_template
            produce = self.produce_template
            key = pv.branch_key_parameter
            children = tuple((draw(context, key), produce(context, pv))
                             for _ in range(10))
            return children
```

**Comment by gwelymernans** [comment]
I'm not sure I agree with `pep8` about the `E126` error. `pylint` doesn't complain about it, and just from looking at the code, it's correctly aligning with matching elements.

I do agree with @hayd about how the alternative syntaxes suck, and that the refactoring he came up with is probably the best option for such code. (I realize that it's not always possible to do that, but still...)

**Comment by gwelymernans** [comment]
We're now generating this:

```
class NAryTreeStrategy():
    def produce_template(self, context, pv):
        if True:
            children = tuple(
                (self.branch_key_strategy.draw_template(
                    context, pv.branch_key_parameter),
                 self.produce_template(context, pv)) for _ in range(10))
            return children
```

It's marginally better. I hope that it holds up for other examples. if not, please file a new bug. :-)
