### ISSUE TITLE
join_multiple_lines=False still joins function calls

### ISSUE THREAD

**Issue by kmorrison** [google/yapf#222]
I have noticed irregularities with application on join_multiple_lines

```
self.thirty_char_word(
    first_arg,
    second_arg,
)
```

becomes 

```
self.thirty_char_word(first_arg, second_args, )
``` 

even with `join_multiple_lines=False`. I have looked at the code and my only guess is that maybe when parsed the line is implicitly joined, and so is not considered to be joining by the time the rule gets applied.

Please let me know if there are any more reproducing steps that you require.

**Comment by gwelymernans** [comment]
This is a misunderstanding of what that style option means. It's supposed to mean that the formatter will leave some multi-line statements as they are, such as short `if` statements:

```
if foo(bar, baz): continue
```

It's not going to leave things like function calls alone.
