### ISSUE TITLE
Infer indentation level when formatting from stdin

### ISSUE THREAD

**Issue by strokirk** [google/yapf#224]
While coding in vim, it's very useful to set yapf as the `equalprg`, which means that selected lines will be sent via `stdin` to yapf and replaced with it's output.

However, this means that if I want to format only a few lines in the middle of an indented block, yapf will fail with `IndentationError: unexpected indent`. For example, only sending the `bar = sorted( bar )` line to yapf in the following example.

```python
def foo():
    bar = ['c', 'd', 'a']

    bar = sorted( bar )

    return foo
```

It would be really useful if yapf could look at the first line of input to infer the common indent-level of all following lines.

**Comment by bolov** [comment]
+1

**Comment by gwelymernans** [comment]
Unfortunately, this isn't something we can control. The parser we use (`lib2to3`), isn't able to accept this. The best you can do here is use the `--lines` option when formatting in `vim`.

**Comment by purpleP** [comment]
@gwelymernans Well, you can try other parser (Jedi for example) or dedent lines before sending it to parser.

**Comment by gwelymernans** [comment]
@purpleP two things:

1. Dedenting the code may allow the line to go over the max column limit. If anyone wanted to go down this route, they would need to modify the max column limit amount during that formatting. If someone wanted to submit a pull request with this feature, I would consider it. :-) Then again, when the code is submitted via `stdin`, why not dedent it before, pass in the adjusted column limit, and then indent the result themselves?
2. Using a new parser, while it would have some benefits, would require a huge rewrite of the entire formatter, and then only to support one feature that has a workaround (that I mentioned above). The only way to achieve the same functionality as the Jedi parser would probably be to modify `lib2to3` to have it.

**Comment by purpleP** [comment]
@strokirk @bolov  Hi, I've added pull request to fix this behaviour. Until it's merged you can use my fork if you want.

**Comment by purpleP** [comment]
@gwelymernans Oh, I haven't thought about column limit. I will fix this in my pull request.

**Comment by purpleP** [comment]
@gwelymernans Okay, I've added the test and fixed it. By the way, you should consider using pytest instead of unittest, because it's really much better. After using it for about half year I wouldn't want to come back to unittest even if someone would pay me for that.
