### ISSUE TITLE
yapf does not wrap lines with lambdas correctly 

### ISSUE THREAD

**Issue by jamesbroadhead** [google/yapf#225]
cat yapfbad.py

$ yapf -i --style my.yapf yapfbad.py ; pylint --rcfile=pylintrc yapfbad.py | grep "Line too long"

    C:  9, 0: Line too long (104/100) (line-too-long)

$ cat yapfbad.py 

    class SomeClass(object):
        do_something = True

        def succeeded(self, dddddddddddddd):
            d = defer.succeed(None)

            if self.do_something:
                d.addCallback(
                    lambda _: self.aaaaaa.bbbbbbbbbbbbbbbb.cccccccccccccccccccccccccccccccc(dddddddddddddd))
            return d

(adding lambdas to a twisted callback chain like this is normal practise, as it allows avoiding the implicit passing of the result of the previous callback)

$ cat my.yapf 

    [style]
    based_on_style = pep8
    spaces_before_comment = 4
    column_limit = 100

$ cat pylintrc

    [FORMAT]
    max-line-length=100

Alternately, should I be weighting column_limit higher? I tried this already without success.

**Comment by gwelymernans** [comment]
YAPF does everything it can to place a lambda on a single line, because some style guides make multiple line lambdas a violation. What I can do is make a style knob so that people can relax this.

**Comment by jamesbroadhead** [comment]
thanks! 

For slightly more context, this cropped up when we were migrating onto yapf, with strict pylint line-length checking already enabled. Eventually, I saw the light & just disabled the strict line-length checking
("you've either got to fully trust your formatter, or not -- the middle ground, working around the conflicting foibles of two tools, is a horrible place to be")

**Comment by gwelymernans** [comment]
LOL! Indeed. :-) I'm sorry it took so long to get to this (work, life, and things). But I hope that it'll help in the future.
