### ISSUE TITLE
yapf injects unnecessary newlines between args in dict definition

### ISSUE THREAD

**Issue by jamesbroadhead** [google/yapf#231]
````
$ cat models.py 
from flask.ext.restful import fields

task_fields = {
    'a': fields.Boolean,
    's': fields.Boolean,
    't': fields.String,
    'uri': fields.Url('task', absolute=True),
    's2': fields.String,
}

$ cat style.yapf 
[style]
based_on_style = google
indent_width = 2
column_limit = 100

$ yapf --style=style.yapf -i -r models.py 
$ git diff
diff --git a/models.py b/models.py
index 26db8fd..b5e595d 100644
--- a/models.py
+++ b/models.py
@@ -4,6 +4,7 @@ task_fields = {
     'a': fields.Boolean,
     's': fields.Boolean,
     't': fields.String,
-    'uri': fields.Url('task', absolute=True),
+    'uri': fields.Url('task',
+                      absolute=True),
     's2': fields.String,
 }
````

(this one may be intentional based on the chosen based_on style)

**Comment by frol** [comment]
You can fix this by adding the `SPLIT_BEFORE_NAMED_ASSIGNS=False` line to your `style.yapf`.

**Comment by gwelymernans** [comment]
This fell off my plate. @frol is correct. What's happening is that YAPF is placing all arguments on separate lines if there are named arguments. It was a feature often asked for. There have been requests to relax this a bit for when the whole function can can be placed on a single line. I just haven't gotten around to doing that just yet.

In the meantime, `SPLIT_BEFORE_NAMED_ASSIGNS=False` is the best way to help out here. Thanks, @frol!

**Comment by jamesbroadhead** [comment]
I see -- thanks for the response. 

Is there an option to make the split-likelihood even higher in function/method arguments?
eg. to output something like
```
def foo(
    bar,
    baz,
    quux=False):
  pass
```
which some believe lead towards cleaner merges.
