### ISSUE TITLE
Style configuration values

### ISSUE THREAD

**Issue by b5y** [google/yapf#234]
I am using yapf to reformat code after manipulating with it. More detail, I am implementing python analyzer.

Could you please give me some example values for the following keys in the style dictionary (https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L45) ?:

1) I18N_FUNCTION_CALL
2) SPLIT_PENALTY_AFTER_UNARY_OPERATOR
3) SPLIT_PENALTY_EXCESS_CHARACTER
4) SPLIT_PENALTY_BITWISE_OPERATOR
5) SPLIT_PENALTY_IMPORT_NAMES
6) SPLIT_PENALTY_LOGICAL_OPERATOR
7) SPLIT_PENALTY_AFTER_OPENING_BRACKET
8) SPLIT_PENALTY_FOR_ADDED_LINE_SPLIT

Most of values on these keys are mysterious for me.

**Comment by gwelymernans** [comment]
If you look at [`CreatePEP3Style`](https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L146), it will give you values that coincide with the PEP8 style guide. The `I18N_FUNCTION_CALL` option is for internationalization code, and is really specific to a company's internal practices. So you can probably just ignore it in your code if you don't deal with internationalization.

**Comment by b5y** [comment]
I have seen [CreatePEP8Style](https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L146) and use it as one of the 4 default styles in yapf.
Accordingly, I am collecting data to give it to [CreateStyleFromConfig](https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L257) method and want to know exactly where and how to get these values. I am implementing python analyzer and using yapf in my project.

**Comment by gwelymernans** [comment]
Ah! I see. The values were gotten by trail-and-error. We adjusted one until we got the format that we liked and repeated for the rest of the style options...Sorry that it's not a better answer...

**Comment by b5y** [comment]
It's okay. Thank you!
