### ISSUE TITLE
SPLIT_BEFORE_BITWISE_OPERATOR incorrectly(?) set to True in PEP8 style

### ISSUE THREAD

**Issue by meatbody** [google/yapf#237]
The only line I can find in PEP8 dealing with splitting around operators is "The preferred place to break around a binary operator is after the operator, not before it." (https://www.python.org/dev/peps/pep-0008/#maximum-line-length)

I don't see any other lines in PEP8 that deal specifically with bitwise operators, and since &, | and ^ are all themselves binary operators, I think this should be set to False in the default PEP8 style.

**Comment by gwelymernans** [comment]
Good catch! fixed.
