### ISSUE TITLE
yapf is not stable: running yapf -i on a file several times in a row keeps changing the file

### ISSUE THREAD

**Issue by yannack** [google/yapf#239]
I have a pathogical example below of the symptom I am describing (this is on the current master branch). 

There are cases where running yapf -i will yield a given output A, running it again on that output will yield a new output B, running it again will revert back to A, then B, then A, B, A, B...

To reproduce this issue, run:
`PYTHONPATH=yapf/ python yapf/yapf -i --style='{indent_width: 2, continuation_indent_width: 4, indent_dictionary_value: True}' /tmp/yapf/test.py`

Using the following `test.py` file:
```
class A(object):
  def method(self):
    filters = {
        'expressions': [
            {'field': {
                'search_field':
                    {'user_field': 'latest_party__number_of_guests'},
            }}
        ]
    }
```

And notice how the lines:

```
                 'search_field':
                     {'user_field': 'latest_party__number_of_guests'},
```

keep getting exchanged with:

```
                 'search_field': {'user_field': 'latest_party__number_of_guests'
                                  },
```

**Comment by gwelymernans** [comment]
Oof...that's gross. There are a few other situations where it's not as stable as it should be. I'll look into it.

**Comment by gwelymernans** [comment]
Please let me know if this crops up again...
