### ISSUE TITLE
yapf --style=pep8 sometimes inserts a blank line it shouldn't

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#24]
This code is pep8 correct, because timeout is a *local* function definition and thus has only one blank line in front of it:

    import signal

    try:
        signal.SIGALRM
        # ..................................................................
        # ...............................................................

        def timeout(seconds=1):
            pass
    except:
        pass

However yapf reformats it as:

    import signal

    try:
        signal.SIGALRM

        # ..................................................................
        # ...............................................................

        def timeout(seconds=1):
            pass
    except:
        pass

With two blank lines before timeout.

pep8 checker says "E303 too many blank lines (2)"

**Comment by DRMacIver** [comment]
Confirmed in master.

**Comment by eliben** [comment]
I'm not sure what's the right way to go here. PEP8 says "Separate top-level function and class definitions with two blank lines. " 

Is ``timeout`` not a "top-level function" here just because it's inside a ``try`` block? I'd say it still is, since it's not nested in any other function or class.

**Comment by DRMacIver** [comment]
I agree it's arguable. My argument in favour of it going this way is simply that this is what the pep8 checker says and basically all the existing tooling is designed around compatibility and consistency with that, so unless there's a really good reason to go the other way I think consistency is a strong net good.

**Comment by eliben** [comment]
We do not hold the ``pep8`` checker as "the source of truth", FWIW. The only source of truth is https://www.python.org/dev/peps/pep-0008/, and it leaves some things loosely defined on purpose.

That said, we'll look into this. Thanks for the report, as always

**Comment by DRMacIver** [comment]
I'm not really putting it forth as a source of truth. I'm saying that given that all the existing editor integration, linting, etc. is built on it, a code formatter that doesn't produce source code that complies to its whims is going to be really annoying to use because it's not compatible with anything else.

**Comment by gwelymernans** [comment]
As Eli mentioned, this is a grey area. When in doubt, we should add a knob of some sort so that people can have their cake and eat it too. While we don't take any one tool as the source of all truth, we also don't expect everyone to change just because we say so. :-)

**Comment by gwelymernans** [comment]
FWIW, our pylint agrees with pep8 on this.
