### ISSUE TITLE
PEP-0942 formatting await in parens weirdly

### ISSUE THREAD

**Issue by sdunster** [google/yapf#240]
We're seeing yapf want to try and do this:

```
-                    if (await fut):
+                    if ( await fut):
```

And this:
```
-    with (await semaphore):
+    with ( await semaphore):
```

While this syntax should not really be used I think yapf needs to do a better job of dealing with it.

See #182

**Comment by sdunster** [comment]
Should be easy to repro but if you need more details lmk

**Comment by gwelymernans** [comment]
(Sorry for the delay in getting back to you.)

I'm not able to reproduce this. Is it a syntax used with a newer Python? Which version?

**Comment by leandrotoledo** [comment]
@gwelymernans this is Python 3.5+ implementation of [PEP 492](https://www.python.org/dev/peps/pep-0492/), I can reproduce the issue:

```
-    if (await get_links()):
+    if ( await get_links()):
```

**Comment by gwelymernans** [comment]
I still couldn't reproduce it, but please test this change and let me know if it works.

**Comment by leandrotoledo** [comment]
@gwelymernans, problem still persists.

Cookbook:
```
$ virtualenv -p python3.5 env

$ source env/bin/activate

$ python -V
Python 3.5.1

$ pip install https://github.com/google/yapf/archive/master.zip
```

```
$ cat mock.py
async def get_html():
    pass

async def main():
    if (await get_html()):
        pass
```

```
$ yapf mock.py 
async def get_html():
    pass


async def main():
    if ( await get_html()):
        pass
```

Hope it helps, let me know if you need further details!
Thanks!

**Comment by gwelymernans** [comment]
Ah! Now I can reproduce it. Thank you. :-) I think the latest fix should solve this for you...
