### ISSUE TITLE
tab indentation support

### ISSUE THREAD

**Issue by eskhool** [google/yapf#244]
It appears yapf forces space indentation? Surely there are some people out there who believe in pretty code (hell they use tabs for that reason only!). Is there something that I am missing or is this a bug/feature?

**Comment by gwelymernans** [comment]
It's a missing feature. :-) For those who believe in the superiority of tabs, they should have a knob to do that. It just hasn't been done yet, as it hasn't been asked for yet. Would you be interested in taking a stab at it?

**Comment by eskhool** [comment]
I believe I just might but wouldn't commit to a time frame just yet :-) ..lets keep this open for us to get more people to express support for this idea ...till then I anticipate the primary task will be to treat it as a special case of INDENT_WIDTH = 1 and use tabs instead of spaces for indentation (assuming that the code doesn't have mixed indentation by mistake which pep8 would point out and Python 3 would reject anyways)...I am not familiar with the clang-format's reformatting algorithm so thats what will probably make me spend some time.

**Comment by gwelymernans** [comment]
Sure, we can leave this open. :-) What I envision happening is that we have a `USE_TABS` knob that people can set. Then when `AddWhitespacePrefix` is called, it would use `\t` instead of `' '`. Shouldn't be too difficult, but it would be a good "intro to YAPF" project if you're interested in helping out. :-)

**Comment by dracony** [comment]
I guess this can be closed now
