### ISSUE TITLE
Extra drop indent within dict.

### ISSUE THREAD

**Issue by stephen-soltesz** [google/yapf#245]
Yapf will reformat the following:

        oids = {
            'octets': models.OID(rx='abc', tx='def'),
            'discards': models.OID(rx='ghi', tx='jkl')
        }

with extra drop indents within the function calls:

        oids = {
            'octets': models.OID(rx='abc',
                                 tx='def'),
            'discards': models.OID(rx='ghi',
                                   tx='jkl')
        }

Since the lines by themselves do not exceed 80-columns, and the format is not expected by most python readers, the drop indent may be unnecessary.

**Comment by gwelymernans** [comment]
Yeah. The reason for this is because when we have named arguments to a function, we place all arguments on separate lines. I need to relax this a bit it would seem...

**Comment by gwelymernans** [comment]
Actually...this may have been fixed. Could you try current ToT?
