### ISSUE TITLE
Add spaces around power operator

### ISSUE THREAD

**Issue by Chaoste** [google/yapf#247]
I found this code in yapf/yapflib/unwrapped_line.py :
```
if left.value == '**' or right.value == '**':
  # Don't add a space around the "power" operator.
  return False
```
But I would like to add spaces and it's not permitted by pep8 so it would be great if you could add this option to the style config.

Example:
`yapf_api.FormatCode("a ** b")` returns `('a**b\n', True)`.

**Comment by derkuci** [comment]
any opinion/plan for this?  I also like to have spaces around math power operator.

**Comment by Chaoste** [comment]
5 years later, I finally realize that this feature was implemented very quickly. Thanks a lot! 😄

**Comment by gwelymernans** [comment]
👍
