### ISSUE TITLE
Blank line after multiline string

### ISSUE THREAD

**Issue by Chaoste** [google/yapf#248]
If I have a multiline string which is longer than one line, yapf adds a blankline after this string. Is this pythonic way or a bug?

```
from yapf import yapf_api as yapf
yapf.FormatCode('query = """SELECT id \nFROM table \nWHERE day in {}"""\ndays = ",".join(days)')
```
Returns:
`('query = """SELECT id \nFROM table \nWHERE day in {}"""\n\ndays = ",".join(days)\n', False)`

Notice the two newlines before i define 'days'. This happens only if the multiline string includes newlines.
I couldn't found an option disabling this settings - maybe you can add this variable for me :)

**Comment by gwelymernans** [comment]
Oof...no. That shouldn't happen...Fixed.
