### ISSUE TITLE
Don't add newlines to dictionary

### ISSUE THREAD

**Issue by Chaoste** [google/yapf#249]
If i have a big array in a dictionary with many values I don't want yapf to add a newline after each argument.

Example:
`print(yapf.FormatCode("KEEP_IDS = {\n    'mock': [\n               1009065026905003213,       1009065026905003254,        1009065026953780747,       1009065026953780746,\n        1009065026905003257,\n        1009065026905003287,\n        1009065026905003286,\n        1009065026905003256,\n        1009065026905003255,\n        1009065026905003212,\n        1009065026953780729,\n        1009065026947694176,\n        1009065026947694177,\n        1009065026947694178,\n        1009065026947694179,\n        1009065026953780728,\n    ],\n    'empty': [],\n}", style_config="setup.cfg")[0])`

Returns:
```
KEEP_IDS = {
    'mock': [
        1009065026905003213,
        1009065026905003254,
        1009065026953780747,
        1009065026953780746,
        1009065026905003257,
        1009065026905003287,
        1009065026905003286,
        1009065026905003256,
        1009065026905003255,
        1009065026905003212,
        1009065026953780729,
        1009065026947694176,
        1009065026947694177,
        1009065026947694178,
        1009065026947694179,
        1009065026953780728,
    ],
    'empty': [],
}
```

Expected:
```
KEEP_IDS = {
    'mock': [
        1009065026905003213, 1009065026905003254, 1009065026953780747,
        1009065026953780746, 1009065026905003257, 1009065026905003287,
        ...
    ],
    'empty': [],
}
```

**Comment by gwelymernans** [comment]
You added a comma at the end of the list, which is a sign to yapf to place each item in a list on separate lines. If you remove it, you'll get this:

```
KEEP_IDS = {
    'mock': [
        1009065026905003213, 1009065026905003254, 1009065026953780747,
        1009065026953780746, 1009065026905003257, 1009065026905003287,
        1009065026905003286, 1009065026905003256, 1009065026905003255,
        1009065026905003212, 1009065026953780729, 1009065026947694176,
        1009065026947694177, 1009065026947694178, 1009065026947694179,
        1009065026953780728
    ],
    'empty': [],
}
```

In general, if you have hand-formatted data literals that you don't want yapf to touch, you need to disable formatting for them. E.g.,

```
KEEP_IDS = {
    'mock': [
        1009065026905003213, 1009065026905003254, 1009065026953780747,
        1009065026953780746, 1009065026905003257, 1009065026905003287,
        1009065026905003286, 1009065026905003256, 1009065026905003255,
        1009065026905003212, 1009065026953780729, 1009065026947694176,
        1009065026947694177, 1009065026947694178, 1009065026947694179,
        1009065026953780728
    ],
    'empty': [],
}  # yapf: disable
```
