### ISSUE TITLE
yapf does not strip blank lines from the end of a file

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#25]
I suppose this one is more of a feature request. pyformat will strip blank lines from the end of a file (pep8 checker reports the blank line at the end of the file as W391), but yapf will not, meaning a file that could easily be formatted into PEP8 compliance will not be.

**Comment by DRMacIver** [comment]
Confirmed in master.

**Comment by eliben** [comment]
I can't reproduce this with master (see added tests ^^^^^^). Can you please provide an example?

**Comment by DRMacIver** [comment]
I believe this was (accidentally?) fixed in c80d69ce2b55bedd6350bcb7cbc00f9662a6a6b7

**Comment by eliben** [comment]
@DRMacIver I agree. Fixed then.

**Comment by gwelymernans** [comment]
Oops! I didn't know about this PR when I added c80d69c. Thanks for adding a test!
