### ISSUE TITLE
yapf --style=pep8 produces E124  closing bracket does not match visual indentation

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#26]
Reformatting the following valid (but gross) code:

    def foo(x):
        return x

    def test_collapses_whitespace_nicely():
        foo(
            lambda x,       y:           1  # pragma: no cover
        )

Results in the following (better but invalid) code:

    def foo(x):
        return x

    def test_collapses_whitespace_nicely():
        foo(lambda x, y: 1 # pragma: no cover
           )

**Comment by DRMacIver** [comment]
Confirmed in master.

**Comment by gwelymernans** [comment]
Interesting. Our version of pylint doesn't agree with PEP 8 on this. If I move the `)` to align with the `f` in `foo`, it complains that it shouldn't be that way.

**Comment by alexjurkiewicz** [comment]
I think you're aware (not sure if you're talking pep8 the linter or pep8 the spec), but it seems pylint and pep8 the linter don't agree. Here's another example of yapf output:

    TEST_LIST = ('foo', 'bar',  # first comment
                 'baz',  # second comment
                )

This raises pep8 linter E124 "closing bracket does not match visual indentation". If I add another space to the last line, you instead get pylint C0330 "wrong continued indentation"!

[The pep8 spec says the following](https://www.python.org/dev/peps/pep-0008/#indentation): *"The closing brace/bracket/parenthesis on multi-line constructs may either line up under the first non-whitespace character of the last line of list [example1] or it may be lined up under the first character of the line that starts the multi-line construct [example2]"*.

example1 shows this:

    my_list = [
        1, 2, 3,
        4, 5, 6,
        ]

example2 (not relevant to this discussion really, just included for completeness):

    my_list = [
        1, 2, 3,
        4, 5, 6,
    ]

It seems pylint & yapf are wrong, in this case. The pep8 linter error is correct.

**Comment by alexjurkiewicz** [comment]
I think the test testClosingBracketIndent in reformatter_test.py is wrong, it claims this is correct layout:

    while (xxxxxxxxxxxxxxxxxxxxx(yyyyyyyyyyyyy[zzzzz]) == 'aaaaaaaaaaa' and
           xxxxxxxxxxxxxxxxxxxxx(yyyyyyyyyyyyy[zzzzz].aaaaaaaa[0]) == 'bbbbbbb'
          ):

**Comment by gwelymernans** [comment]
@alexjurkiewicz It seems like this is a conflict between Google's version and PEP 8. I'll need to add a knob to control this...

**Comment by gwelymernans** [comment]
I added 9439278. Let's see if that fixes this for you.

**Comment by alexjurkiewicz** [comment]
Beaut! Thanks @gwelymernans :+1:
