### ISSUE TITLE
Please normalize backslash continuations

### ISSUE THREAD

**Issue by bukzor** [google/yapf#275]
Input:

```
a = 1 + \
2
```

Desired output:

```
a = 1 + 2
```

In actuality, yapf avoids rewriting any continuation with a backslash escape.

**Comment by ricardolsmendes** [comment]
+1

YAPF does not normalize the following code:
decoded = '{}...'.format(encoded[:max_length - 3].decode(encoding, 'ignore')) \
            if len(encoded) > max_length \
            else encoded.decode(encoding, 'ignore')

If I manually remove the backslashes and put the whole code in one line, then run YAPF, it works:
decoded = '{}...'.format(encoded[:max_length - 3].decode(
            encoding,
            'ignore')) if len(encoded) > max_length else encoded.decode(
                encoding, 'ignore')

I would like YAPF to do it automatically.

**Comment by gwelymernans** [comment]
This is intentional. When YAPF encounters a backslash, it assumes that the programmer intended the code to be exactly that way. It could be nicer with indentations, but it's our policy not to remove any tokens from the program to reduce the chances of introducing subtle bugs.

**Comment by ricardolsmendes** [comment]
Ok, @gwelymernans , thanks for clarifying.
