### ISSUE TITLE
Yapf doesn't get odd indent width

### ISSUE THREAD

**Issue by b5y** [google/yapf#280]
Hi!

Say, I want to set this indent:

```python
from yapf.yapflib.yapf_api import style, FormatFile


def my_own_style():
    my_style = style.CreatePEP8Style()
    my_style['INDENT_WIDTH'] = 3
    return my_style

# Lets format any file (with another indent) with this style:
formatted_code = FormatFile("any_file.py", 
                                style_config=style.SetGlobalStyle(my_own_style()), 
                                in_place=False)[0]
# And write it somewhere:
with open('resulted_insertion.py', 'w') as fd:
        fd.write(formatted_code)
````

You will not believe, but resulted file will be with 4 indent width instead of 3. The same is for 1 indent width and so on.
Please correct me if I am wrong.
If it is bug, I am ready to fix it.

**Comment by gwelymernans** [comment]
This does sound like a bug. If you'd like to attack it, please feel free. :-)

**Comment by b5y** [comment]
@gwelymernans That's great! Please assign this task to me. I will fix it on this week.

**Comment by gwelymernans** [comment]
It's not allowing me to assign it to you. I think you're not on the list or something. :-(

**Comment by b5y** [comment]
Okay. Got it

**Comment by b5y** [comment]
Another idea come to my mind during browsing yapf code. Why continuation indent must be the same as indent? 

For instance, in Python we could implement the following code (and it will be validated):

```
for x in range(10):
  for y in range(5): # <- 2 indents
     print x, y # <- 3 indents
```
