### ISSUE TITLE
empty line after method

### ISSUE THREAD

**Issue by retr0h** [google/yapf#287]
Is there a way to check for empty lines under methods?  I've not seen this in the documentation.  I have a codebase where this keeps sneaking in, and would like the formatter to account for it.

```
def foo():

  code....
```

vs

```
def foo()
  code....
```

**Comment by gwelymernans** [comment]
It's possible to check for this. My main concern is whether this is common enough to turn on by default. It could possibly be done as a style option knob.

**Comment by retr0h** [comment]
> It's possible to check for this. My main concern is whether this is common enough to turn on by default. It could possibly be done as a style option knob.

Right, I don't mind it being a knob.

**Comment by gwelymernans** [comment]
For clarification, do you want it to always have a blank line after the `def` line, or only when there's a blank line in the original code?

**Comment by retr0h** [comment]
I actually want to strip the blank lines after a def.  So I figured we would have a knob that would either strip or preserve the blank line.
