### ISSUE TITLE
'yapf --in-place' should keep eol style

### ISSUE THREAD

**Issue by wsw0108** [google/yapf#288]
under window10/py2.7.11, run `yapf --in-place file.py` change the eol to '\r\n'(it was '\n').

I think when do in-place formating, it should not touch the original eol style.

To archive this, there only a little change to 'yapflib/py3compat.py', like below:
```python
from functools import partial
open_with_encoding = partial(io.open, newline='')
```

**Comment by ppolewicz** [comment]
eol on Windows is `'\r\n'` though, isn't it? I think yapf should normalize the end of lines, in case my IDE happened to write it differently than in case of the other files in the project. So I think `yapf --in-place` should NOT keep the eol style - it should enforce the line ending as per policy of the project.

**Comment by gwelymernans** [comment]
I did a quick look at `clang-format` and they have a function to determine if `\r\n` should be used.

```c++
static bool inputUsesCRLF(StringRef Text) {
  return Text.count('\r') * 2 > Text.count('\n');
}
```

I think this would be a good compromise, and it should keep `yapf` from causing a whitespace change on every line when it replaces `\r\n` with `\n`.

**Comment by gwelymernans** [comment]
There seems to be a bit of a problem. The `\r` character doesn't seem to be supported by `lib2to3`...
