### ISSUE TITLE
code with `async def` fails with `--verify`

### ISSUE THREAD

**Issue by afg984** [google/yapf#293]
yapf cannot `--verify` this code
```
# async.py


async def foo():
    pass
```

Notes:
I found this issue with the [PyYapf](https://github.com/google/yapf/tree/v0.11.1/plugins#sublime-text) plugin for sublime text, which [uses ``--verify``](https://github.com/jason-kane/PyYapf/blob/v0.10.3/PyYapf.py#L151), which [seems not to be a public api](https://github.com/google/yapf/blob/v0.11.1/yapf/__init__.py#L115) though

Application output/ Traceback
```
yapf --verify async.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yapf/yapflib/verifier.py", line 43, in VerifyCode
    compile(textwrap.dedent(code).encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 4
    async def foo():
                   ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

(omitted)
```

additional information:

```
python --version
Python 3.5.2
yapf --version
yapf 0.11.0
yapf --version
yapf 0.11.1
```
Neither of 0.11.0, 0.11.1 work

**Comment by gwelymernans** [comment]
The `--verify` option is not meant for normal use, only when debugging `yapf` itself. Please don't use it. :-)

**Comment by afg984** [comment]
Thanks for the information, reporting to PyYapf.

**Comment by gwelymernans** [comment]
I created this pull request: https://github.com/jason-kane/PyYapf/pull/25

**Comment by afg984** [comment]
haha, thanks. was just about to submit it
