### ISSUE TITLE
FormatFile's verify kwarg should default to False

### ISSUE THREAD

**Issue by underyx** [google/yapf#297]
It looks like

- `FormatFile` is the public API for formatting files
- The verifier is an unmaintained, private library, for debugging purposes, see here: https://github.com/google/yapf/issues/293

In this case, it would save people a fair bit of headache (e.g. https://github.com/coala-analyzer/coala-bears/pull/748) if syntax verification was disabled by default.

**Comment by gwelymernans** [comment]
Odd...Not sure why that was still there. Fixed.

**Comment by underyx** [comment]
Awesome, thanks!
