### ISSUE TITLE
Function argument splitting differently, given default args

### ISSUE THREAD

**Issue by vasa-chi** [google/yapf#307]
Given:
```python
def long_function_name(var_one, var_two, var_three, var_four, var_five, var_six):
    print(var_one)
```
`yapf --style=pep8 -d longfunc.py` returns:
```patch
--- longfunc.py	(original)
+++ longfunc.py	(reformatted)
@@ -1,2 +1,3 @@
-def long_function_name(var_one, var_two, var_three, var_four, var_five, var_six):
+def long_function_name(var_one, var_two, var_three, var_four, var_five,
+                       var_six):
     print(var_one)
```

But when there is at least one default argument:
```python
def long_function_name(var_one, var_two, var_three, var_four, var_five, var_six=1):
    print(var_one)
```
`yapf --style=pep8 -d longfunc.py` returns:
```patch
--- longfunc.py	(original)
+++ longfunc.py	(reformatted)
@@ -1,2 +1,7 @@
-def long_function_name(var_one, var_two, var_three, var_four, var_five, var_six=1):
+def long_function_name(var_one,
+                       var_two,
+                       var_three,
+                       var_four,
+                       var_five,
+                       var_six=1):
     print(var_one)
```

Is this as intended? Is there currently any way to force argument splitting to always work as in the first example?

**Comment by jpupu** [comment]
Setting `SPLIT_BEFORE_NAMED_ASSIGNS=False` will format the second example similarly to the first:

```diff
--- foo.py	(original)
+++ foo.py	(reformatted)
@@ -1,5 +1,8 @@
-def long_function_name(var_one, var_two, var_three, var_four, var_five, var_six):
+def long_function_name(var_one, var_two, var_three, var_four, var_five,
+                       var_six):
     print(var_one)
 
-def long_function_name(var_one, var_two, var_three, var_four, var_five, var_six=1):
+
+def long_function_name(var_one, var_two, var_three, var_four, var_five,
+                       var_six=1):
     print(var_one)
```

**Comment by vasa-chi** [comment]
Thanks!

Although it feels like this should be set in pep8 style, no?

**Comment by jpupu** [comment]
Well, I don't really feel qualified to comment on that, but according to comments on #216 and #231 the splitting behaviour has been much requested. In cases where you have many named assigns it certainly is very nice.

**Comment by gwelymernans** [comment]
Yes, it's intentional. You should be able to turn it off by setting `SPLIT_BEFORE_NAMED_ASSIGNS` to `False` in your style options. Please give it a shot. :-)

**Comment by vasa-chi** [comment]
Oh, yes, sorry, `SPLIT_BEFORE_NAMED_ASSIGNS` knob does the job. 
I just kinda assumed that the output with `SPLIT_BEFORE_NAMED_ASSIGNS=False` was nearer to the style in [pep8](https://www.python.org/dev/peps/pep-0008/#indentation) doc. But they do not particularly cover named assigns, so I guess that is just my personal preference :)

Thank you very much for this awesome project!

**Comment by gwelymernans** [comment]
Thank you. :-)
