### ISSUE TITLE
A global style setup and usage bug via FormatCode, FormatFile[dev branch only]

### ISSUE THREAD

**Issue by rojaster** [google/yapf#308]
Short Description:
If you would like to set up default style globally, you're getting back `DEFAULT_STYLE_FACTORY` that was defined as Pep8 (this is the reason why Pep8 style works well) for all possible pre-defined styles(google, chromium and etc...)

Long Description:
I hack on one project that uses `yapf` and caught one interesting bug in last development version.

This function sets up a configuration of global style [SetGlobalStyle()](https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L39). 
It is being used by `FormatCode` ( `FormatFile` uses it implicitly via `FormatCode` call )

I found some tests that are using a global style's setting from the previous test or setting up own style:
1. https://github.com/google/yapf/blob/master/yapftests/yapf_test.py#L229
2. https://github.com/google/yapf/blob/master/yapftests/yapf_test.py#L238
3. https://github.com/google/yapf/blob/master/yapftests/yapf_test.py#L1130

In Format Code we have next string:
Check yapf_api.py - https://github.com/google/yapf/blob/master/yapf/yapflib/yapf_api.py#L120
```python
 style.SetGlobalStyle(style.CreateStyleFromConfig(style_config))
```
The `style_config` parameter defined like a `string` or `None`: https://github.com/google/yapf/blob/master/yapf/yapflib/yapf_api.py#L23 . 
It has three options:
1. pre-defined style by name: 'pep8', 'google' and etc
2. path to a file with style
3. None, use a DEFAULT_STYLE_FACTORY

And how it was ( https://github.com/google/yapf/blob/7e088293e4ea05bfd479258ae7748cd57e84a218/yapf/yapflib/style.py#L316 ):
```python
 if style_config is None:
    return DEFAULT_STYLE_FACTORY()
```

Ok, but in last changes we got this : 

Check: style.py - https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L320

```python

styles = (CreatePEP8Style(), CreateGoogleStyle(),
             CreateFacebookStyle(), CreateChromiumStyle())
  def_style = False
  if style_config is None:
    for style in styles:
      if _style == style:
        def_style = True
        break
    if not def_style:
        return _style
    return DEFAULT_STYLE_FACTORY()
  style_factory = _STYLE_NAME_TO_FACTORY.get(style_config.lower())
```

Check DEFAULT_STYLE_FACTORY: https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L419
```python
# The default style - used if yapf is not invoked without specifically
# requesting a formatting style.
DEFAULT_STYLE = 'pep8'
DEFAULT_STYLE_FACTORY = CreatePEP8Style
```

(test for this part has number [3](https://github.com/google/yapf/blob/master/yapftests/yapf_test.py#L1130)
This code, has next steps:
1. firstly, does check style_config is `None`, Ok, we got `None`(remember we set up style globally, it will `None` always, ) 
2. Is the globally defined style in the list of default styles?
  1. Nope, we've defined our own style and returned a _style that references to our style. (def_style = False)

in first look all is good but it does not:
```python
# what if I do something like this
 style.SetGlobalStyle(style.CreateChromiumStyle())
yapf_api.FormatCode(<input_unformatted_code_here>, style_config=None)

# or like in the given test

yapf_api.FormatCode(<input_unformatted_code_here>, style_config= style.SetGlobalStyle(style.CreateChromiumStyle()))
``` 
both calls are equivalent to each other, but we get a DEFAULT_STYLE_FACTORY back!!!
> (but first is much more readable and clear, because `setter` always returns `None` and It sets the global state, and we do not confuse a caller about the callee's arguments contract).

We get this because when we check `_style`(a global style) it assigns to def_style a True value and breaking out from the loop. The second condition would be ignored and DEFAULT_STYLE_FACTORY is being returned back as a result of a callee.

```python

# caller calls the method:
#yapf_api.FormatCode(<input_unformatted_code_here>, 
#                                    style_config= style.SetGlobalStyle(style.CreateChromiumStyle()))

styles = (CreatePEP8Style(), CreateGoogleStyle(),
             CreateFacebookStyle(), CreateChromiumStyle())
  def_style = False
  if style_config is None:   # style_config = None, but _style = CreateChromiumStyle()
    for style in styles:
      if _style == style: # ok we got this as the last element, it is really default style
        def_style = True 
        break # get out from the loop
    if not def_style: # def_style = True, but `not def_style` is a False
        return _style # skip this step, our condition gets false
    return DEFAULT_STYLE_FACTORY() # yeah, method returns DEFAULT_STYLE_FACTORY that's equal al CreatePEP8Style by default
  style_factory = _STYLE_NAME_TO_FACTORY.get(style_config.lower())
```

In General, this code raises some questions like:
* Have tests been relevant for the current piece of code?
* Why was KISS principle ignored? ( excerpt was copy-pasted from ipython console)
```python
In [3]:  styles = (style.CreatePEP8Style(), style.CreateGoogleStyle(),
             style.CreateFacebookStyle(), style.CreateChromiumStyle())

In [4]: style._style in styles
Out[4]: True

In [5]: if style._style in styles: print('true')
true

In [6]: style.SetGlobalStyle(style.CreateChromiumStyle())

In [7]: style._style == style.CreateChromiumStyle()
Out[7]: True

In [8]: style._style in styles
Out[8]: True

In [9]: if style._style in styles: print('true')
true

In [10]: 

```

I rewrote this part in my fork and changed the behavior and callee's contract.
if style_config equals `None` it returns a global style( _style). On start _style equals a DEFAULT_STYLE_FACTORY. After that, we must apply next convention that appears as a caller-callee contract: either use a style_config or use a global style(via SetGlobalStyle) and style_config keep `None`.

This approach has a positive and negative effects:
1. I implemented a global `getter` because we have a global `setter` by the module level.
2. A global `getter` is breaking an encapsulation of a global style, but it has broken already - you can change the global _style externally that is a global state change. And Yeah I've been reading [eliben's todo](https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L436) and I absolutely agree with that.

**Comment by b5y** [comment]
The whole "ceremony" with setting ```styles``` variable is about [this](https://github.com/google/yapf/blob/master/yapftests/yapf_test.py#L229) test. If you run it separately from all other tests, it passed. Even if you check this test (just ```u'+    pass'```) on debugger, it returns True. What is strange, is that ```self.assertTrue(u'+    pass' in diff)``` returns None during separately running. I am [working](https://github.com/google/yapf/pull/309) with this problem.

**Comment by rojaster** [comment]
@b5y I want a comment from the core team, not from the man who did this.

**Comment by b5y** [comment]
@rojaster my comment not only for you.

**Comment by rojaster** [comment]
@b5y, The test is broken, because it's used the style from the previous test, that's no a good solution, because in this case tester will wait that DEFAULT_STYLE_FACTORY is being returned by default (DEAFULT_STYLE_FACTORY assigned to PEP8 like in the previous usage in the test case )

**Comment by b5y** [comment]
@rojaster I know the problem. Just need time to fix this bug and add more tests.

**Comment by rojaster** [comment]
@b5y I have the solution already but I want to discuss it with a core team

**Comment by gwelymernans** [comment]
From what I can see, it looks like we should be returning `_style` here instead of `DEFAULT_STYLE_FACTORY()`. Does this seem correct?

```python
diff --git a/yapf/yapflib/style.py b/yapf/yapflib/style.py
index cebbc27..3ee6395 100644
--- a/yapf/yapflib/style.py
+++ b/yapf/yapflib/style.py
@@ -327,7 +327,7 @@ def CreateStyleFromConfig(style_config):
         break
     if not def_style:
         return _style
-    return DEFAULT_STYLE_FACTORY()
+    return _style
   style_factory = _STYLE_NAME_TO_FACTORY.get(style_config.lower())
   if style_factory is not None:
     return style_factory()
```

**Comment by rojaster** [comment]
@gwelymernans, yeah, we can return it directly  or give a `getter` for that. I think if we use a style via a variable with an underscore(_style) a `getter` method is a better choice and we don't have to use protected member of the module directly.

In my fork, I created `getter` and declared a public interface: `setter`(SetGlobalStyle) and `getter`(GetGlobalStyle). And if I change the way to work with a style internally it won't change my way to work externally. (pr#310)
That's good for my case, but maybe you have another vision of it.

**Comment by gwelymernans** [comment]
I added a potential fix. Let me know what you guys think.

**Comment by b5y** [comment]
@gwelymernans LGTM! Thanks for fixing this!

**Comment by rojaster** [comment]
@gwelymernans I commented your commit.
