### ISSUE TITLE
Version 0.12.0 tag

### ISSUE THREAD

**Issue by khornberg** [google/yapf#312]
I believe the 0.12.0 tag is incorrect

Master with version change - https://github.com/google/yapf/commit/95936ecc735f538488fe6c4f6d8e078bd0840f33
Tagged - https://github.com/google/yapf/commit/f0dd0a4cf25c1ebbb381f6e7ea1797ceefad7b25

**Comment by gwelymernans** [comment]
Gah! Thank you for catching that. It should be fixed now...
