### ISSUE TITLE
Regression: Ugly reformat of rested data structure

### ISSUE THREAD

**Issue by sfermigier** [google/yapf#313]
Here's a diff between some code formatted by yapf 0.12 and 0.12.1:

```
-    breadcrumbs = [{'name': 'Admin',
-                    'url': url_for(".home")},
-                   {'name': title},]
+    breadcrumbs = [{
+        'name': 'Admin',
+        'url': url_for(".home")
+    },
+                   {
+                       'name': title
+                   },]
```

I believe everyone would agree that, while the previous formatting was not ideally pleasing, the new oe is much worse.

**Comment by gwelymernans** [comment]
MY EYES! THEY BURN!!!

Okay, yeah, this sucks. I'll see what I can do.
