### ISSUE TITLE
Code outside `--lines` range is reformatted in some circumstances

### ISSUE THREAD

**Issue by chrisdiamand** [google/yapf#318]
Hi!

In the following example, running yapf on just the final line also adds a spurious extra blank line on line 2:

    import sys

    # Comment
    def some_func(x):
        x = ["badly" , "formatted","line" ]

[run `yapf test.py --lines=5-5`]

    import sys

    # Comment
    def some_func(x):
        x = ["badly", "formatted", "line"]

There are now two blank lines on lines 2 and 3, rather than the original one, even though those are outside the scope of the `--lines` argument. On larger examples, this happens to _any_ function in the file with a comment on the line before the `def` keyword.

**Comment by gwelymernans** [comment]
This is weird...It definitely shouldn't be doing this. I'll look into it.

**Comment by chrisdiamand** [comment]
Thanks!
