### ISSUE TITLE
Yaml files support

### ISSUE THREAD

**Issue by mikefaille** [google/yapf#323]
Please, support yaml files.
Since yapf support this dictionary representation `key: value`, Yaml files could be easy to implement.

**Comment by gwelymernans** [comment]
YAML has nothing to do with Python. Its syntax is completely different. I'm sorry, but that's beyond the scope of this project...

**Comment by mikefaille** [comment]
For sure. But, I search a good Yaml linter for emacs and I tried autopep8. (It work well !) So, if I don't find good Yaml linter as base for emacs then I will explore if we can adapt python linter. There is lots of rules we can wrap up between bot linters. Proof (maybe) autopep8 for python and yaml. 

I understand that we can prefer simplicity and just forking yapf for some behavior than taking risk to augment code complexity for out of initial scope feature (more thinking is required here).

**Comment by gwelymernans** [comment]
It's not so much that yapf might fail when formatting yaml (it might succeed for most of it), but it's not designed for yaml and I just don't want to "feature creep" yapf to where it has to support both Python and yaml. A new yaml-specific formatter might be the best option here. If you want to base it off of yapf (or autopep8), feel free to do that. :-)
