### ISSUE TITLE
Corruption since 0.11.0

### ISSUE THREAD

**Issue by ppolewicz** [google/yapf#327]
```
$ cat yapftest.py 
def foo():
    if 0:
        return False
        
    #a deadly comment
    elif 1:
        return True

print(foo())
$ cat yapftest.py | awk '{print $0 "$"}'
def foo():$
    if 0:$
        return False$
        $
    #a deadly comment$
    elif 1:$
        return True$
$
print(foo())$
$ yapf --version
yapf 0.13.1
$ python yapftest.py 
True
$ yapf yapftest.py > yapftest2.py 
$ python yapftest2.py 
  File "yapftest2.py", line 6
    1:
     ^
SyntaxError: invalid syntax
$ cat yapftest2.py 
def foo():
    if 0:
        return False

    #a deadly comment
    1:
    elif
        return True


print(foo())
$ cat setup.cfg 
[yapf]
based_on_style=facebook
COLUMN_LIMIT=100
SPACE_BETWEEN_ENDING_COMMA_AND_CLOSING_BRACKET=False
SPLIT_PENALTY_AFTER_OPENING_BRACKET=0
```

On 0.10.0 it works just fine.

**Comment by khamidou** [comment]
Hi! I'm reopening this issue because it looks like it was only partially fixed. Here's another failing test case:
```python
def f():
    if x == 2:
          return 2
          # a hanging comment
  
      # another line
    elif x == 3:
          return 3
  
    else:
          return 4
```

This is the output I get when running yapf `0.16.2`
```python
def f():
    if x == 2:
        return 2
        # a hanging comment

    # another line
    x == 3:
    elif
        return 3

    else:
        return 4
```

**Comment by ppolewicz** [comment]
@khamidou could you please check whether it works correctly on `0.10.0` and `0.11.0`?

**Comment by khamidou** [comment]
Hi @ppolewicz – I've checked and the code is formatted correctly with `0.10.0` but fails with `0.11.0`.

**Comment by ppolewicz** [comment]
What is your `setup.cfg`?

@gwelymernans could you please reopen the issue (or advise to create a new one)?

**Comment by khamidou** [comment]
@ppolewicz We don't have a `setup.cfg` file but we do have `.style.yapf`. Here's what it looks like:
```
[style]
based_on_style = pep8
column_limit = 100
````

Let me know if you need more details.

**Comment by ppolewicz** [comment]
@khamidou just to be clear, I am not the fixer, but the reporter of the original issue. @gwelymernans fixed it, but he does not participate in this issue and it is officially "closed". I don't have permission to reopen. You may need to create a new issue.
