### ISSUE TITLE
USE_TABS does not work for indentation

### ISSUE THREAD

**Issue by spaceone** [google/yapf#328]
USE_TABS=True is ignored for continued indentation. Instead spaces are used.

My configuration:

[.style.yapf](https://github.com/google/yapf/files/559934/default.style.yapf.txt)
Reproduce:

```
$ yapf --version
yapf 0.13.2
printf "property_descriptions = {\n\t'name': admin.property(\n\t\tshort_description=_('Foobar'),\n\t\tlong_description='',\n\t\tsyntax=syntax.hostName,\n\t\tmultivalue=False,\n\t\tinclude_in_default_search=True,\n\t\toptions=[],\n\t\trequired=True,\n\t\tmay_change=False,\n\t\tidentifies=True\n\t),\n}\n" > /tmp/foo.py
yapf --style .style.yapf /tmp/foo.py
```

Also you cannot specify /dev/stdin or "-" as argument for the file.

**Comment by spaceone** [comment]
A follow up error of this is that with CONTINUATION_INDENT_WIDTH=4 the following gets replaced into wrong reindention:
```
layout = [
    Tab(_('General'), _('Basic settings'), layout=[
        Group(_('Computer account'), layout=[
            ['name', 'description'],
            'inventoryNumber',
        ]),
    ]),
]
```

→ 
```
layout = [
    Tab(_('General'), _('Basic settings'), layout=[
        Group(_('Computer account'), layout=[
   ['name', 'description'],
   'inventoryNumber',
        ]),
    ]),
]
```

This makes this tool unusable for me.

**Comment by eskhool** [comment]
+1, facing the same issue with the tool. Any suggestions on where to start with the fix?

**Comment by gwelymernans** [comment]
I'll take a look at this, but if you look at the `whitespace_prefix` bit in the `format_token` module, it should help determine what's going on here with the tabs.
