### ISSUE TITLE
yapf collapses example onto single too long line

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#332]
yapf --style=pep8 will reformat the following code:

``` python
class a:
    def b():
        ccc(
         ddddddddd=lambda eeeeeeeeeeeeeeeeeeeee:
         ffffffffffffffffffffffffffff
        )
```

into the following:

``` python
class a:
    def b():
        ccc(ddddddddd=lambda eeeeeeeeeeeeeeeeeeeee: ffffffffffffffffffffffffffff
            )
```

As well as looking kinda weird with its closing bracket placement, the generated line is too long (80 characters rather than 79).

I tested this running against a2f0342 under Python 3.5.1

**Comment by petobens** [comment]
I'm also having this issue with pep8 style where lines are 80 characters long instead of 79. Thanks in advance for looking into this.

**Comment by gwelymernans** [comment]
I'm not sure how I missed this one. Sorry for the delayed response.

This is because lambdas shouldn't be more than a single line. So it's kind of a "damned if you do / damned if you don't" situation. If we wrap the lambda onto two lines, then you're violating that rule. Otherwise, you're violating the column limit. If you want to violate the lambda rule, you can set `ALLOW_MULTILINE_LAMBDAS` to `True`.

```python
$ yapf --style '{based_on_style: pep8, ALLOW_MULTILINE_LAMBDAS: True}' x.py
class a:
    def b():
        ccc(ddddddddd=lambda eeeeeeeeeeeeeeeeeeeee:
            ffffffffffffffffffffffffffff)
```

**Comment by DRMacIver** [comment]
> So it's kind of a "damned if you do / damned if you don't" situation.

It's probably not, but would it be possible to get yapf to emit some sort of warning when it's forced into decisions like that?

**Comment by gwelymernans** [comment]
@DRMacIver I don't know if that's really feasible to do. When yapf decides that one line needs to go over the column limit, it doesn't know what decision finally drove it to determine this. For example, whether it was from the subscript splitting penalty being too high or from a lambda expression penalty.

**Comment by gwelymernans** [comment]
@petobens Ah! Your situation is slightly different. In this case, yapf is fighting between keeping a subscript contiguous and going over the column limit. If you changed the `SPLIT_PENALTY_EXCESS_CHARACTER` to, say, 3100, it would give you this output (which admittedly sucks):

```python
import pandas as pd


def foo():
    df = pd.DataFrame()
    df = df[(df['campaign_status'] == 'LIVE') & (df['action_status'] == 'LIVE'
                                                 )]
```

(This is an interesting way to switch between "`df[0]`" and "`df[1]`". :-) )

I'll see what I can do to fix this issue. In general, yapf doesn't like to split subscripts at all...

**Comment by petobens** [comment]
@gwelymernans great! Thank you!

**Comment by petobens** [comment]
@gwelymernans thank you! One minor question. Consider the following example:
```python
class Foo:
    def __init__(self):
        self.col_order = None

    def bar(self):
        group_metrics = 'this is a pandas data frame'
        group_metrics = group_metrics[['group_id', 'action_id', 'action_name', 'source'] + self.col_order]
```
which (currently) gets formatted like this:
```python
class Foo:
    def __init__(self):
        self.col_order = None

    def bar(self):
        group_metrics = 'this is a pandas dataframe'
        group_metrics = group_metrics[
            ['group_id', 'action_id', 'action_name', 'source'] + self.col_order]
```
therefore violating the 79 column limit (since the last line is actually 80 characters long). Is this expected? Once again thanks for the help and patience :)

**Comment by gwelymernans** [comment]
No, it shouldn't happen. :-( When I try it, I get this:

```python
class Foo:
    def __init__(self):
        self.col_order = None

    def bar(self):
        group_metrics = 'this is a pandas dataframe'
        group_metrics = group_metrics[
            ['group_id', 'action_id', 'action_name', 'source'] +
            self.col_order]
```
