### ISSUE TITLE
Line break before binary operator

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#335]
yapf --style=pep8 reformats the following code:

```python
class A:
    def b():
        aaaaa*a * aa*aaaa(
         aaa +
         aaa*a) or aaa*aaaa*aaaaa(
         aaa*aaaaa + aa)
```

as the following:

```python
class A:
    def b():
        aaaaa * a * aa * aaaa(aaa + aaa * a) or aaa * aaaa * aaaaa(aaa * aaaaa
                                                                   + aa)
```

According to pep8 the line break needs to be after the final +, not before.

I tested this running against a2f0342 under Python 3.5.1

**Comment by henryrizzi** [comment]
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

That's the correct formatting I believe. Binary Operators should remain close to their operands.

**Comment by DRMacIver** [comment]
Huh, so it is. Apparently they [changed pep8 earlier this year](https://hg.python.org/peps/rev/3857909d7956) and I guess I didn't notice and was running a checker that was based off the old choice. Sorry about that!
