### ISSUE TITLE
Allow two empty lines between imports and assignments

### ISSUE THREAD

**Issue by gforcada** [google/yapf#340]
At @plone we created our own styleguide and decided that between imports and code there should be 2 blank lines, to clearly mark the end of imports and beginning of code.

yapf though eats one of those two blank lines, would it be possible to add a knob for that?

**Comment by gforcada** [comment]
I noticed that it already puts 2 blanks lines for imports and classes/functions but it only keeps one blank line when there is an assignment, i.e.:

```
import os


TOP_LEVEL = True
```

gets reformatted to:

```
import os

TOP_LEVEL = True
```

**Comment by arareko** [comment]
This feature will be available in version `0.31.0` of YAPF
