### ISSUE TITLE
Force new line for dict key

### ISSUE THREAD

**Issue by gforcada** [google/yapf#341]
Hi,

I'm testing yapf and I stumbled upon a change that yapf makes that I don't want:

```
-    extras_require={
-        'test': [
-            'plone.app.testing',
-            'plone.testing',
-        ],
-    },
+    extras_require={'test': [
+        'plone.app.testing',
+        'plone.testing',
+    ], },
```

So, keep the first key of a dictionary in a new line rather than on the first line itself.

I'm using the following configuration on ``.style.yapf``:

```
[style]
based_on_style = pep8
dedent_closing_brackets = True
coalesce_brackets = False
```

Am I missing a knob or not configuring them properly?

**Comment by advance512** [comment]
Agree, this should definitely be a knob.

**Comment by gwelymernans** [comment]
Weird. I'm not able to replicate this...What version of YAPF are you using?

**Comment by advance512** [comment]
I got this on yapf 0.14.0.

**Comment by gforcada** [comment]
@gwelymernans as @advance512 says, I was testing it with version 0.14.0

**Comment by advance512** [comment]
Update?

**Comment by gwelymernans** [comment]
This is what I get:

```python
python -m yapf --style '{based_on_style: pep8, coalesce_brackets: False, dedent_closing_brackets: True}' < /tmp/y.py
def _():
    extras_require = {
        'test': [
            'plone.app.testing',
            'plone.testing',
        ],
    },
```

**Comment by gforcada** [comment]
I can not reproduce it with yapf 0.17.0
