### ISSUE TITLE
Inconstiten spacing with keyword argument and string type hints

### ISSUE THREAD

**Issue by wheerd** [google/yapf#351]
Similar to #174 I am getting inconsistent spacing around the equal sign for function default arguments when I am using a string as type hint:
```python
def foo(x: int=42):
    pass


def foo2(x: 'int' =42):
    pass
```
Then pylint will (rightfully) complain about the second one:
```
C:  5, 0: No space allowed before keyword argument assignment
def foo2(x: 'int' =42):
                  ^ (bad-whitespace)
```

**Comment by wheerd** [comment]
Thanks for fixing this :)

**Comment by rjkmurray** [comment]
Help me with my git hub email.  Lloyd.
