### ISSUE TITLE
Yapf removes blank line before class docstring for no reason

### ISSUE THREAD

**Issue by underyx** [google/yapf#358]
I have the following code

```python
class A:

    """Does something.

    Also, here are some details.
    """

    def __init__(self):
        # …
```

and yapf changes it to

```python
class A:
    """Does something.

    Also, here are some details.
    """

    def __init__(self):
        # …
```

even when the (most likely unrelated) `BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF` knob is set to `True`. Either way, I think yapf should just leave these blank lines of mine alone >:(

**Comment by gwelymernans** [comment]
YAPF does this because the class-level docstring shouldn't have a space before it. I'll add a knob though so that you can retain one if you want. :-)

**Comment by underyx** [comment]
Wow, cool, thanks, @gwelymernans!
