### ISSUE TITLE
`.yapf.style` in pwd is getting ignored?

### ISSUE THREAD

**Issue by ChillarAnand** [google/yapf#360]
```
→c test.py
this_is = foo('aaaaaaaaaaaaaaaaaaaaa',
              'bbbbbbbbbbbbbbbcccccccccccccccccccccccccccccb')

→yapf test.py 
this_is = foo('aaaaaaaaaaaaaaaaaaaaa',
              'bbbbbbbbbbbbbbbcccccccccccccccccccccccccccccb')

→yapf test.py --style .yapf.style
this_is = foo('aaaaaaaaaaaaaaaaaaaaa', 'bbbbbbbbbbbbbbbcccccccccccccccccccccccccccccb')

→c .yapf.style 
[style]
based_on_style = google
split_before_first_argument = false
column_limit = 120
```

**Comment by gwelymernans** [comment]
There are two things going on here. First, the file should be named `.style.yapf`. And second it will pick up that file only if it's in a parent directory. It'll pick up that file in the current directory if yapf is reading from `stdin`. See the `--help` text for details.

**Comment by spectralLight** [comment]
Hello

I made a setup.cfg file and put it in the parent directory
`
[yapf]
based_on_style = google
indent_width = 120
`
if i use yapf in the console

`yapf someCode.py`

the config file is being used and the indent_width is being applied like expacted.

Howerver if i use Pycharm IDE menu "Code"-> "Reformate Code with yapf" the config file is being ignored and code is formatted with default settings.

the executable yapf is in /usr/local/bin/ and the setup.cfg in the parent directory.

Thx in advance for an answer.
