### ISSUE TITLE
includes blank lines everywhere no matter which style (on Windows)

### ISSUE THREAD

**Issue by MagSec-Arts** [google/yapf#363]
I tested ``pep8`` and ``google`` style on the same module.

Booth ended up in generating blank lines all over the place:

```python
# coding=utf-8
"""

Usage: Store



    >>> try: a = 1 + 'b'

    ... except:

    ...     from tracebackHandler import catchError

    ...     catchError()



"""

import getpass

import socket

import time

# ...


    @classmethod
    def add(cls, tracebackMessage):

        cls._stack.append(tracebackMessage)

    @classmethod
    def clear(cls):

        cls._stack = []

# ...
```

It seems I get a blank line almost everywhere in my code.

With this behavior I can't use ``yapf`` in production with Windows.

This doesn't happen on Debian or OSX.

**Comment by gwelymernans** [comment]
Quite weird. I wonder if this is a `\r\n` vs `\n` thing. Could you print the lines showing the newlines to see?

**Comment by gwelymernans** [comment]
This may be fixed by #366 PR. Could you patch your copy and try it out, please? I'd like to know if it solves this...

**Comment by MagSec-Arts** [comment]
The lines are ending on ``\r\n`` (``CR+LF``).
I tested it with the suggested patch https://github.com/google/yapf/pull/366 and now it works fine.

**Before:**
```python
import os
import sys

import ticket
class D():
    D=3
class ABC(object):
    A = 'p'
    B = 0
    c = D
# Comment
def a(a, *args):
    try:
        x = a + 1
    except:
        x = None
    return x
```

**After:**
```python
import os
import sys

import ticket


class D():
    D = 3


class ABC(object):
    A = 'p'
    B = 0
    c = D


# Comment
def a(a, *args):
    try:
        x = a + 1
    except:
        x = None
    return x
```

**Comment by gwelymernans** [comment]
Oh good! That PR was merged and the new release should have it. Thank you!
