### ISSUE TITLE
yapf collapsing brackets onto a single line of more than 80 characters

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#37]
The following:

    def feed(request, url, feed_dict=None):
        instance.title_template = f.title_template or (
            'feeds/%s_title.html' %
            slug)

gets reformatted as:

    def feed(request, url, feed_dict=None):
        instance.title_template = f.title_template or ('feeds/%s_title.html' % slug)

**Comment by gwelymernans** [comment]
The "instance" line isn't over 80 characters long.

```
    instance.title_template = f.title_template or ('feeds/%s_title.html' % slug)
********************************************************************************
```

However, with the PEP 8 styling (79 characters), it gives this, which is ugly:

```
def feed(request, url, feed_dict=None):
    instance.title_template = f.title_template or ('feeds/%s_title.html' % slug
                                                  )
```

**Comment by DRMacIver** [comment]
Hm. You're right, it's not. I wonder why I thought it was when I submitted this. Apologies.

(I suspect the answer is that I edited this incorrectly out of something that actually did exhibit a bug, but I don't know what).
