### ISSUE TITLE
W503: yapf inserts line break before rather than after a binary operator

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#38]
The following:

    def w(context): {
        'e_link': (
            not is_popup and context['has_delete_permission'] and
            ange and t('e', True)
        ),
    }

Gets reformatted as:

    def w(context):
        {
            'e_link': (not is_popup and context['has_delete_permission'] and ange
                       and t('e', True)),
        }

Which is wrong. The "and" should not be starting a line according to pep8.

**Comment by gwelymernans** [comment]
Could you check this again? I think it's been fixed:

```
def w(context):
    {
        'e_link': (
            not is_popup and context['has_delete_permission'] and ange and
            t('e', True)),
    }
```
