### ISSUE TITLE
reorder imports

### ISSUE THREAD

**Issue by xoviat** [google/yapf#385]
yapf does not conform to the C0411 standard, which governs the order of imports. this should be resolved.

**Comment by gwelymernans** [comment]
I don't see any errors given by pylint for C0411. Co you have an example?

**Comment by xoviat** [comment]
![image](https://cloud.githubusercontent.com/assets/15351036/24413004/be9966c8-139f-11e7-9529-224d0f383151.png)

**Comment by gwelymernans** [comment]
Um...yapf doesn't use `import inspect` anywhere.

**Comment by xoviat** [comment]
> Um...yapf doesn't use import inspect anywhere.

No, that's an example file that's been parsed by yapf.

**Comment by audiolion** [comment]
I would recommend using [isort](https://github.com/timothycrosley/isort) if you want your imports intelligently sorted and conforming with flake, I don't think yapf's scope is to reorder imports

**Comment by xoviat** [comment]
>  I don't think yapf's scope is to reorder imports

yapf claims to be gofmt for python; gofmt reorders imports as far as I can tell.

**Comment by gwelymernans** [comment]
Actually, we claim to be more like a `clang-format` for Python. :-) Reordering import statements isn't something I want `yapf` to do. I know that `gofmt` does that, but it's a lot trickier to do in Python, and I don't want to get into that quagmire.

**Comment by albertodonato** [comment]
Isort (https://github.com/timothycrosley/isort) does a pretty good job at that, FTR

**Comment by tjulinfan** [comment]
Hi there, seems I encountered the same issue. And I don't want to ignore such errors in pylint, is there any workaround to make yapf to follow C0411 standard?
