### ISSUE TITLE
E203, E702: Whitespace before ';' and not fixing multiple statements per line

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#40]
The following code

    d(ew);ing_new

is reformatted as:

    d(ew) ; ing_new

The whitespace before ; is definitely forbidden by pep8. The multiple statements per line is "discouraged".

**Comment by gwelymernans** [comment]
Also fixed separating semicolon statements into single statements:

  0da6b3f..f95b17e  master -> master
