### ISSUE TITLE
F-strings crash yapf

### ISSUE THREAD

**Issue by RenatoUtsch** [google/yapf#404]
Code using the new [F-strings](https://www.python.org/dev/peps/pep-0498/) feature introducted in Python 3.6 crashes yapf.

I'm using yapf version 0.16.1.

**Comment by audiolion** [comment]
this is a duplicate of https://github.com/google/yapf/issues/342

**Comment by RenatoUtsch** [comment]
Sorry, didn't see that in the issues list. Guess I should stop searching only on the first page.
