### ISSUE TITLE
Should print filename for ParseError

### ISSUE THREAD

**Issue by cancan101** [google/yapf#413]
I ran `yapf -d --recursive` and the error I get is:
```
lib2to3.pgen2.parse.ParseError: bad input: type=8, value=u')', context=('', (1, 28))
``` 
which is not enough info to tell what file is the issue. the line and column numbers are printed.

I suggest adding the file path to the context. Might require catching the `ParseError` and then re-throwing along with the information.

**Comment by gwelymernans** [comment]
You're right. That should be way more informative. I'll see what I can do.
