### ISSUE TITLE
Reformatting dict-key assignments with long values?

### ISSUE THREAD

**Issue by mikelambert** [google/yapf#417]
I just started using auto-format-js-on-save and it changed my life. As a former Google-python-readability-reviewer, I am therefore super-excited about yapf. :)

Looking at it reformat my code, I think my only complaint is it choosing to reformat a long line as:
```
+        self.display[
+            'needs_polyfill'] = 'fb_iab' in user_agent or 'ucbrowser' in user_agent
```
I'd much prefer the following for readability:
```
+        self.display['needs_polyfill'] = (
+            'fb_iab' in user_agent or 'ucbrowser' in user_agent)
```
(Which incidentally, also better matches how yapf reformats in the case of: `"key": some_long_value_here`)

I couldn't see any options for this however...curious if this is within the realm of yapf reformatting (adding parens), and if there's a certain weight param I would need to trigger this?

**Comment by jouve** [comment]
it looks related to #415

**Comment by mikelambert** [comment]
Yes, looks like a dupe, thanks!
