### ISSUE TITLE
`split_before_first_argument` doesn't work on some cases

### ISSUE THREAD

**Issue by jorgehatccrma** [google/yapf#424]
There seem to be some corner cases where `split_before_first_argument` doesn't seem to work as expected (at least not as I'd expect). For example using this style config

```
[style]
based_on_style = pep8
align_closing_bracket_with_visual_indent=True
coalesce_brackets=True
dedent_closing_brackets=False
indent_dictionary_value=True
spaces_around_power_operator=False
space_between_ending_comma_and_closing_bracket=False
split_arguments_when_comma_terminated=True
split_before_first_argument = False
split_before_named_assigns = False
split_penalty_after_opening_bracket=30
split_penalty_for_added_line_split=30
use_tabs=False
```

the following unformatted code:

```
a_super_long_version_of_print(argument1, argument2, argument3, argument4, argument5, argument6, argument7)
CREDS_FILE = os.path.join(os.path.expanduser('~'), 'apis/super-secret-admin-creds.json')
```

Gets formatted into:

```
a_super_long_version_of_print(argument1, argument2, argument3, argument4,
                              argument5, argument6, argument7)
CREDS_FILE = os.path.join(
    os.path.expanduser('~'), 'apis/super-secret-admin-creds.json')
```

While the formatted original first line looks the way I'd expect, with all the arguments it can fit in the first line, and the remaining ones hanging at the same indentation level as the first one, the second original line seems to apply a different heuristic. Instead of what I'm getting, I was expecting to get:

```
CREDS_FILE = os.path.join(os.path.expanduser('~'),
                          'apis/super-secret-admin-creds.json')
```

If this is the expected behaviour, I'd appreciate if you can let me know if there's a configuration knob I could use to achieve my desired style.

**Comment by g-bon** [comment]
@jorgehatccrma I'm experiencing the same. Have you eventually found a solution?

**Comment by haqle314** [comment]
I fixed it by setting `split_penalty_after_opening_bracket` to a really large value, `1,000,000` worked in my case. I've just started using `yapf` so I'm not sure if this will interfere with anything else though.

**Comment by apbard** [comment]
@haqle314 not working for me
