### ISSUE TITLE
Return error if files were changed and quiet argument

### ISSUE THREAD

**Issue by mattdavis90** [google/yapf#433]
What are the thoughts on having the a quiet argument to the command line application and returning a non-zero value if the code requires changing.

This would then allow chaining in a CI environment; e.g. test code formatting prior to running tests and hence stop the pull request if formatting is bad.

Thanks

**Comment by gwelymernans** [comment]
This is interesting. Actually, the code doesn't follow the docstring. We're supposed to return a non-zero value if things changed, but we don't. Your change fixes that, so that's a plus. I'll take a closer look at it.
