### ISSUE TITLE
Dict value not indented after split

### ISSUE THREAD

**Issue by jonashaag** [google/yapf#435]
```py
def foo():
    def bar():
        foobar = spameggsspameggsspameggs({
            'foobarfoobarfoobar':
            '123456789123456789',
        })
```

Note the missing indentation before the 123... Is this intended behaviour and if so is there a knob to disable it?

**Comment by gwelymernans** [comment]
Yes, it's intentional. If you use `indent_dictionary_value`, it should do what you want.
