### ISSUE TITLE
yapf: disable disables just enough to generate invalid syntax

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#44]
The following syntactically valid python:

    class SplitPenaltyTest(unittest.TestCase):
      def testUnbreakable(self):
        self._CheckPenalties(tree, [
        ])  # yapf: disable

Is reformatted into the following invalid python:

    class SplitPenaltyTest(unittest.TestCase):
        def testUnbreakable(self):
        self._CheckPenalties(tree, [
        ])  # yapf: disable

**Comment by gwelymernans** [comment]
Fixed by 1d7fe7e.
