### ISSUE TITLE
Use pyga/awpa instead of lib2to3

### ISSUE THREAD

**Issue by bwendling** [google/yapf#448]
pyga/awpa may support Python3 more fully than lib2to3. It would be good to explore this.

**Comment by ipfans** [comment]
It seems that https://github.com/pyga/awpa not complete for all source. And PyPi version of awpa still missing grammar of Python 3.6. I think we still need to waiting for new version release of awap.

**Comment by gwelymernans** [comment]
Do they have a timeline for that?

**Comment by pquentin** [comment]
See https://bugs.python.org/issue40360: lib2to3 is now deprecated and may not be able to fully parse Python 3.10+. CPython encourages using https://libcst.readthedocs.io/ or https://parso.readthedocs.io/

**Comment by kamahen** [comment]
LibCST builds on parso. Comparing stars on GitHub:
- LibCST: 423
- parso: 296
- awpa: 10
https://bugs.python.org/issue40360#msg367726

**Comment by kamahen** [comment]
I suspect that pyga/awpa isn't the best solution (it seems to have lib2to3 underneath it).

I've written up a proposal for augmenting the stdlib ast module; this would of course require some work in yapf as well.
https://mail.python.org/archives/list/python-ideas@python.org/thread/X2HJ6I6XLIGRZDB27HRHIVQC3RXNZAY4/

**Comment by bwendling** [comment]
Closed with 7c408b9d7750292760ed255f744211d1ef535668.
