### ISSUE TITLE
dedent_closing_brackets = false not respected for square brackets.

### ISSUE THREAD

**Issue by thisfred** [google/yapf#452]
With the `dedent_closing_brackets` setting set to false, I would expect the following line to not be changed by YAPF

```python
        source, destination, options = [conf.get(key) for key in
                                        ('source', 'destination', 'options')]
```

or, if it was, to be changed to:

```python
        source, destination, options = [
            conf.get(key) for key in ('source', 'destination', 'options')]
```

but instead I get:

```python
        source, destination, options = [
            conf.get(key) for key in ('source', 'destination', 'options')
        ]
```

which seems to go directly against the setting. (which does seem to work for parentheses, but the documentation claims: "Applies to all kinds of brackets, including function definitions and calls.")

**Comment by thisfred** [comment]
If this behaviour is confirmed to be undesirable, I can try and figure out how to fix it.

**Comment by gwelymernans** [comment]
The flag isn't having an effect because YAPF is requiring a split before the ending bracket. This is because it's splitting after the opening bracket. It's arguably not the correct behavior. (The knob was added by Facebook to comply with their style: 94089878.)

**Comment by patrys** [comment]
The documentation is misleading as it explicitly shows a dict literal being affected by this knob yet yapf insists on giving the closing brace its own line.

**Comment by patrys** [comment]
See #525

**Comment by thisfred** [comment]
thank you!

**Comment by patrys** [comment]
I think this can be closed as there is now a separate knob to control this.
