### ISSUE TITLE
Function definition formatting change in 0.17 -> 0.18

### ISSUE THREAD

**Issue by njsmith** [google/yapf#458]
In 0.17, with [this .style.yapf](https://github.com/python-trio/trio/blob/4d41a6ddfa352cc2002592a64b58f9a7172c9495/.style.yapf), this code is formatted like this:

```python
async def open_file(
    file,
    mode='r',
    buffering=-1,
    encoding=None,
    errors=None,
    newline=None,
    closefd=True,
    opener=None
):
    pass

async def run_sync_in_worker_thread(
    sync_fn, *args, cancellable=False, limiter=None
):
    pass
```

If I keep everything else the same and upgrade to 0.18, then it gets reformatted as:

```python
async def open_file(file, mode='r', buffering=-1, encoding=None, errors=None,
                    newline=None, closefd=True, opener=None):
    pass


async def run_sync_in_worker_thread(sync_fn, *args, cancellable=False,
                                    limiter=None):
    pass
```

It's not really obvious to me which is better, but I was caught by surprise. Is this expected? I don't see anything about it in the CHANGELOG...

**Comment by njsmith** [comment]
Bizarrely, `git bisect` says that the change happened in 6412ce704a8fcbf74544d12f2ee211d9b2087f9b.

Before that commit, there is a weird discrepancy between `def` and `async def`, where for some reason the argument list above becomes indented *more* (8 spaces) if I used `def`, but otherwise they're formatted similarly. After that commit, we get the effect shown above.

**Comment by gwelymernans** [comment]
Ironically, it looks like the `split_before_first_argument` knob is causing this.
