### ISSUE TITLE
Weird behavior associated to split_before_named_assigns=False

### ISSUE THREAD

**Issue by derkuci** [google/yapf#465]
The document says, when `split_before_named_assigns=True`, yapf will "split named assignments onto individual lines".  If the value is set to False, it seems to me that this means "I don't particularly want to break every named assignments onto individual lines, but I am still OK to break before some named assignments, if necessary."

However, I tried various settings and it all pointed to `split_before_named_assigns=False` would make yapf try very hard to avoid breaking before any named assignments.  For example, it'll change 
```
for var in a_list:
    foo_barr('some string', 12345678, some_list + [var], [var, var, var])
    foo_barr('some string', 12345678, some_list + [var], [var, var, var],
             some_named_var=dict.fromkeys(another_list + [var], SOME_CONSTANT))
```
to
```$ yapf test.py 
for var in a_list:
    foo_barr('some string', 12345678, some_list + [var], [var, var, var])
    foo_barr('some string', 12345678, some_list + [var],
             [var, var, var], some_named_var=dict.fromkeys(
                 another_list + [var], SOME_CONSTANT))
```
Seems quite strange to me.

**Comment by gwelymernans** [comment]
This may have been fixed recently. Could you try it with top-of-tree?

**Comment by derkuci** [comment]
Yes, I believe it has been fixed.  Thank you!
