### ISSUE TITLE
Parsing python 2 syntax on python 3 results in internal error

### ISSUE THREAD

**Issue by GrahamCampbell** [google/yapf#476]
This is because the initial parse succeeds by falling back to python 2 grammar, however the verify phase fails. It would be cool if we could turn off falling back in this way, and force the parsing to be in the same python version as the host machine.

**Comment by gwelymernans** [comment]
The verifier isn't really reliable. There are a lot of situations it can't support. So it's probably best not to use it (it's basically for debugging).

**Comment by GrahamCampbell** [comment]
Ah, ok. Thanks.

What do you make of having a flag to force parsing the code as python 2 if running as python 2, and force parsing as python 3 if running as python 3?

> There are a lot of situations it can't support.

I assume all the situations it can't support are those which arise from the runtime language definition differing from the grammar used to parse the file originally?

**Comment by GrahamCampbell** [comment]
How about this:

```py
def ParseCodeToTree(code):
  grammar = _GRAMMAR_FOR_PY3 if sys.version_info[0] == 3 else _GRAMMAR_FOR_PY2
  parser_driver = driver.Driver(grammar, convert=pytree.convert)
  tree = parser_driver.parse_string(code, debug=False)

  return _WrapEndMarker(tree)
```

**Comment by GrahamCampbell** [comment]
Or, I guess, actually:

```py
def ParseCodeToTree(code):
  try:
    grammar = _GRAMMAR_FOR_PY3 if sys.version_info[0] == 3 else _GRAMMAR_FOR_PY2
    parser_driver = driver.Driver(grammar, convert=pytree.convert)
    tree = parser_driver.parse_string(code, debug=False)
  except parse.ParseError:
    try:
      ast.parse(code)
    except SyntaxError as e:
      raise e
    else:
      raise

  return _WrapEndMarker(tree)
```

**Comment by gwelymernans** [comment]
Is there a benefit to parsing as Python 2 for Python 2 code over Python 3, if it still supports the Python 2-ism?
