### ISSUE TITLE
For triple-quoted strings, always use double quote characters to be consistent with the docstring convention in PEP 257.

### ISSUE THREAD

**Issue by pgdr** [google/yapf#479]
According to [PEP-8](https://www.python.org/dev/peps/pep-0008/) and [PEP-257](https://www.python.org/dev/peps/pep-0257/), every triple-quoted string, _including docstrings_, should be double quotes.

That is, `yapf` should translate
```python
def f():
    '''Docstring'''
    pass
```
to
```python
def f():
    """Docstring"""
    pass
```

**Comment by gwelymernans** [comment]
Sorry, YAPF intentionally doesn't change the contents of tokens.
