### ISSUE TITLE
Wrong documentation for finding .style.yapf

### ISSUE THREAD

**Issue by peterludemann** [google/yapf#489]
The documentation says ".style.yapf or setup.cfg file located in one of the parent directories of the source file (or current directory for stdin)".

Perhaps you and I have different understandings about the meaning of "parent directory"; but by experiment, I found that .style.yapf takes effect if it's in the same directory as the source (this is a Good Thing). So, I suggest changing the wording to "in the same directory as the source file or one of its parent directories (for stdin, the current directory is used)."

**Comment by gwelymernans** [comment]
That sounds fine. Would you like to submit a PR for it? :-)

**Comment by peterludemann** [comment]
OK, I'll get a round tuit "soon".

**Comment by gwelymernans** [comment]
Here you go: https://upload.wikimedia.org/wikipedia/commons/9/93/RoundTuit.jpg

**Comment by peterludemann** [comment]
pull request: #492
