### ISSUE TITLE
Weird case w/ dedent_closing_brackets=True where yapf preserves terribly formatted line for no obvious reason

### ISSUE THREAD

**Issue by njsmith** [google/yapf#495]
Originally noticed with 0.17, reproduced with current master.

Create a file foo.py:
```python
if (isinstance(value  , (StopIteration  , StopAsyncIteration  )) and exc.__cause__ is value_asdfasdfasdfasdfsafsafsafdasfasdfs):
    return False
```
Notice that the first line goes way over the column limit, as well as having lots of random weird whitespace.

 `yapf --style=pep8 foo.py` fixes it, as expected (removes the weird whitespace and splits the first line).

`yapf --style=facebook foo.py` returns the file through unchanged, as if it was already correctly formatted (!!)

**Comment by njsmith** [comment]
On further investigation, it looks like to reproduce the above issue, it's sufficient to have a style that's identical to pep8, except with `dedent_closing_brackets` set to `True`.

**Comment by gwelymernans** [comment]
What's happening is that with the Facebook style the formatter isn't able to come up with an acceptable formatting for the line. So it just prints the line as is.

**Comment by njsmith** [comment]
Excellent, thanks!
