### ISSUE TITLE
The live demo being hosted on heroku is giving  Application error

### ISSUE THREAD

**Issue by anubhakushwaha** [google/yapf#496]
On trying to view the demo it is giving **Application Error** , along with the message, 
> An error occurred in the application and your page could not be served. If you are the application 
> owner, check your logs for details.

**Comment by mingrammer** [comment]
Same here

**Comment by JasonShin** [comment]
Same

**Comment by JasonShin** [comment]
:+1:

**Comment by michaelmior** [comment]
Seeing this again.

**Comment by jpadilla** [comment]
Ugh, seems like I'm running out of free hours for this. Just deployed to https://yapf.now.sh instead. Will open a PR to update.

**Comment by JasonShin** [comment]
@jpadilla Do you have demo source code available by any chance? I'd like to host it internally for a demo purpose.

**Comment by jpadilla** [comment]
Source code is at https://github.com/jpadilla/yapf-online
