### ISSUE TITLE
setup.cfg yapf configuration not loaded

### ISSUE THREAD

**Issue by r00tat** [google/yapf#502]
As suggested in #392:

`setup.cfg` yapf configuration is not being loaded. It seems like only `.style.yapf` is being loaded.

.style.yapf:

```
[style]
indent_dictionary_value=true
```

test.py:
```
a = {
    "a": "aaaaaaaaaaaaa",
    "b": "bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb  bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb",
}
```

```
$ yapf test.py
settings = {
    "a":
        "aaaaaaaaaaaaa",
    "b":
        "bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb  bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb",
}
```

Now moving .style.yapf to setup.cfg:

```
$ mv .style.yapf setup.cfg
$ yapf test.py
settings = {
    "a":
    "aaaaaaaaaaaaa",
    "b":
    "bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb  bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb bbbbbbbbbbbbb",
}
```

Lines "aaaaaaaaaaaaa", and "bbbbbbbbbbbbb..." are not indented.

**Comment by gastlich** [comment]
@r00tat I think it should be under *[yapf]* section instead in `setup.cfg` file

> In the [yapf] section of a setup.cfg file in either the current directory or one of its parent directories.

**Comment by gwelymernans** [comment]
@r00tat: Please try what @gastlich mentioned. I think that should solve your issue.

**Comment by r00tat** [comment]
Thanks, that solved the issue.
