### ISSUE TITLE
Python 3.6 dict unpacking weird indentation

### ISSUE THREAD

**Issue by jonashaag** [google/yapf#504]
```python
class Foo:
    def foo(self):
        foofoofoofoofoofoofoofoo('foofoofoofoofoo', {
            'foo': 'foo', **foofoofoo
        })
```

yapf (master) turns this into

```python
class Foo:
    def foo(self):
        foofoofoofoofoofoofoofoo('foofoofoofoofoo', {
            'foo': 'foo',
            **
            foofoofoo
        })
```

which is unexpected for two reasons:

- There's enough space on the `'foo'` line to put `**foofoofoo`
- IMO it doesn't make sense to split the `**` and `foofoofoo`

Not sure if this is a minimal example; I simply took an example from a codebase and replaced everything with "foo".

**Comment by gwelymernans** [comment]
That is indeed weird...I'll try to fix.
