### ISSUE TITLE
Demo seems doesn't work

### ISSUE THREAD

**Issue by lzhuor** [google/yapf#508]
The [demo](https://yapf.herokuapp.com/) doesn't really work as of now. 

It shows an
```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```

**Comment by jinfagang** [comment]
Same

**Comment by gwelymernans** [comment]
This should be fixed now I believe. There was an issue with resources at the demo's site. I'll close this for now. Please let me know if it persists.

**Comment by lzhuor** [comment]
@gwelymernans Thank you, it works now. [DEMO](https://yapf.now.sh/)

**Comment by roopeshvs** [comment]
@gwelymernans The [demo](https://yapf.now.sh/) seems to be not working again.
ZEIT v1 has been shut down. https://mailchi.mp/f923e55efe1d/simplified-pricing-1087517
