### ISSUE TITLE
Extra spaces being added by yapf (ad-infinitum).

### ISSUE THREAD

**Issue by alanhdu** [google/yapf#513]
Using `yapf 0.20.1` and Python 3.6.4, when I `yapf` the following code:

```python
import yaml

{
   "config": {
           **yaml.load(f"""
    a:
      b: 0""")},
 }
```

yapf adds an extraneous 13 spaces after the closing `"""`:

```
--- test.py	(original)
+++ test.py	(reformatted)
@@ -4,5 +4,5 @@
    "config": {
            **yaml.load(f"""
     a:
-      b: 0""")},
+      b: 0"""             )},
  }
```

Running `yapf` repeatedly just adds even more spaces (ad-infinitum). This does *not* happen if:
- We don't use a format string
- We take out the wrapping `config` dictionary
- We don't use the new dict unpacking `**` syntax.

This also ignores `yapf: disable` comments, so 
```python
import yaml
# yapf: disable
{
   "config": {
           **yaml.load(f"""
    a:
      b: 0""")},
 }
# yapf: enable
```

*still* inserts extra spaces.

**Comment by gwelymernans** [comment]
Whoa! Yeah, this is bad...

**Comment by gwelymernans** [comment]
I'm not able to replicate this. Could you try with HEAD?

**Comment by alanhdu** [comment]
After `pip install git+https://github.com/google/yapf@master` I still get the same behavior.

Hm... could you try using the following dockerfile then (where `test.py` is the code sample at the beginning?). That might take care of any environment mismatches.

```dockerfile
FROM python:3.6

RUN pip install yapf
ADD test.py /test.py
RUN yapf -d /test.py
```

**Comment by gwelymernans** [comment]
I don't have Docker...:-(

**Comment by alanhdu** [comment]
Hm... what system are you using? I'm on Ubuntu 16.04 and Python 3.6.4 (installed w/ Anaconda) -- are you on a different platform?

Alternatively, I'm also happy to contribute a patch (although it might take a while for me to get to it) -- do you have some intuition about where in the code base I should start poking at?

**Comment by gwelymernans** [comment]
I tried it on both Linux (Debian install) and Mac and it didn't replicate. If you'd like to do a patch, I would appreciate it. The code to look at is `format_token::AddWhitespacePrefix()`. Whatever is adding the spaces to the code does it through that function.

**Comment by alanhdu** [comment]
Huh -- I think I know where the reproducibility problem is.

On `master`, I can no longer reproduce the problem without the `yapf: enable` and `yapf: disable` . Without those comments, `yapf` works just fine (although on `0.20.1` the comments are unnecessary). In fact, on master I can reduce the problem further to:

```python
# yapf: disable
(f"""
        """)
# yapf: enable
```

The problem in the code is that in https://github.com/google/yapf/blob/fe6460f944e78ce3d64ece432bee1dddd18f861a/yapf/yapflib/format_token.py#L168-L169, `first_column` and `depth` are both 0 so `self.spaces_required_before` is set to `self.column`, which is why we're adding extra spaces. I'm still digging into why `first_column` is set to 0 though.

**Comment by alanhdu** [comment]
Ok -- root cause is that the regex in https://github.com/google/yapf/blob/fe6460f944e78ce3d64ece432bee1dddd18f861a/yapf/yapflib/format_token.py#L276-L278 doesn't account for format strings.

**Comment by gwelymernans** [comment]
Ah! Good catch. I'll need to check that other regexes aren't also affected by this.

Thank you for tracking this down!
