### ISSUE TITLE
1-liner yapf failure

### ISSUE THREAD

**Issue by mgoldey** [google/yapf#514]
The following code throws a ParseError when I attempt to yapf it :
```
print({**{5:2},**{3:4}})
```

Code executes using python 3.5 and 3.6 successfully, yielding {3:4,5:2}.

commit 6ae096bf5152dcc002c8622bb835f074560fbd24

**Comment by gwelymernans** [comment]
You need to use Python 3.6.4 or better it seems. This is because the `lib2to3` library may not be able to handle some Python3-isms (but I think it got fixed in 3.6.4).

**Comment by mgoldey** [comment]
Good catch - I just tried building and installing again with Python 3.6.3 and yapf could process this line.

Interesting that yapf built with Python 3.5.2 yapf cannot.

**Comment by gwelymernans** [comment]
I modified the README to say that people should use 3.6.4. Let me know if you have other issues. :-)
