### ISSUE TITLE
A .style.yapf with all the options

### ISSUE THREAD

**Issue by IlanHindy** [google/yapf#520]
Hi,
I want to create a .style.yapf file in my projec's home folder.
Is there a file with all the options that I can take and customize later ?
Ilan

**Comment by gwelymernans** [comment]
No, but what you can do is use the `--style-help` flag to get a dump of all of the flags with the default settings (in this case pep8). The format it outputs is the same format you need for the `.style.yapf` file. It also emits descriptions of the knobs, which is good. :-)
