### ISSUE TITLE
Matrix multiplicaation operator should be a BINARY_OPERATOR

### ISSUE THREAD

**Issue by Zaharid** [google/yapf#559]
I do not want spaces around '@'. Adding it to the configuration like:

```
no_spaces_around_selected_binary_operators=set("*,@,/,+,-")
```

does not work:
```
#delthis.py
def f(b,c):
    a = b+c@c
    return a
```

```
$ yapf delthis.py
def f(b, c):
    a = b+c @ c
    return a
```

I have checked that adding `'@'` in here:

https://github.com/google/yapf/blob/7cfb6b10b65e6db1f09583e5cc6a5f5bb7937f4f/yapf/yapflib/subtype_assigner.py#L198

seems to do the trick.

**Comment by medifle** [comment]
It seems this option does not work at all, no matter for * or /
```bash
python3 -m yapf --style="{based_on_style: pep8, NO_SPACES_AROUND_SELECTED_BINARY_OPERATORS: '*,/'}" hello.py
```
