### ISSUE TITLE
README.rst no longer renders

### ISSUE THREAD

**Issue by killarny** [google/yapf#572]
I don't know enough about reStructuredText to figure out why this is happening, or else I'd just submit a pull request, but something about the latest change introduced to README.rst does not render properly on GitHub or PyPI ([see here](https://pypi.org/project/yapf/)). The immediately prior commit for that file renders fine.

Here are links to view the last two commits in the history for README.rst at the time of filing this issue:
- 20d0c8f1774cf3843f4032f3e9ab02338bf98c75: [broken rendering](https://github.com/google/yapf/blob/20d0c8f1774cf3843f4032f3e9ab02338bf98c75/README.rst)
- 99c9bb1bd092028af7857c0bd12c3e56b83da665: [properly rendered](https://github.com/google/yapf/blob/99c9bb1bd092028af7857c0bd12c3e56b83da665/README.rst)

Here's a link to [the diff](https://github.com/google/yapf/compare/99c9bb1bd092028af7857c0bd12c3e56b83da665...20d0c8f1774cf3843f4032f3e9ab02338bf98c75#diff-88b99bb28683bd5b7e3a204826ead112) for those changes.

**Comment by gwelymernans** [comment]
Thanks for the report!
