### ISSUE TITLE
Breaks code using line continuation with backslashes

### ISSUE THREAD

**Issue by fpatz** [google/yapf#58]
This:

    text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. "\
           "Sed sit amet ipsum mauris. Maecenas congue ligula ac quam viverra nec consectetur "\
           "ante hendrerit. Donec et mollis dolor. Praesent et diam eget libero egestas mattis "\
           "sit amet vitae augue. Nam tincidunt congue enim, ut porta lorem lacinia consectetur. "\
           "Donec ut libero sed arcu vehicula ultricies a non tortor. Lorem ipsum dolor sit amet, "\
           "consectetur adipiscing elit. Aenean ut gravida lorem. Ut turpis felis, pulvinar ..."

gets convert to this:

    text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. "
    "Sed sit amet ipsum mauris. Maecenas congue ligula ac quam viverra nec consectetur "
    "ante hendrerit. Donec et mollis dolor. Praesent et diam eget libero egestas mattis "
    "sit amet vitae augue. Nam tincidunt congue enim, ut porta lorem lacinia consectetur. "
    "Donec ut libero sed arcu vehicula ultricies a non tortor. Lorem ipsum dolor sit amet, "
    "consectetur adipiscing elit. Aenean ut gravida lorem. Ut turpis felis, pulvinar ..."

That is, the backslashes causing the string literals to be considered one statement are removed, effectively cutting off the string after the first line.

**Comment by gwelymernans** [comment]
Oy! Reason #44215 why I hate backslash-newline continuations (or really any line continuations (I'm looking at you, Fortran!)) in languages. I'll see what we can do here...
