### ISSUE TITLE
indent_dictionary_value=true generates unnecessary parentheses around value in nested dict

### ISSUE THREAD

**Issue by Quanyails** [google/yapf#581]
Hi there! This is my first time contributing an issue, so please let me know if I can do to make the process easier!

Version: `yapf==0.22.0`

`.style.yapf`:
```ini
[style]
indent_dictionary_value = true
```

Input:
```python
my_dict = {
    'key':  # Some comment about the key
        {
            'nested_key': 1,
        },
}
```

Output:
```python
my_dict = {
    'key':  # Some comment about the key
        {
            'nested_key': (1),
        },
}
```

Every time we feed the output back into yapf, an additional pair of parentheses is added to the value.

The extra parentheses are not generated when the comment is moved after the opening curly bracket or elsewhere. While this issue is easy to work around, the cause is unexpected and takes time to debug.

**Comment by gwelymernans** [comment]
Whoa! This is bad!! It certainly shouldn't be doing this...I'll fix.
