### ISSUE TITLE
multi-line doc string formating when indent size changes

### ISSUE THREAD

**Issue by djhenderson** [google/yapf#60]
I have this code (from primepairs.py, not authored by me) which is indented with two spaces, and includes a multi-line doc string.

```
def prod(iterable):
  """ Multiplies entries in a List, for example
      prod( [2,3,4,5] ) is 120
  """
  return reduce(operator.mul, iterable, 1)
```

which get reformatted by yapf with no options in python 3.5a2 as:

```
def prod(iterable):
    """ Multiplies entries in a List, for example
      prod( [2,3,4,5] ) is 120
  """
    return reduce(operator.mul, iterable, 1)
```

The result is correct python, and acceptable to pep8, but not visually appealing.

The case where a multi-line string literal is used as a doc string, is different from the case where the string is used to initialize a variable. In the latter case, the string end delimiter must not be moved. In the first case, the string end delimiter location can be moved to align with the string start delimiter.

**Comment by gwelymernans** [comment]
Hmm...okay. Though I might make it an option. If we reformat the docstring, it could go over the allowable column limit, requiring human intervention. (I don't want to put "line reflowing" logic into YAPF. That would be a bit much, me thinks.)

**Comment by mtlynch** [comment]
I just ran into this as well. The ideal would be if YAPF did line reflowing, but I understand that's a huge task.

I'm fine with human intervention to fix the overflowing line size. YAPF already does overflow the line, just not consistently:

```
$ more docstring.py
def foo(bar, baz):
  """Performs a foo by fzzing baz. Caller is responsible for releasing the lock.

  Args:
    bar: An instance of the Bar class that's been artisanally designed for this
      function.
    baz: Any old Bar class instance will do.

  Returns:
    A fzz'd and foo'd baz that the caller must take ownership for and raise like
    it was their own offspring.
  """
  return None

```

**Current**:
```
$ yapf --style google docstring.py 
def foo(bar, baz):
    """Performs a foo by fzzing baz. Caller is responsible for releasing the lock.

  Args:
    bar: An instance of the Bar class that's been artisanally designed for this
      function.
    baz: Any old Bar class instance will do.

  Returns:
    A fzz'd and foo'd baz that the caller must take ownership for and raise like
    it was their own offspring.
  """
    return None
```
Note that the `"""Performs a foo by...` line is 82 characters

**Desired**:
```
def foo(bar, baz):
    """Performs a foo by fzzing baz. Caller is responsible for releasing the lock.

    Args:
      bar: An instance of the Bar class that's been artisanally designed for this
        function.
      baz: Any old Bar class instance will do.

    Returns:
      A fzz'd and foo'd baz that the caller must take ownership for and raise like
      it was their own offspring.
    """
    return None
```

The lines go over the limit but it makes the change consistently.

**Comment by hayd** [comment]
see also https://pypi.python.org/pypi/docformatter

**Comment by mtlynch** [comment]
Thanks for the tip @hayd!

**Comment by gwelymernans** [comment]
Thanks for the pointer, @hayd. This fell off of my plate, so to speak. I'm glad someone has thought enough to write a docstring reformatter. :-)

**Comment by bwendling** [comment]
The docformatter is the best option here.
