### ISSUE TITLE
Closing parenthesis / bracket on own line, no comma required.

### ISSUE THREAD

**Issue by tony** [google/yapf#606]
My apologies if there's already a knob for this. I don't think their is. Pretty much every combination I've found wants a trailing comma to put the closing of a dict or arguments on a new line.

I want closing parents/brackets on new lines. Without having to add a comma, in what in my situation is hundreds of places.

I want to be able to have this without having to place a closing comma.

Is there another knob for this combo?

We have a `SPLIT_BEFORE_FIRST_ARGUMENT`...

We could have a `SPLIT_BEFORE_LAST_ARGUMENT`?

e.g.

Before: 
```python
    app.redis_connection_jobs  = Redis.from_url(app.config['JOBS_REDIS_URL'])
    app.scheduler = Scheduler(connection=app.redis_connection_jobs, queue=queue_low)
```

After:
```python
    app.redis_connection_jobs = Redis.from_url(app.config['JOBS_REDIS_URL'])
    app.scheduler = Scheduler(
        connection=app.redis_connection_jobs, queue=queue_low)
```

What I want (note there's no trailing comma):

```
app.scheduler = Scheduler(
    connection=app.redis_connection_jobs, queue=queue_low
)
```

See also: https://github.com/google/yapf/issues/251#issuecomment-218443506

**Comment by jasonmhite** [comment]
I would also like this behavior.

I'd also add that it'd also be nice to have a switch to force *always* adding a trailing comma when indenting. I prefer to have trailing commas on every line of a multiline expression, so that I can add/rearrange arguments without having to change any other lines.

**Comment by gwelymernans** [comment]
I think you want some of the settings in the Facebook style:

```
python -m yapf --style facebook /tmp/x.py
def _():
    app.redis_connection_jobs = Redis.from_url(app.config['JOBS_REDIS_URL'])
    app.scheduler = Scheduler(
        connection=app.redis_connection_jobs, queue=queue_low
    )
```

**Comment by tony** [comment]
@gwelymernans That looks so good. I've been looking for this behavior for a long time!

https://github.com/google/yapf/blob/v0.23.0/yapf/yapflib/style.py#L341 (in case anyone is interested)

**Comment by tony** [comment]
I think this answers the question? I am going to close this now.

**Comment by tony** [comment]
@gwelymernans Thank you!
