### ISSUE TITLE
'no spaces around operators '

### ISSUE THREAD

**Issue by salof90** [google/yapf#608]

**Comment by salof90** [comment]
Did the 'no spaces around operators' convention change?

The last version released 0.23 requires no spaces around operators, while in version 0.22 spaces were required. Is this by design or a bug?

**Comment by grossman83** [comment]
I can verify this too. I don't think it's a feature. It is definitely an issue. yapf 0.22.0 worked fine on this point, but 0.23.0 is causing me trouble. It's taking lines like this:
`if dog > cat:`

and converting them to:
`if dog> cat:`

or
`if dog >cat:`

Neither of which makes any sense. This was not happening on 0.22.0 but now is on 0.23.0

**Comment by gwelymernans** [comment]
It's a bug. I'll try to revert the changes.

**Comment by salof90** [comment]
still broken in version 0.24
