### ISSUE TITLE
ParseError on Python 3 code using yield from syntax

### ISSUE THREAD

**Issue by gpshead** [google/yapf#61]
I was running yapf under Python 3.4.0 on some Python 3.4 code and got this when it encountered a yield from:

lib2to3.pgen2.parse.ParseError: bad input: type=1, value='from', context=(' ', (201, 28))

This appears to be a [lib2to3 bug - issue19511](https://bugs.python.org/issue19511).  Is it even possible to work around that within yapf?

A (painful) workaround for now for the modern yield from users is to just comment out the yield from lines and undo that after formatting.

**Comment by eliben** [comment]
I think this goes away in version > 3.4.0 (we had it reported https://github.com/google/yapf/issues/55 and elsewhere)

**Comment by eliben** [comment]
I definitely don't see it in Python 3.5

**Comment by eliben** [comment]
This was fixed in upstream Python / lib2to3 in revision  `90211:094615256a54`, which (I believe) went into 3.4.1

I bumped the required version for yapf.
