### ISSUE TITLE
USE_TAB does nothing currently

### ISSUE THREAD

**Issue by kevinleestone** [google/yapf#63]
At the moment, USE_TAB is not implemented.

**Comment by eliben** [comment]
Tabs are evil and should die in a fire :-D

Seriously, though, you are right! We may consider removing this option altogether.

**Comment by kevinleestone** [comment]
That's so funny. I love tabs, but I'm probably in the vast minority :)

**Comment by gwelymernans** [comment]
What eliben@ said! ;-) When I added that option, it was basically an attempt to honor something that's not in wide use. And it fell to the wayside. I don't *mind* adding support for it, but to tell the truth it's not at the top of our list...though we would happily take contributions.
