### ISSUE TITLE
Add a knob that turns formatting off

### ISSUE THREAD

**Issue by mnieber** [google/yapf#648]
I would like to turn off formatting for an entire subtree. This could be achieved by adding a knob that turns all formatting off (like clang-format has). Formatting for a subtree can then be turned off by placing an appropriate `.style.yapf` in that subtree.

**Comment by mnieber** [comment]
To answer my own feature request: this behaviour can be achieved by placing an empty `.style.yapf` file in the subtree.

**Comment by mnieber** [comment]
I don't know why I thought that using an empty `.style.yapf` file solved it, but it seems it doesn't, so I will reopen the issue.

**Comment by gwelymernans** [comment]
Does the `--exclude` flag work?

**Comment by mnieber** [comment]
@gwelymernans For my use case it would not be a good solution, because I'm calling yapf through a Sublime Text plugin. It would a hassle to have different yapf invocations in each project,

**Comment by ewjoachim** [comment]
Looks like you'd better tell Sublime to only yapfize some projects (maybe disable it by default and enable it in your workespace settings ?)

**Comment by mnieber** [comment]
I don't think it would be better :-). You can compare it to how
`.gitignore` is used: instead of having to exclude files with `--exclude`
when calling `git add`, it's much more convenient when the filetree already
contains a `.gitignore` file that excludes things for you. Similarly, it's
convenient when parts of the subtree are excluded by default from
yapf-izing.

This is especially important when working with several people on a source
tree. You don't want to have to tell each collaborator which files they
should exclude when calling yapf.

**Comment by ewjoachim** [comment]
Ah, I misread, you're talking about a subtree, not the whole tree, sorry.

**Comment by gwelymernans** [comment]
@mnieber You can add a `.yapfignore` file. I think this should do what you want it to.

https://github.com/google/yapf#excluding-files-from-formatting-yapfignore
