### ISSUE TITLE
Whitespace changes are made outside of --lines

### ISSUE THREAD

**Issue by hayd** [google/yapf#66]
For example:

```
code = """

if a:     b


if c:
        to_much      + indent

        same



#comment

#   trailing whitespace    """

FormatCode(code, lines=[(3, 3)])
"""if a: b

if c:
    to_much + indent

    same

#comment

#   trailing whitespace
"""
```

I hoped that only line 3 (the `if a: b`) to be modified.

I think the lines are all glued up [here](https://github.com/google/yapf/blob/cbe7ac48ce8f38b9555b50a035e060b0c350b238/yapf/yapflib/reformatter.py#L67-75) which doesn't have reference to the original source.

**Comment by hayd** [comment]
With the above example, I now see:

```
def print_code(code_string):
    for i, line in enumerate(code_string.splitlines(), start=1):
        print("%2d %s" % (i, line))

print_code(yapf.yapf_api.FormatCode(code, lines=[(3, 3)]))

 1 if a: b
 2
 3 if c:
 4     to_much      + indent
 5
 6     same
 7
 8 #comment
 9
10 #   trailing whitespace
```
That is, whitespace is still being modified (lines 1 and 2 are removed, and lines between `same` and `#comment`).

**Comment by gwelymernans** [comment]
I see. It isn't retaining vertical spacing. Okay.

**Comment by hayd** [comment]
(ps. The context for caring about this is adding a yapf backend for [pep8radius](https://github.com/hayd/pep8radius).)

**Comment by gwelymernans** [comment]
I think this should be fixed with ea8aa56.

Note: Indentations will still be reformatted. I don't know of a way to safely retain them in unformatted regions while modifying them in formatted regions...

**Comment by hayd** [comment]
I wrote [code to do exactly that](https://github.com/hhatto/autopep8/blob/53645b50653212c25b44a3fc2770a688b9e469b3/autopep8.py#L3020-L3209) in autopep8... it's pretty hairy, to say the least (although it was an interesting exercise). It's possible you *could* do it by storing the indentation in the tree, as opposed to just the indentation level, plus a little hoop jumping... tbh I'm not sure it's worth it for this edge case.

**Comment by gwelymernans** [comment]
That code shall haunt my dreams tonight. :-) Seriously though, I'd like to table that issue until / unless it becomes bothersome in the future.

There is another issue with disabling. Blank lines at the beginning and end of file will probably be removed still. The latter bit shouldn't be too difficult. But retaining blank lines at the beginning of the file will be a bit trickier I think...Let me think on it a bit.

**Comment by sbc100** [comment]
I ran into the same issue when trying to add yapf support for 'git cl format': https://codereview.chromium.org/1156743008/
