### ISSUE TITLE
.style.yapf is ignored in pycharm

### ISSUE THREAD

**Issue by spectralLight** [google/yapf#664]
Hello

I use yapf in pycharm:
"Code"->"Reformat code with YAPF"

i created the file .style.yapf:
```
[style]
based_on_style = google
column_limit = 120
```
I put it one time in /usr/local/bin/ and another time in the parent directory. However, the code is not formatted as expected according to the created file .yapf.style but with the default style. I tried the same with the setup.cfg. This also didn't worked.

How can I use the settings of the .style.yapf file in pycharm?

**Comment by kfuzesi** [comment]
Any updates about this issue?

**Comment by gwelymernans** [comment]
I'm sorry but I don't know anything about how pycharm uses yapf.
