### ISSUE TITLE
Installation not working on Mac

### ISSUE THREAD

**Issue by michK** [google/yapf#669]
Running `pip install yapf` seems to execute properly, but on completion `yapf file.py` gives `-bash: yapf: command not found`.

There is also no yapf executable in `/usr/local/bin/`

Running MacOS Mojave 10.14

**Comment by michK** [comment]
Thanks, this helps, but still just points me to where the yapf python library is installed, i.e. `site-packages/`, but there is no actual yapf binary stored there.

**Comment by michK** [comment]
I just realized that `python -m yapf file.py > out.py` seems to work. Is this the commonly used approach for Macs?

**Comment by gwelymernans** [comment]
No not 100% sure how it's used on Macs. :-( It might just be a thing that `pip` does...

**Comment by michK** [comment]
Well, I'm fine using it like that, thanks (-:

**Comment by drjuarez** [comment]
You should just symlink where it's installed. I'm using pyenv which is why it wasn't executable.  so...
1- Get the output from pip show as described above
2- `ln -s /path/to/step1output/yapf /usr/local/bin/yapf`
3- Now you can run from command line like `yapf myfile`
