### ISSUE TITLE
Spacing around binary operators

### ISSUE THREAD

**Issue by harahu** [google/yapf#670]
[PEP8](https://www.python.org/dev/peps/pep-0008/#other-recommendations) recommends a context dependent approach to whitespaces around binary operators:

> If operators with different priorities are used, consider adding whitespace around the operators with the lowest priority(ies). Use your own judgment; however, never use more than one space, and always have the same amount of whitespace on both sides of a binary operator.
> 
> Yes:
> 
> ```
>  i = i + 1
>  submitted += 1
>  x = x*2 - 1
>  hypot2 = x*x + y*y
>  c = (a+b) * (a-b)
> ```
> No:
> 
> ```
>  i=i+1
>  submitted +=1
>  x = x * 2 - 1
>  hypot2 = x * x + y * y
>  c = (a + b) * (a - b)
> ```

They recommend selecting whitespace based on the hierarchy of operators in the expression the operator appears. Would it be possible and/or desirable to reflect this in the yapf pep8 style?

**Comment by harahu** [comment]
Having now added an option for this (see #671), I am more or less happy. It could be added as default in the PEP8 style, but that might need some more testing and consideration from maintainers. Any thoughts @gwelymernans? Feel free to close this issue if you think it should stay as is for now.

**Comment by gwelymernans** [comment]
I was thinking about changing the default for PEP8. Is it a requirement for PEP8 or a "nice to have"?

**Comment by harahu** [comment]
Considering the wording it seems to be optional. I don't know anything more than what I quoted above, so hard to say.

**Comment by gwelymernans** [comment]
Okay, then let's leave it optional here. We can change it easily later if it's preferred by more people.

Thanks for your PR for this!
