### ISSUE TITLE
yapf: Unknown style option "SPLIT_BEFORE_ARITHMETIC_OPERATOR"

### ISSUE THREAD

**Issue by kohlka** [google/yapf#686]
This is my setup.cfg:
```
[yapf]
based_on_style = pep8
column_limit = 79
split_before_bitwise_operator = True
split_before_arithmetic_operator = True
split_before_closing_bracket = True
```
I'm getting the error "yapf: Unknown style option "SPLIT_BEFORE_ARITHMETIC_OPERATOR"" when I try to run yapf on my code.

I'm running yapf 0.26.0.

**Comment by apbard** [comment]
That knob has been added after the 0.26.0 release. 
To have it you have to wait the 0.27.0 release or install the development version:
```
sudo pip3 install git+https://github.com/google/yapf.git@master
```

**Comment by gwelymernans** [comment]
The new release is out. Please take a look.
