### ISSUE TITLE
How to format code per pair per line, thx!

### ISSUE THREAD

**Issue by fhqplzj** [google/yapf#695]
I have such code snippet `    column_pairs = [('label', ''), ('c_last_clk_cate_arm', ''),
                    ('c_last_clk_cate_tag', ''), ('c_last_clk_cate_ttag', ''),
                    ('c_max_clk_cate_10s_arm', ''),
                    ('c_max_clk_cate_10s_tag', ''),
                    ('c_max_clk_cate_10s_ttag', ''), ('c_scr_hour', ''),
                    ('c_user_context_info_ctr_10s', 0.0),
                    ('c_user_context_info_ctr_50s', 0.0),
                    ('c_user_context_info_ctr_5s', 0.0), ('i_arm', ''),
                    ('i_c', ''), ('i_ck', ''), ('i_ct', ''), ('i_ctr', ''),
                    ('i_ctr_7d', 0.0), ('i_fbspos', 0.0), ('i_from', 0.0),
                    ('i_ic', ''), ('i_rt', ''), ('i_rtf_nrot', ''),
                    ('i_rts', 0.0), ('i_rtype', ''), ('i_tk', ''),
                    ('i_tl', ''), ('i_uf', ''), ('i_ut', ''), ('i_utc', ''),
                    ('ir_ctr', 0.0), ('o_CkCtr', ''), ('o_CkRts', ''),
                    ('o_arm_ctr10s', ''), ('o_arm_pvafterclick', 0),
                    ('o_arm_pvclick10s', ''), ('o_arm_snafterclick', 0),
                    ('o_armpvclick30', ''), ('o_armpvclick7', ''),
                    ('o_armscore30', ''), ('o_armscore7', ''), ('o_tclkr', ''),
                    ('o_tpvacr', ''), ('o_tpvclkr', ''), ('o_tpvr', ''),
                    ('u_avg_tag_score', 0.0), ('u_clk_30d', 0.0),
                    ('u_clk_7d', 0.0), ('u_max_clk_30d_arm', ''),
                    ('u_max_clk_7d_arm', ''), ('u_max_ctr_30d_arm', ''),
                    ('u_max_ctr_7d_arm', ''), ('u_max_tag_score', 0.0),
                    ('u_min_tag_score', 0.0), ('x_Cer', 0), ('x_Cpr', 0),
                    ('x_context_match_info_arm_ctr_10s', 0.0),
                    ('x_context_match_info_arm_ctr_30d', 0.0),
                    ('x_context_match_info_arm_ctr_7d', 0.0),
                    ('x_context_match_info_ttag_ctr_10s', 0.0),
                    ('x_context_match_info_ttag_ctr_50s', 0.0),
                    ('x_context_match_info_ttag_ctr_5s', 0.0),
                    ('x_dis_sim_statis_beh', ''), ('x_dis_sim_statis_con', ''),
                    ('x_filtered_tag_cont_clk_ctrs', ''),
                    ('x_filtered_tag_ctrs', ''), ('x_filtered_tag_idfs', ''),
                    ('x_filtered_tag_names', ''), ('x_rtf_clk', ''),
                    ('x_rtf_cp', ''), ('x_rtf_rc', ''), ('x_rtf_rp', ''),
                    ('x_rtf_rr', ''), ('x_sim_cos', 0.0), ('x_sim_cos_2', 0.0),
                    ('x_uMt', 0), ('x_uMtp', ''),
                    ('x_url_pro_ntag_tag_names', ''),
                    ('x_url_pro_ntag_tag_scores', '')]
`

I want to format the code one pair per line, but do not know how to config the style file, can anyone help me? thx so much!

**Comment by apbard** [comment]
just add a final comma after the last tuple

**Comment by gwelymernans** [comment]
@apbard is correct. That's the best way to get yapf to do that for you.
