### ISSUE TITLE
'--lines=a-b' doesn't actually limit formatting to that line range

### ISSUE THREAD

**Issue by Strilanc** [google/yapf#706]
Repro. Create a file `test.py` with the following contents:

```python
def f():
                       print("overindented")


def g():
                       print("overindented")
```

Then run this command, which should only reformat the first two line (i.e. just `f`):

```bash
yapf --lines=1-2 test.py
```

Actual output:

```python
def f():
    print("too indented")


def g():
    print("too indented")
```

Expected output:

```python
def f():
    print("too indented")


def g():
                       print("overindented")
```

**Comment by gwelymernans** [comment]
This is intentional. Otherwise yapf could generate invalid code. Consider this:

```
def f():
                print("too indented")
          print("not as indented")
```

If you format only line 2 but don't adjust the other indents, you'll get this:

```
def f():
    print("too indented")
          print("not as indented")
```

**Comment by Strilanc** [comment]
@gwelymernans The README says this command line argument is supported. There are no caveats about affecting other lines, or pointers to more information that talk about the exact limitations. If you do not intend to support this functionality in full generality then the documentation should be updated to make this clearer.

In the case where two lines start at the same indentation, but the overall indentation is wrong, and the user has specified only one of the lines may be modified, then the correct behavior is to not change the indentation but still attempt to fix other formatting issues such as spacing between operators within the valid region.

**Comment by Strilanc** [comment]
@gwelymernans Is it *only* indentation that has this lines ignoring behavior?

**Comment by gwelymernans** [comment]
@Strilanc Yes, it's only indentation which will be affected.

**Comment by Strilanc** [comment]
Here is an exception to that rule:

```python
def f(*args):
    reflow = g(1, 2, 2, 2, 2, 3)


def g(*args):
    reflow = f(
        1,
        2,
        2,
        2,
        2,
        3)
```

Then run

```
yapf test.py --lines=5-5
```

Produces:

```python
def f(*args):
    reflow = g(1, 2, 2, 2, 2, 3)


def g(*args):
    reflow = f(
        1,
        2,
        2,
        2,
        2,
        3)
```

Which mutated lines other than line 5.

**Comment by gwelymernans** [comment]
It did? Which lines? They look identical. :-)

**Comment by Strilanc** [comment]
Bah, sorry, I pasted the wrong thing. The input is

```python
def f(*args):
    reflow = g(
        1,
        2,
        2,
        2,
        2,
        3)


def g(*args):
    reflow = f(
        1,
        2,
        2,
        2,
        2,
        3)
```

**Comment by Strilanc** [comment]
I will note that that particular example is not actually a problem IMO. It's just a corner case worth noting; that the lines spread to include entire statements or expressions.
