### ISSUE TITLE
Bad formatting for list of dicts

### ISSUE THREAD

**Issue by skicombinator** [google/yapf#720]
Hi.
I always appreciate you providing such a good tool.

When I tried to format the code below with yapf version 0.26.0, 
```python
dict_value = {
    'qwer': [
        {'path': '/usr/bin/long/path/file.ext',
         'hash': '30g98weu9812ue98jg0234qwer89y34234'
        },
        {'path': '/usr/bin/long/path/file.ext',
         'hash': '30g98weu9812ue98jg0234qwer89y34234'
        }
        ]
}
```

I got formatted like this:

```python
dict_value = {
    'qwer': [{
        'path': '/usr/bin/long/path/file.ext',
        'hash': '30g98weu9812ue98jg0234qwer89y34234'
    },   # why this closing bracket here?
             {
                 'path': '/usr/bin/long/path/file.ext',
                 'hash': '30g98weu9812ue98jg0234qwer89y34234'
             }]
}
```

I think some penalties for formatting list of dictionaries are suspicious.
Would you please check this issue?
Thank you.

**Comment by apbard** [comment]
This is a dup of #623
have you tried the 0.27?

**Comment by skicombinator** [comment]
Hi @apbard , thanks for your reply.
I think the issue you gave to me tells me what I wanted.
Thank you. I will try 0.27.0 version!
