### ISSUE TITLE
why codes of yapf don't follow the Google Python Style Guide?

### ISSUE THREAD

**Issue by rainchen** [google/yapf#721]
[Google Python Style Guide](http://google.github.io/styleguide/pyguide.html) says:

```
3.4 Indentation
Indent your code blocks with 4 spaces.
```

but the pylintrc config of yapf repo is using 2 spaces:

```
https://github.com/google/yapf/blob/master/pylintrc#L171
indent-string='  '
```

“style guide recommended formatter 's lint rules against style guide“, so who is standard?

**Comment by gwelymernans** [comment]
YAPF was developed internally at Google first. Our internal style more resembles Chromium's style, which uses 2 spaces among other things. (I don't know why we don't use Google's Style internally either.)
