### ISSUE TITLE
YAPF does not format to be compliant with PEP8 in conditional expression

### ISSUE THREAD

**Issue by skicombinator** [google/yapf#725]
Hi. 
The code below violates PEP8 at line 3, as flake8 says that 'E125: continuation line with same indent as next logical line'.
```python
def foo(param1, param2):
    if param1 is None and\
        param2:   # here
        return
```

When I ran YAPF to this code, it did not format anything. So, the code remains violating PEP8.
I think YAPF should correct this violation, but it didn't. 
I wonder why YAPF does not format the code like this pattern.

Thank you always.

**Comment by gwelymernans** [comment]
YAPF intentionally leaves lines with continuation markers in them alone. It assumes that the programmer knew what they were doing. :-)

**Comment by skicombinator** [comment]
@gwelymernans Thank you.
So is it ok to understand that every code lines that contain a trailing continuation marker is not formatted by YAPF?

**Comment by gwelymernans** [comment]
That's correct. It's probably not the best approach, but I wanted to avoid the complexity of potentially having to move it somewhere else.

**Comment by skicombinator** [comment]
Thanks for your help!
