### ISSUE TITLE
`SPLIT_ALL_COMMA_SEPARATED_VALUES`: Not Working

### ISSUE THREAD

**Issue by skicombinator** [google/yapf#726]
Hi again!

When I reformat the code below with option `--style='{split_all_comma_separated_values=True}'`
```python
dic = { 'name': name, 'size': size, 'runs': runs, 'succ': succ }
```

I thought the result should look like:
```python
dic = {
    'name': name,
    'size': size,
    'runs': runs,
    'succ': succ
}
```

But the result was:
```python
dic = {'name': name, 'size': size, 'runs': runs, 'succ': succ}
```

Did I get wrong about the option `split_all_comma_separated_values`? Or are the option just not working?

Thank you!

**Comment by thinkwelltwd** [comment]
The last entry in the dict needs a trailing comma. Then it'll split the values.

```python
dic = { 'name': name, 'size': size, 'runs': runs, 'succ': succ, }
```
Will become

```python
dic = {
    'name': name,
    'size': size,
    'runs': runs,
    'succ': succ,
}
```

**Comment by skicombinator** [comment]
@thinkwelltwd Thanks for your help.
I tried as your comment, and it worked perfectly.
It was me that misunderstood the option.
Thank you!
