### ISSUE TITLE
What style is yapf itself formatted in?

### ISSUE THREAD

**Issue by sbc100** [google/yapf#73]
The CONTRIBUTING files suggested that is it google style.. but running:

$ yapf -i --style=google yapf/__init__.py

generates a lot of changes.   Perhaps CONTRIBUTING should include a command to format yapf, using yapf?

Also, have you considered a project-wide .yapf (or .yapfrc or .yapfconfig) file that would allow project to automatically dictate their preferred style?

**Comment by gwelymernans** [comment]
It's formatted in Google's internal style. Though that file (and the style.py file) hasn't been run through YAPF just yet. :-) I have an issue that I want to address before running style.py through the formatter.
