### ISSUE TITLE
Checking if file exists before reading can cause problem in case of race conditions.

### ISSUE THREAD

**Issue by farziengineer** [google/yapf#731]
https://github.com/google/yapf/blob/f6bb994eb2b0e865244d7bf16cbedf568b7d65b2/yapf/yapflib/file_resources.py#L89-L90

The above snippet of code can cause problem in case of race condition, where file might be present at the time of `if os.path.exists(path)` but might not exist when we try to read the file and result in exception. The python EAFP(Easy to Ask for Forgiveness than Permission) philosophy suggests that we use a try catch block to avoid this problem. [Suggested changes](https://stackoverflow.com/a/56036903/8577285).
You can read [this stackoverflow answer ](https://stackoverflow.com/a/82852/8577285) to understand the problem more 
Can this issue be assigned to me? 
The above snippets can be replaced by the following.
```python
try:
    f = open(config_file)
except IOError as e:
    print("File can't be accessed")
else:
      with f:
        config = py3compat.ConfigParser()
        config.read_file(fd)
        if config.has_section('yapf'):
          return config_file```
@gwelymernans 
@sergiogiro

**Comment by gwelymernans** [comment]
Thanks!
