### ISSUE TITLE
Option for splitting lists vertically?

### ISSUE THREAD

**Issue by chrisspen** [google/yapf#751]
I have a number of lists in Django admins that are formatted like:

    class MyAdmin(ModelAdmin):

        list_display = (
             'some_value1',
             'some_value2',
            ...
             'some_value97',
             'some_value98',
             'some_value99',
        )

and I'd like to maintain this type of formatting, as it's much easier to scan this list vertically, then to reformat it into a one or more lines and scan it both horizontally and vertically.

When I run yapf, it reformats it to:

    class MyAdmin(ModelAdmin):

        list_display = ('some_value1', 'some_value2', ... 'some_value97', 'some_value98', 'some_value99')

I've read through all the options, but I don't see any "knob" to change this. I'm I just missing it, or is this formatting not supported?

My `.style.yapf` is:

    [style]
    based_on_style = pep8
    COLUMN_LIMIT = 160
    COALESCE_BRACKETS = true
    BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = true
    SPACES_BEFORE_COMMENT = 1
    SPLIT_COMPLEX_COMPREHENSION = true

**Comment by gwelymernans** [comment]
In your first example, you terminated the list with a comma, which should do the trick. In the second example, it's not. The trailing comma is a hint to yapf to split each element onto individual lines.

```
yapf --style pep8 < /tmp/x.py
class MyAdmin(ModelAdmin):

    list_display = (
        'some_value1',
        'some_value2',
        'some_value97',
        'some_value98',
        'some_value99',
    )
```
