### ISSUE TITLE
Documentation for .yapfignore patterns?

### ISSUE THREAD

**Issue by chrisspen** [google/yapf#754]
Is there any documentation for the types of patterns supported by `.yapfignore`? Very little's mentioned in the README. Are they like regex patterns or `.gitignore` patterns?

I'd like to exclude auto-generated Python files, like Django migrations, from Yapf. The only commonality these files have is that they're all under a `migration` folder and their names all begin with numbers. What pattern would I put in my `.yapfignore` file to exclude these from processing?

**Comment by gwelymernans** [comment]
This should be better documented for sure. I'll do that now.
