### ISSUE TITLE
[Feature Request]: add ability to parse "scm ignore" file to when doing `yapf -ri ./`

### ISSUE THREAD

**Issue by stevenleeS0ht** [google/yapf#759]
It would be awesome to add ability of reading 'scm ignore' file (.gitignore, .hgignore ...). It can significantly improve the situation when `yapf` stuck on the folder like `/.venv`, `venv` ...

It would be better to use `.yapfconf`, which can set the ignore rule definition to `.gitignore` or `hgignore` or something else.

**Comment by gwelymernans** [comment]
Hi! We have a `.yapfignore` already. :-)
