### ISSUE TITLE
Interaction between comments and \

### ISSUE THREAD

**Issue by mc-nathan** [google/yapf#76]
I've inherited a large code base that is not yet conforming to PEP8 and have been testing autopep8 and yapf.  When I tried yapf it introduced a syntax error which I've reduced to the following small test case (the original code is much uglier):

```
def fn(arg):
    v = fn2(key1 = True,
            #c1
            key2 = arg)\
                    .fn3()
```

gets turned into

```
def fn(arg):
    v = fn2(key1=True,  #c1 key2=arg)\
                    .fn3()
```

I haven't had a chance to dig deeper, but I do know that the comment and the \ are important.

**Comment by gwelymernans** [comment]
Gah! I will address this quickly.
