### ISSUE TITLE
yapf falsely ignores "yapf: disable" in import region

### ISSUE THREAD

**Issue by kkew3** [google/yapf#760]
Hi. I encountered this just now (minimal example):

```python
#yapf: disable
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
#yapf: enable
```

gets formatted to

```python
#yapf: disable
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
#yapf: enable
```

which leads to runtime error, as `matplotlib.use('Agg')` must precede the import of `matplotlib.pyplot`. Thanks!

yapf version: `0.28.0`

EDIT: using neither `#yapf: disable` nor `# yapf: disable` works.

**Comment by gwelymernans** [comment]
I don't see that. In fact, yapf shouldn't be moving `import` lines around at all, and definitely not statements...

```
python -m yapf < /tmp/x.py
#yapf: disable
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
#yapf: enable
```

What style options are you using?

**Comment by kkew3** [comment]
[style.ypaf.txt](https://github.com/google/yapf/files/3586348/style.ypaf.txt)

In fact, I myself, strangely, can no longer reproduce this issue either! I'm closing this for now. I'm reopening or reporting a new issue should it reoccur. Thanks a lot!
