### ISSUE TITLE
"yapf --lines=21-28-vv" returned error: ValueError: invalid literal for int() with base 10: '28-vv'^M No matching autocommands

### ISSUE THREAD

**Issue by tngreene** [google/yapf#761]
Hi,

I'd like to use YAPF with VIM, but I've never had much luck with it.

If I try to use :YAPF, with ranges or '<'> I get stuff like this:

`"yapf --lines=21-28-vv" returned error: ValueError: invalid literal for int() with base 10: '28-vv'^M
No matching autocommands`

Doesn't matter if it is code or a series of empty lines.

Simply running :YAPF seems to work.

yapf git commit: 126fc7eb85dec8fe3

```
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 20 2018 15:37:12)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-9
Compiled by hp@HP-PC
Huge version with GUI.  Features included (+) or not (-):
+acl                +clientserver       +dialog_con_gui     +file_in_path       +keymap             +modify_fname       +perl/dyn           +scrollbind         -termguicolors      +visual             +xpm_w32
+arabic             +clipboard          +diff               +find_in_path       +lambda             +mouse              +persistent_undo    +signs              +terminal           +visualextra        -xterm_save
+autocmd            +cmdline_compl      +digraphs           +float              +langmap            +mouseshape         -postscript         +smartindent        -tgetent            +viminfo            
+autoservername     +cmdline_hist       +directx            +folding            +libcall            +multi_byte_ime/dyn +printer            +startuptime        -termresponse       +vreplace           
+balloon_eval       +cmdline_info       -dnd                -footer             +linebreak          +multi_lang         +profile            +statusline         +textobjects        -vtp                
-balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +lispindent         +mzscheme/dyn       +python/dyn         -sun_workshop       +timers             +wildignore         
+browse             +conceal            +emacs_tags         -hangul_input       +listcmds           +netbeans_intg      +python3/dyn        +syntax             +title              +wildmenu           
++builtin_terms     +cryptv             +eval               +iconv/dyn          +localmap           +num64              +quickfix           +tag_binary         +toolbar            +windows            
+byte_offset        +cscope             +ex_extra           +insert_expand      +lua/dyn            +ole                +reltime            +tag_old_static     +user_commands      +writebackup        
+channel            +cursorbind         +extra_search       +job                +menu               +packages           +rightleft          -tag_any_white      +vertsplit          -xfontset           
+cindent            +cursorshape        +farsi              +jumplist           +mksession          +path_extra         +ruby/dyn           +tcl/dyn            +virtualedit        -xim                
 ```

Also using jedi-vim if that matters.

Result of `:python3 import sys; print(sys.version)`
`3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]`

But again, this has been a problem for a while. I try it again every few months to see if it gets fixed, and this time I decided not to be lazy and submit a bug report.

I don't have anything YAPF related in my vimrc except this:
```
    "python
    autocmd VimRCFileTypeCmds FileType python nnoremap <leader>= :.,.YAPF<cr>
```

But, that shouldn't matter, right?

**Comment by gwelymernans** [comment]
Have you tried the plugin in `plugins/vim`?

**Comment by tngreene** [comment]
Ah! I forgot this

`Plug 'google/yapf', { 'rtp': 'plugins/vim', 'for': 'python' }`

is also in my vimrc! I usually skip past that section because it is so set and forget.

Is that what you mean?

Can you be a little more clear about what you mean by "Have you tried the plugin in plugins/vim"? 

It has a lot of ambiguous meanings.

**Comment by gwelymernans** [comment]
By looking at the error message, you seem to be using: `--lines=21-28-vv`. What's the `-vv` bit about? You shouldn't do that.

**Comment by tngreene** [comment]
I mean, I'm not choosing todo anything besides use the addon out of the box.

I tried again today and got this
```
"yapf --lines=1-6-vv" returned error: operable program or batch file.^M
No matching autocommands
```

When running over this nonsense.
```
import this

x = {'a':       1,
        "b": (1,3,45555555555555555555555555555555555555555555555555555)

        }
```

**Comment by gwelymernans** [comment]
Where is the `-vv` coming from?

**Comment by tngreene** [comment]
from `yapf/plugins/vim/autoload/yapf.vim`

```
function! yapf#YAPF() range
  " Determine range to format.
  let l:line_ranges = a:firstline . '-' . a:lastline
  let l:cmd = 'yapf --lines=' . l:line_ranges . '-vv'
```

**Comment by tngreene** [comment]
Even removing `-vv` and the equals sign in `--lines=` doesn't seem to to make it work

```"yapf --lines 18-21" returned error: SyntaxError: invalid syntax^M```

**Comment by tngreene** [comment]
I realize that once I fixed the whole "no space between `-vv` and the lines end, and removing the equals sign it worked.

The syntax error came from trying to format a file with syntax errors in it.
