### ISSUE TITLE
Remove unused lambdas

### ISSUE THREAD

**Issue by AmjadHD** [google/yapf#768]
[pylint](https://pylint.readthedocs.io/en/latest/technical_reference/features.html#format-checker-messages) detects unused lambdas

>unnecessary-lambda (W0108):
>--
>Lambda may not be necessary Used when the body of a lambda expression is a function call on the same argument list as the lambda itself; such lambda expressions are in all but a few cases replaceable with the function being called in the body of the lambda.

can you add the possibility to remove those unused lambdas e.g (`lambda x: f(x)` -> `f`) ?

**Comment by gwelymernans** [comment]
YAPF isn't sophisticated enough to do this type of transformation. Also, it's our philosophy not to change the source code by removing or adding tokens. If you want to do this, I think the best way to achieve it is by using `lib2to3` and creating a "fixer" for it.

**Comment by AmjadHD** [comment]
Isn't lib2to3 meant to transform python 2 code to python 3 ?

**Comment by kamahen** [comment]
"Isn't lib2to3 meant to transform python 2 code to python 3 ?"

That was its original intent, but it can be used for many other kinds of code transformations. (And the original need somewhat went away with the introduction of the "six" library.)

**Comment by Trim21** [comment]
yapf is code formatter, it shouldn't change AST.
