### ISSUE TITLE
A blank line after method docstring missing in 0.28.0

### ISSUE THREAD

**Issue by yanqd0** [google/yapf#770]
In the version `0.28.0`, when `BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF` is `false` by default, there is a new bug in docstring only methods.

```python
class Demo:
    """
    Demo docs
    """
    def foo(self):
        """
        foo docs
        """
    def bar(self):
        """
        bar docs
        """
```

When `BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = true` is set, the format fixed.

```python
class Demo:
    """
    Demo docs
    """

    def foo(self):
        """
        foo docs
        """

    def bar(self):
        """
        bar docs
        """
```

There may be an implement error, because there should always be a blank line between `foo docs` and `bar` method, no matter what `BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF ` is.

**Comment by yanqd0** [comment]
This issue is closed. Dose that mean fixed or not to fix?

**Comment by gwelymernans** [comment]
It's been fixed.
