### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by mattseymour** [google/yapf#772]
Add support for python 3.8 new syntax changes:

- [Assignment expressions (walrus) :=](https://docs.python.org/3.9/whatsnew/3.8.html#assignment-expressions)
- [Positional-only parameters](https://docs.python.org/3.9/whatsnew/3.8.html#positional-only-parameters)

**Comment by kamahen** [comment]
It appears that lib2to3/Grammar.txt hasn't been updated to include the new features. (I've downloaded the Python 3.8 source [tarball](https://www.python.org/downloads/release/python-380/) and also looked at [github](https://github.com/python/cpython/commits/master/Lib/lib2to3/Grammar.txt).

**Comment by kamahen** [comment]
I've created https://bugs.python.org/issue38551

**Comment by kamahen** [comment]
https://bugs.python.org/issue36541 contains a proposed PR to bring lib2to3 up-to-date.

**Comment by p-patil** [comment]
Has support for python 3.8 syntax been added yet? I tried cloning the repo today and running on a file with the walrus operator, and got a `lib2to3.pgen2.parse.ParseError`, so I guess lib2to3 hasn't merged the PR for updating to 3.8 yet?

**Comment by ABitMoreDepth** [comment]
I just bumped into this as well

**Comment by kamahen** [comment]
This appears to solve the problem: https://bugs.python.org/issue36541

Also, Python 3.9 will add a positional-only grammar change: https://www.python.org/dev/peps/pep-0570/

**Comment by HacKanCuBa** [comment]
> Also, Python 3.9 will add a positional-only grammar change: https://www.python.org/dev/peps/pep-0570/

Which grammar change would that be? I couldn't find it in the PEP regarding current grammar for 3.8. Thanks!

**Comment by smokephil** [comment]
It works with Python 3.8.3rc1

**Comment by bentheiii** [comment]
Any update on this issue? lib2to3 is deprecated anyhow and YAPF is now unusable in newer projects...

**Comment by kamahen** [comment]
@gwelymernans - want to have a chat about this?  I might be persuaded to figure out what's needed and maybe even implement it (step 1: figure out which of the alternatives to lib2to3 is likely to be the best).

The big question: how popular is yapf vs black? I wouldn't want to put in a lot of effort if it turns out that the world has decided on the one-size-fits-all approach.

**Comment by gwelymernans** [comment]
@kamahen https://github.com/google/yapf/issues/448 is an open issue about this. I would love for someone to take this up, as my current projects don't allow for much time to focus on YAPF.

**Comment by HacKanCuBa** [comment]
How important is to still support Python2, which is deprecated, vs support Python3.8+? Isn't it easier to just drop support for v2? I know a ton of people is going to hate me, but its probably easier to just fork the project to support v2 and simply remove its support here.

**Comment by vapier** [comment]
dropping py2 sounds great.  seems like a good excuse to jump the version series too.

**Comment by kamahen** [comment]
Let's see if there's any discussion on this proposal (linked from item #448) for replacing lib2to3 with an augmented stdlib ast module:
https://mail.python.org/archives/list/python-ideas@python.org/thread/X2HJ6I6XLIGRZDB27HRHIVQC3RXNZAY4/

**Comment by gpshead** [comment]
https://github.com/python/cpython/pull/23759 should fix lib2to3 for the remaining positional only argument pep-570 syntax omission; that'll take a while to trickle down to various people's CPython installs.
