### ISSUE TITLE
"yapf: disable" might be ignored

### ISSUE THREAD

**Issue by hydrargyrum** [google/yapf#799]
When there's a `yapf: enable` followed by a `yapf: disable`, yapf might get lost and discard the `disable`.

## Separated

```python
# yapf: disable
a(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeee)
# yapf: enable

# yapf: disable
a(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeee)
# yapf: enable
```

There is no diff, as expected.

```
% yapf /tmp/ya3.py --diff
%
```

## Glued

Now, remove the separating newline:

```python
# yapf: disable
a(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeee)
# yapf: enable
# yapf: disable
a(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeee)
# yapf: enable
```

The block is reformatted, though it shouldn't.

```diff
--- /tmp/ya4.py	(original)
+++ /tmp/ya4.py	(reformatted)
@@ -2,5 +2,6 @@
 a(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeee)
 # yapf: enable
 # yapf: disable
-a(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccc, ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeee)
+a(bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, ccccccccccccccccccccccccccccccc,
+  ddddddddddddddddddddddd, eeeeeeeeeeeeeeeeeeeeeeeeeee)
 # yapf: enable
```

**Comment by tommai78101** [comment]
Have you tried `# yapf:enable` and `# yapf:disable` without the whitespaces in between "yapf" and "enable" or "disable"? This is how I'm using it on my local machine, running VS Code.

**Comment by hydrargyrum** [comment]
@tommai78101 it doesn't change anything, and anyway the behavior shouldn't be different whether or not there's an empty line between `yapf: disable` and `yapf: enable`

**Comment by gwelymernans** [comment]
I believe the issues is that the middle comment is seen as a single comment. YAPF may not detect that there's both an enable and disable in the same comment. It should be a simple fix.
