### ISSUE TITLE
`spaces_before_comment` is ignored sometimes

### ISSUE THREAD

**Issue by hydrargyrum** [google/yapf#802]
## Config

With this config:

```ini
[style]
based_on_style = pep8
spaces_before_comment = 2
split_all_top_level_comma_separated_values = true
```

## Code v1

And this file:

```python
KO = {
    'ABC': Abc, # abc
    'DEF': Def, # def
    'LOL': Lol, # wtf
    'GHI': Ghi,
    'JKL': Jkl,
}
```

I would expect comments to be reformatted by being prefixed with 2 spaces.
Unfortunately, yapf doesn't reformat anything.

```sh
% ~/.local/bin/yapf --style style.yapf --diff old.py && echo no diff
no diff
%
```

## Code v2

If I tweak the code, by just removing one line:

```diff
--- old.py	2020-01-20 16:13:26.229459664 +0100
+++ new.py	2020-01-20 16:13:56.537740670 +0100
@@ -3,5 +3,4 @@
     'DEF': Def, # def
     'LOL': Lol, # wtf
     'GHI': Ghi,
-    'JKL': Jkl,
 }
```

Suddenly yapf is willing to reformat the code:

```diff
% ~/.local/bin/yapf --style style.yapf --diff new.py && echo no diff 
--- new.py	(original)
+++ new.py	(reformatted)
@@ -1,6 +1,6 @@
 KO = {
-    'ABC': Abc, # abc
-    'DEF': Def, # def
-    'LOL': Lol, # wtf
+    'ABC': Abc,  # abc
+    'DEF': Def,  # def
+    'LOL': Lol,  # wtf
     'GHI': Ghi,
 }
```

**Comment by hydrargyrum** [comment]
Doing a few tests, it seems the reformatting is affected by the all-concatenated-line-length, even though it shouldn't, perhaps explaining why removing an entry affects it, even though it's buggy.

Set `COLUMN_LIMIT` to an absurdly low number (like 30) and see it's not reformatted at all, while it should. Not a single line of the example file exceeds 30 columns anyway, but if yapf concatenates all lines, it will exceed 30.
Set `COLUMN_LIMIT` to an absurdly high number (like 500) and see the comments are reformatted, and just the comments, as expected.

`split_all_top_level_comma_separated_values` mandates that the dict should be split in multiple lines whatever the line length, and `spaces_before_comment` affects spaces number.

**Comment by gwelymernans** [comment]
I haven't ran this, but I suspect what's happening is that there's some conflict going on, possibly related to column limit like you mentioned, where yapf can't find a suitable formatting style and so emits the code unaltered. For example, it could be that yapf requires the code to split but the contradicts itself by disallowing the split.
