### ISSUE TITLE
knob for spaces around brackets 

### ISSUE THREAD

**Issue by rski** [google/yapf#811]
Hi, 

I'd like to use YAPF for a codebase that uses this style:
```
def foo( arg1, arg2 ):
  a = [ 1, 2, 3 ]
```
Would you be open to a PR that adds support for such a config option?

**Comment by rski** [comment]
I see https://github.com/google/yapf/pull/657 exists, but that doesn't cover functions

**Comment by larslue** [comment]
I can hardly believe, that yapf would add a knob that more or less directly clashes with pep8.

https://www.python.org/dev/peps/pep-0008/#pet-peeves

**Comment by rski** [comment]
wade beat me to it
