### ISSUE TITLE
--style=google uses 2-space indentation

### ISSUE THREAD

**Issue by sbc100** [google/yapf#83]
It seems confusing to use 2-space indentation when the public google style guide uses 4:
https://google-styleguide.googlecode.com/svn/trunk/pyguide.html

Of course, I can see how this happened since the internal google guide uses 2-spaces.

Perhaps we should have another style called google-internal?   Or just have yapf use a custom style which is based on the public google style?

**Comment by gwelymernans** [comment]
I think the style that's closes to what YAPF uses is `chromium`. We've had this come up before. I think I'll just create a Chromium style and be done with it.

**Comment by sbc100** [comment]
Nice!  Thanks.
