### ISSUE TITLE
breaking function calls on keyword arguments

### ISSUE THREAD

**Issue by sbc100** [google/yapf#86]
I experimented with running yapf over a real codebase and found that many of the things it changed was the splitting on function calls across multiple lines when keyword arguments were used.

A common example is this:

```
parser.add_argument('-v', '--verbose', action='store_true',                      
                    help='Output extra information.')
```

YAPF always wants to turn this into:

```
parser.add_argument('-v', '--verbose',
                    action='store_true',
                    help='Output extra information.')
```

It seems that once it decides the break the line it insists on breaking for *every* keyword arg.

Note that this is not true for non-keyword args.  If I remove the keywords from the above example YAPF will leave it alone. 

Is this deliberate?  I don't think this is specified in pep8 or google guide is it?

**Comment by gwelymernans** [comment]
This is deliberate. It's a knob that several people asked for, but which isn't specified in the style guides. You can control this via the `SPLIT_BEFORE_NAMED_ASSIGNS` knob.

Another option is to try to replicate the original code's formatting: if they placed them all on single lines, then we could try to retain that. But that would be a larger enhancement change.

**Comment by sbc100** [comment]
Ah I see.  So none of the style guides (google, pep8, chromium) specify this, but its perfectly valid.    In these kinds of cases it seems that yapf is opinionated in a particular point.  Would it be good to document such cases?     In general does yapf always try to have an opinion?   Have you considered having a "don't care" option for cases like this, where the original code would be left unchanged, or would be against the philosophy of yapf?  (BTW, does clang format support "don't care"?)

**Comment by gwelymernans** [comment]
I believe that `clang-format` has a way to detect whether to "bin pack" things, which I believe is roughly the same as "don't care". There are a few things that YAPF has an opinion on, but mostly because of the personal preference of its creator. :-) In such cases, I tended towards adding a knob to control that. (But I'm sure to have missed some.) So I think that the knobs the way to document such things.  What do you think?

**Comment by sbc100** [comment]
Makes sense to me.

I guess there could be an argument that for all on knobs that are not specified in a spec it might be nice to support three value: YES, NO, DONT_CARE.   If that was supported we could default to DONT_CARE in the pep8 and google/chromium styles (since that actually don't care about some things).

I'm kind of on the fence about this though, since its really really nice to have a formatted where there is only one true way to format a piece of code.  Its either formatted or not formatted.

Anyway, I don't see any reason to leave this issue open, given that I know about that knob.
