### ISSUE TITLE
Demo Link https://yapf.now.sh/ Gives 404 Code: DEPLOYMENT_NOT_FOUND

### ISSUE THREAD

**Issue by thmsdnnr** [google/yapf#869]
The demo page https://yapf.now.sh linked to in the README's Introduction section is not working for me.

I get a 404 Page that displays: `Code: DEPLOYMENT_NOT_FOUND.`

The issue was also mentioned here https://github.com/google/yapf/issues/508#issuecomment-678806719, but I didn't find any open issues for it.

**Comment by Zenahr** [comment]
I can confirm that.

**Comment by ichard26** [comment]
Doing some research

**Comment by William04A** [comment]
I can confirm that as well.

**Comment by ichard26** [comment]
https://github.com/jpadilla/black-playground/issues/3#issuecomment-382202551 seems to provide some insight into what happened to yapf's demo:
> Custom domains on now require a premium plan, not worth for this imho. Might be able to run this on Heroku for free in my account, but will run out of free dyno hours(same thing eventually happened with https://yapf.now.sh).

**Comment by bwac2517** [comment]
Link shouldn't be in the readme if it 404s
