### ISSUE TITLE
Missing trailing comma after forced split

### ISSUE THREAD

**Issue by francois-rozet** [google/yapf#874]
After forced splits with `dedent_closing_brackets = true`, a trailing comma isn't added to the last element, although it should according to the Google code style:

> Trailing commas in sequences of items are recommended only when the closing container token ], ), or } does not appear on the same line as the final element...

Example:

```python
    def forward(self, input: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
```

is transformed to

```python
    def forward(
        self,
        input: torch.Tensor,
        target: torch.Tensor
    ) -> torch.Tensor:
```

while it should be

```python
    def forward(
        self,
        input: torch.Tensor,
        target: torch.Tensor,
    ) -> torch.Tensor:
```

**Comment by teresaejunior** [comment]
Duplcate of https://github.com/google/yapf/issues/274

**Comment by francois-rozet** [comment]
> Duplicate of #274?

It seems it is, indeed. I will close the issue then.
