### ISSUE TITLE
Check out what I made for you guys!

### ISSUE THREAD

**Issue by blacktop** [google/yapf#88]
https://github.com/blacktop/atom-python-yapf

Atom.io plugin to format Python files using YAPF

It's available and ready to use here:
 - https://atom.io/packages/python-yapf

**Comment by alexjurkiewicz** [comment]
As a YAPF & Atom user, nice! Would it be feasible to integrate with atom-beautify? A lot of people already have that installed, and it currently uses autopep8(?).

**Comment by fiatjaf** [comment]
This issue should have a more descriptive title.

**Comment by eliben** [comment]
Modified title of issues to make it more searchable.

Thanks!

**Comment by gwelymernans** [comment]
Yay! Thank you for the plugin. :+1:
