### ISSUE TITLE
Exluding directories fails on Windows due to \ vs / path separators.

### ISSUE THREAD

**Issue by bwoodsend** [google/yapf#880]
Currently using `--exclude` on a folder, as well putting one in the `.gitignore`, has no effect. I've dug through and found the culprit:

`IsIgnored()` (below) does the filtering. It knows it must strip leading `./`s from the paths it tests before applying `fnmatch()`.

https://github.com/google/yapf/blob/768267f3481259df9e2162968c9d5986074ec15c/yapf/yapflib/file_resources.py#L187-L192

But on Windows, `os.walk()` (the output of which gets fed to `IsIgnored()`) returns Windows style `.\file\name` paths which fail to have the `.\` prefix stripped so `IsIgnored()` always return false.

The easiest fix IMO is just to normalise paths to Posix style paths, then leave the `./` stripping code as is:
```diff
diff --git i/yapf/yapflib/file_resources.py w/yapf/yapflib/file_resources.py
index 50b4687..477e4c1 100644
--- i/yapf/yapflib/file_resources.py
+++ w/yapf/yapflib/file_resources.py
@@ -186,6 +186,9 @@ def _FindPythonFiles(filenames, recursive, exclude):
 
 def IsIgnored(path, exclude):
   """Return True if filename matches any patterns in exclude."""
+  if os.name == "nt":
+    # Normalise "\" separators to "/" on Windows.
+    path = path.replace("\\", "/")
   path = path.lstrip('/')
   while path.startswith('./'):
     path = path[2:]
```

Shall I put the above into a pull request?

**Comment by gwelymernans** [comment]
Perhaps it's better to use `os.path.sep` instead?

**Comment by bwoodsend** [comment]
Yes, that probably would be cleaner. As Windows accepts both `/` and `\`,  using `os.path.sep` would require that the input `path` always uses `\` for Windows (which `os.walk()` does so this shouldn't be a problem). Is it easier to submit a PR or just for you to push a patch?

**Comment by gwelymernans** [comment]
Go ahead and create a PR for this. (Make sure to update the `CHANGELOG` file and create a tests if possible.) Thanks!
