### ISSUE TITLE
[FEATURE REQUEST] Show re-formated files only for verbose mode as black?

### ISSUE THREAD

**Issue by hiyyg** [google/yapf#917]
Hi, currently the `-vv` flag show all processing files, but I want to see the re-formated files only as what `black` does by default. 

I notice there is a `has_change` flag for each processed file, I think this feature can be added easily.

**Comment by rmekdma** [comment]
I want this feature too. `verbose` option could have an integer value for logging level. For example:

- `--verbose 0 (default)`: not verbose
- `--verbose 1`: print only changed files
- `--verbose 2`: print all logs

Or explicit string option could be also good. (`all`, `change`, `none`)

**Comment by rmekdma** [comment]
closed by https://github.com/google/yapf/pull/1054?
