### ISSUE TITLE
chained method/nested function call creates a ton of whitespace

### ISSUE THREAD

**Issue by kqr** [google/yapf#94]
The simple program

    def fn():
        return module \
               .method(Object(data,
                   fn2(arg)
               ))

seems to result in the mindboggling output of

    def fn():
        return module \
               .method(Object(data,
                                                  fn2(arg)
                              ))

I'm guessing yapf thinks it has combined two lines onto one, and then tries to visually align fn2, but it's not working out. This results is ridiculously long lines of whitespace in actual code, when there are many method calls chained on indvidual lines.

**Comment by gwelymernans** [comment]
FWIW, I haven't forgotten about this. It's actually non-trivial to address. :-/

**Comment by kqr** [comment]
It's cool! I'm eagerly waiting, and using yapf only on files which do not exhibit this problem in the meantime. :) @gwelymernans
