### ISSUE TITLE
What is meant by "penalty"?

### ISSUE THREAD

**Issue by djhoese** [google/yapf#945]
I'd like to make some customizations to the styling applied by yapf and I've looked through a lot of the knobs. I can make things do what I want I think, but I'm having trouble finding an explanation of what a "penalty" is. Could someone explain what it means? What are the units on the integer? In style.py why are some values relatively small in the pep8 style like 300 (or even 0) and some are really large like 10000.

https://github.com/google/yapf/blob/28cb5b748abb2af5e9e846dabf3f4dc836f53162/yapf/yapflib/style.py#L464-L473

Thanks for any help you can provide.

**Comment by gwelymernans** [comment]
A penalty means that when determining what the "optimal" splitting is for a line of code, a penalty for a splitting decision decreases the chance that the heuristic will split at that point.

For instance, we rarely want to split before a colon (`:`). So the penalty for splitting before one is set to `UNBREAKABLE` (actually just a very large number).

In the above list, `SPLIT_PENALTY_BEFORE_IF_EXPR=0` means that it's perfectly fine, and in fact preferable, to split before an `if` expression if a split needs to occur. This prevents something like this from happening (assuming it needs a line break in there):

```
x = [
    x**3 + 42
    for x in some_list if
    x > 2
]
```

The values assigned to penalties came about through trial-and-error.

**Comment by djhoese** [comment]
Thank you! I was thinking they were some kind of number of character offsets like "if we're at the end of an expression add <penalty> number of characters", but couldn't figure out how those numbers made sense in those cases. Sounds good to me. Thanks again.
