### ISSUE TITLE
Strange reformatting of inline dictionary declaration

### ISSUE THREAD

**Issue by sbc100** [google/yapf#95]
YAPF handles the following correctly (leaves it alone):

```
somequitelongvariablename.somemember[a, b] = {
    'somelongkey': 1,
    'someotherlongkey': 2
}
```

But if I add brackets around (a,b) I get the following output:

```
somequitelongvariablename.somemember[(
    a, b)] = {'somelongkey': 1,
              'someotherlongkey': 2}
```

Seems like a bug to me.

**Comment by gwelymernans** [comment]
Hmm...interesting. We try to not split a subscript, but we allow easy splitting after a `(`. So there's a conflict. But yeah, it's a bug...

**Comment by sbc100** [comment]
Thanks!
