### ISSUE TITLE
Allow formatting a parsed lib2to3 tree

### ISSUE THREAD

**Issue by superbobry** [google/yapf#951]
We have a tool which applies transformations from lib2to3 before calling `yapf_api.FormatCode`. This leads to redundant tokenization and parsing on the boundary between lib2to3 and YAPF, even though both use the same CST internally. 

Would you accept a PR adding `yapf_api.FormatTree` which would do exactly what `yapf_api.FormatCode` does, but without the parsing step?

**Comment by gwelymernans** [comment]
I assume you meant pass the result of your lib2to3 run into `yapf_api.FormatTree`? That would be fine, though I want to keep the same signature for `FormatTree`. So a function `FormatTree` calls that accepts the parsed tree, and FormatTree would be a thin wrapper around that call. Or something to that effect.

**Comment by gwelymernans** [comment]
Sure! I'll look at your RFC.

**Comment by superbobry** [comment]
Thanks! As an aside, I didn't find an easy way to figure out if any of the uwlines were modified, so `FormatTree` currently returns just the formatted source without the `modified` flag. Happy to amend that if we could figure out the right value for `modified`.

**Comment by gwelymernans** [comment]
I think at this level of abstraction, returning a `modified` flag wouldn't be appropriate. The input is a tree and the output is a string. We don't modify the tree. It's up to the caller to determine if something has changed, based on whatever rules they have for the formatter changing things.

Could you add a comment to the `CHANGELOG` file?
