### ISSUE TITLE
YAPF ignore configured via pyproject.toml does not take any effect

### ISSUE THREAD

**Issue by dclong** [google/yapf#955]
I have a Python project and configured YAPF ignore via `pyproject.toml` but it doesn't take any effect. If add equivalent ignore patterns into `.yapfignore`, it works.

**Comment by hirosassa** [comment]
@dclong Cloud you give me a small example to reproduce this? I'd like to investigate it.

**Comment by dclong** [comment]
@hirosassa https://github.com/dclong/debug_yapf_ignore is a Git repo to illustrate this issue. The repo has 2 branches: `pyproject` and `yapfignore`. Both branches has a simple Python script named `proj/example.py`. The branch `pyproject` configures `yapf` using `pyproject.toml` while the branch `yapfignore` configures `yapf` using `.style.yapf` and `.yapfignore`. The ignored yapf patterns are equivalent (`proj/example.py` is ignored). I expect nothing to be formatted when running `yapf -ir proj` since the file `proj/example.py` is ignored. This is the case for the branch `yapfignore` but not for the branch `pyproject`.

**Comment by hirosassa** [comment]
@dclong Thank you for implementing the example repo! I checked it and found that `yapf`'s current main branch ignores `proj/example.py` correctly. My changes on your repo is as follows:

```
git diff
diff --git a/pyproject.toml b/pyproject.toml
index 94a3ec6..c76b333 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -9,7 +9,7 @@ python = ">=3.7.1"

 [tool.poetry.dev-dependencies]
 pytest = ">=5.2"
-
+yapf = {git = "https://github.com/google/yapf", rev = "main"}

 [tool.yapf]
 based_on_style = "facebook"
```

I tried following a sequence of commands:

```shell
poetry install
poetry run yapf -dr proj
```

**Comment by dclong** [comment]
@hirosassa Sorry, my bad. And thank you very much for your help!

**Comment by hirosassa** [comment]
@dclong Hi, yapf 0.32 is released! We can user yapfignore feature on pyproject.toml.

**Comment by dclong** [comment]
@hirosassa,

Thank you so much for the update! I will try the latest release of yapf.
