### ISSUE TITLE
README error: [yapf] vs [style]

### ISSUE THREAD

**Issue by NelsonMinar** [google/yapf#961]
I'm a brand new user, so this could be wrong. The README says your style file puts style declarations in a [yapf] block. That doesn't work for me with yapf 0.31.0 from pip; it looks like it should be a [style] block.

I noted there's still a few occurrences of [yapf] in the code. Mostly comments, but also one test. Maybe those should be updated too.

(Feel free to look at my closed pull request for a doc fix. https://github.com/google/yapf/pull/960 )

**Comment by gwelymernans** [comment]
Thanks for pointing this out, @NelsonMinar. The example shows one of several ways one can specify the style in a config file (there are about 4 different ones). But it does look like `[style]` is used more than any others.
