### ISSUE TITLE
spacing in slices and annotations

### ISSUE THREAD

**Issue by anntzer** [google/yapf#97]
Currently,

```
$ echo 'foo[bar + bar : quux]' | yapf
foo[bar + bar:quux]
```

which was correct by a (strict) reading of earlier versions of PEP8.  Now PEP8 has been (sanely, imho) updated to prefer spaces around the colon (although putting spaces neither around the colon nor around the + sign is neither marked as correct nor as incorrect).

Likewise,

```
$ echo 'def foo(bar: baz=1): pass' | yapf
def foo(bar: baz=1):
    pass
```

PEP8 now prefers `def foo(bar: baz = 1): ...`

**Comment by azmd** [comment]
Thanks, that is great!

**Comment by petobens** [comment]
+1 the "updated" PEP8 preferences seem clearly better/nicer. @gwelymernans any chance of implementing this? (especially the second one regarding annotations on keyword arguments)

**Comment by gwelymernans** [comment]
It's possible...They new spacing stuff will need to be looked at actually. I think that it recommends things like `1 + 2*3 - 4`.
