### ISSUE TITLE
Can I ignore something like E501?

### ISSUE THREAD

**Issue by axiaoxin** [google/yapf#98]

**Comment by hayd** [comment]
You can use the COLUMN_LIMIT is the style setting:  https://github.com/google/yapf/blob/e5591550ee91df9f70d1dc5ba047cfa2e54e18b9/yapf/yapflib/style.py#L48, presumably setting it really high would suffice.

**Comment by gwelymernans** [comment]
Unlike `autopep8`, we don't all you to disable formatting by error numbers. That's because `autopep8` is built with a different purpose than `yapf`. You can disable formatting over the section of code though:

```
# yapf: disable
 ... lines that are too long ...
# yapf: enable
```
