### ISSUE TITLE
[Question]yapfignore not working in pyproject.toml

### ISSUE THREAD

**Issue by UponTheSky** [google/yapf#984]
Thank you for reading this issue.

I'm currently working on a Django project and I want to use `yapf` for formatting.

However, as I am trying to use `pyproject.toml` for excluding files, it does not work.

```toml
[tool.yapfignore]
ignore_patterns = [
  '**/migrations]*.py',
  'manage.py',
  'venv/*',
]
```

On the other hand, what makes it interesting is that the command line behaves differently and successfully ignores the files I want.

```sh
yapf --recursive --exclude '**/migrations/*.py' --exclude 'manage.py' --exclude 'venv/*' .
```

I still cannot figure out what would be the problem with this discrepancy.

At the moment, a part my dependencies is like the following:

```txt
pylint==2.12.2
pylint-django==2.4.4
pylint-plugin-utils==0.6
yapf==0.31.0
```

and my current Python version is `3.9.9`.

If there is any problem with the way I make this issue post, please don't hesitate to point it out!

Thank you in advance!

**Comment by UponTheSky** [comment]
It still doesn't work, so I had a workaround, `.yapfignore`.

```
**/migrations/*.py
manage.py
venv/*
```

I have to admit that the project would be a bit more complex, but I think `pyproject.toml` is currently not working for excluding files and directories. Any suggestions?

**Comment by hirosassa** [comment]
Hi @UponTheSky
Related to https://github.com/google/yapf/issues/955 , I think yapf version is the problem.
Latest version (0.32.0) of yapf released 26 Dec (ref: https://pypi.org/project/yapf/#history).
In my local PC, yapf ignore feature correctly worked. Please check.

**Comment by UponTheSky** [comment]
@hirosassa 
Thank you for your reply! I appreciate your kindness.

Oh, I have missed the issue https://github.com/google/yapf/issues/955
I have checked and now it worked.

Now this issue is resolved so I close it.
